cd "..\build\Debug"
del Debug.zip /q
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Client.exe
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Client.exe.config
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Client.exe.nlog
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Common.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.IPluginInterface.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Localization.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Updater.exe
"C:\Program Files\7-Zip\7z.exe" a Debug.zip HtmlAgilityPack.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Ionic.Zip.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip MahApps.Metro.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip NAudio.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Newtonsoft.Json.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip NLog.dll
#"C:\Program Files\7-Zip\7z.exe" a Debug.zip SocketIOClient.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip System.Windows.Interactivity.dll
#"C:\Program Files\7-Zip\7z.exe" a Debug.zip WebSocket4Net.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Licenses\*.txt
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\aruba.wav
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\FFXIVAPP.Plugin.Event.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Informer\FFXIVAPP.Plugin.Informer.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Informer\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Informer\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Log\FFXIVAPP.Plugin.Log.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Log\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Log\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Widgets\FFXIVAPP.Plugin.Widgets.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Widgets\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Widgets\PluginInfo.xml

cd "..\Release"
del Release.zip /q
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Client.exe
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Client.exe.config
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Client.exe.nlog
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Common.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.IPluginInterface.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Localization.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Updater.exe
"C:\Program Files\7-Zip\7z.exe" a Release.zip HtmlAgilityPack.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Ionic.Zip.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip MahApps.Metro.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip NAudio.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Newtonsoft.Json.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip NLog.dll
#"C:\Program Files\7-Zip\7z.exe" a Release.zip SocketIOClient.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip System.Windows.Interactivity.dll
#"C:\Program Files\7-Zip\7z.exe" a Release.zip WebSocket4Net.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Licenses\*.txt
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\aruba.wav
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\FFXIVAPP.Plugin.Event.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Informer\FFXIVAPP.Plugin.Informer.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Informer\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Informer\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Log\FFXIVAPP.Plugin.Log.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Log\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Log\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Widgets\FFXIVAPP.Plugin.Widgets.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Widgets\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Widgets\PluginInfo.xml

cd "..\SmartAssembly"
del SmartAssembly.zip /q
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Client.exe
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Client.exe.config
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Client.exe.nlog
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Common.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.IPluginInterface.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Localization.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Updater.exe
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip HtmlAgilityPack.dll
#"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Ionic.Zip.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip MahApps.Metro.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip NAudio.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Newtonsoft.Json.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip NLog.dll
#"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip SocketIOClient.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip System.Windows.Interactivity.dll
#"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip WebSocket4Net.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Licenses\*.txt
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\aruba.wav
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\FFXIVAPP.Plugin.Event.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Informer\FFXIVAPP.Plugin.Informer.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Informer\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Informer\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Log\FFXIVAPP.Plugin.Log.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Log\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Log\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Widgets\FFXIVAPP.Plugin.Widgets.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Widgets\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Widgets\PluginInfo.xml