//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVAPP.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Application_UpgradeRequired {
            get {
                return ((bool)(this["Application_UpgradeRequired"]));
            }
            set {
                this["Application_UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Top {
            get {
                return ((int)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Left {
            get {
                return ((int)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public global::System.Globalization.CultureInfo Culture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CultureSet {
            get {
                return ((bool)(this["CultureSet"]));
            }
            set {
                this["CultureSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Red|Light</string>
  <string>Green|Light</string>
  <string>Blue|Light</string>
  <string>Purple|Light</string>
  <string>Orange|Light</string>
  <string>Red|Dark</string>
  <string>Green|Dark</string>
  <string>Blue|Dark</string>
  <string>Purple|Dark</string>
  <string>Orange|Dark</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ThemeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ThemeList"]));
            }
            set {
                this["ThemeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue|Light")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Adamantoise</string>\r\n  <string>Aegis</string>\r\n  <string>Alexander</strin" +
            "g>\r\n  <string>Anima</string>\r\n  <string>Atomos</string>\r\n  <string>Bahamut</stri" +
            "ng>\r\n  <string>Balmung</string>\r\n  <string>Behemoth</string>\r\n  <string>Cactuar<" +
            "/string>\r\n  <string>Carbuncle</string>\r\n  <string>Cerberus</string>\r\n  <string>C" +
            "hocobo</string>\r\n  <string>Coeurl</string>\r\n  <string>Diabolos</string>\r\n  <stri" +
            "ng>Durandal</string>\r\n  <string>Excalibur</string>\r\n  <string>Exodus</string>\r\n " +
            " <string>Faerie</string>\r\n  <string>Fenrir</string>\r\n  <string>Garuda</string>\r\n" +
            "  <string>Gilgamesh</string>\r\n  <string>Goblin</string>\r\n  <string>Gungnir</stri" +
            "ng>\r\n  <string>Hades</string>\r\n  <string>Hyperion</string>\r\n  <string>Ifrit</str" +
            "ing>\r\n  <string>Ixion</string>\r\n  <string>Kujata</string>\r\n  <string>Lamia</stri" +
            "ng>\r\n  <string>Leviathan</string>\r\n  <string>Malboro</string>\r\n  <string>Mandrag" +
            "ora</string>\r\n  <string>Masamune</string>\r\n  <string>Midgardsormr</string>\r\n  <s" +
            "tring>Moogle</string>\r\n  <string>Odin</string>\r\n  <string>Phoenix</string>\r\n  <s" +
            "tring>Ragnarok</string>\r\n  <string>Ramuh</string>\r\n  <string>Ridill</string>\r\n  " +
            "<string>Sargatanas</string>\r\n  <string>Shiva</string>\r\n  <string>Siren</string>\r" +
            "\n  <string>Tiamat</string>\r\n  <string>Titan</string>\r\n  <string>Tonberry</string" +
            ">\r\n  <string>Typhon</string>\r\n  <string>Ultima</string>\r\n  <string>Ultros</strin" +
            "g>\r\n  <string>Valefor</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerList"]));
            }
            set {
                this["ServerList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>English</string>
  <string>Japanese</string>
  <string>French</string>
  <string>German</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GameLanguageList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameLanguageList"]));
            }
            set {
                this["GameLanguageList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string GameLanguage {
            get {
                return ((string)(this["GameLanguage"]));
            }
            set {
                this["GameLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CICUID {
            get {
                return ((string)(this["CICUID"]));
            }
            set {
                this["CICUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
            set {
                this["ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CharacterName {
            get {
                return ((string)(this["CharacterName"]));
            }
            set {
                this["CharacterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstName {
            get {
                return ((string)(this["FirstName"]));
            }
            set {
                this["FirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastName {
            get {
                return ((string)(this["LastName"]));
            }
            set {
                this["LastName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily LicenseFont {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["LicenseFont"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowPluginCommands {
            get {
                return ((bool)(this["AllowPluginCommands"]));
            }
            set {
                this["AllowPluginCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveLog {
            get {
                return ((bool)(this["SaveLog"]));
            }
            set {
                this["SaveLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableNLog {
            get {
                return ((bool)(this["EnableNLog"]));
            }
            set {
                this["EnableNLog"] = value;
            }
        }
    }
}
