//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVAPP.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Application_UpgradeRequired {
            get {
                return ((bool)(this["Application_UpgradeRequired"]));
            }
            set {
                this["Application_UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Top {
            get {
                return ((int)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Left {
            get {
                return ((int)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public global::System.Globalization.CultureInfo Culture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CultureSet {
            get {
                return ((bool)(this["CultureSet"]));
            }
            set {
                this["CultureSet"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Red|Light</string>
  <string>Green|Light</string>
  <string>Blue|Light</string>
  <string>Purple|Light</string>
  <string>Orange|Light</string>
  <string>Brown|Light</string>
  <string>Cobalt|Light</string>
  <string>Crimson|Light</string>
  <string>Cyan|Light</string>
  <string>Emerald|Light</string>
  <string>Indigo|Light</string>
  <string>Magenta|Light</string>
  <string>Mauve|Light</string>
  <string>Olive|Light</string>
  <string>Sienna|Light</string>
  <string>Steel|Light</string>
  <string>Teal|Light</string>
  <string>Violet|Light</string>
  <string>Red|Dark</string>
  <string>Green|Dark</string>
  <string>Blue|Dark</string>
  <string>Purple|Dark</string>
  <string>Orange|Dark</string>
  <string>Brown|Dark</string>
  <string>Cobalt|Dark</string>
  <string>Crimson|Dark</string>
  <string>Cyan|Dark</string>
  <string>Emerald|Dark</string>
  <string>Indigo|Dark</string>
  <string>Magenta|Dark</string>
  <string>Mauve|Dark</string>
  <string>Olive|Dark</string>
  <string>Sienna|Dark</string>
  <string>Steel|Dark</string>
  <string>Teal|Dark</string>
  <string>Violet|Dark</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ThemeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ThemeList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue|Light")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Atomos</string>\r\n  <string>Bahamut</string>\r\n  <string>Chocobo</string>\r\n " +
            " <string>Mandragora</string>\r\n  <string>Tiamat</string>\r\n  <string>Tonberry</str" +
            "ing>\r\n  <string>Garuda</string>\r\n  <string>Ifrit</string>\r\n  <string>Ramuh</stri" +
            "ng>\r\n  <string>Titan</string>\r\n  <string>Adamantoise</string>\r\n  <string>Behemot" +
            "h</string>\r\n  <string>Cactuar</string>\r\n  <string>Cerberus</string>\r\n  <string>C" +
            "oeurl</string>\r\n  <string>Goblin</string>\r\n  <string>Malboro</string>\r\n  <string" +
            ">Moogle</string>\r\n  <string>Ultros</string>\r\n  <string>Diabolos</string>\r\n  <str" +
            "ing>Gilgamesh</string>\r\n  <string>Leviathan</string>\r\n  <string>Midgardsormr</st" +
            "ring>\r\n  <string>Odin</string>\r\n  <string>Shiva</string>\r\n  <string>Ridill</stri" +
            "ng>\r\n  <string>Masamune</string>\r\n  <string>Durandal</string>\r\n  <string>Aegis</" +
            "string>\r\n  <string>Gungnir</string>\r\n  <string>Sargatanas</string>\r\n  <string>Ba" +
            "lmung</string>\r\n  <string>Hyperion</string>\r\n  <string>Excalibur</string>\r\n  <st" +
            "ring>Ragnarok</string>\r\n  <string>Alexander</string>\r\n  <string>Anima</string>\r\n" +
            "  <string>Carbuncle</string>\r\n  <string>Fenrir</string>\r\n  <string>Hades</string" +
            ">\r\n  <string>Ixion</string>\r\n  <string>Kujata</string>\r\n  <string>Typhon</string" +
            ">\r\n  <string>Ultima</string>\r\n  <string>Valefor</string>\r\n  <string>Exodus</stri" +
            "ng>\r\n  <string>Faerie</string>\r\n  <string>Lamia</string>\r\n  <string>Phoenix</str" +
            "ing>\r\n  <string>Siren</string>\r\n  <string>Pandaemonium</string>\r\n  <string>Unico" +
            "rn</string>\r\n  <string>Yojimbo</string>\r\n  <string>Famfrit</string>\r\n  <string>L" +
            "ich</string>\r\n  <string>Mateus</string>\r\n  <string>Asura</string>\r\n  <string>Bel" +
            "ias</string>\r\n  <string>Zeromus</string>\r\n  <string>Brynhildr</string>\r\n  <strin" +
            "g>Zalera</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>English</string>
  <string>Japanese</string>
  <string>French</string>
  <string>German</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GameLanguageList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameLanguageList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string GameLanguage {
            get {
                return ((string)(this["GameLanguage"]));
            }
            set {
                this["GameLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CICUID {
            get {
                return ((string)(this["CICUID"]));
            }
            set {
                this["CICUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
            set {
                this["ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CharacterName {
            get {
                return ((string)(this["CharacterName"]));
            }
            set {
                this["CharacterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstName {
            get {
                return ((string)(this["FirstName"]));
            }
            set {
                this["FirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastName {
            get {
                return ((string)(this["LastName"]));
            }
            set {
                this["LastName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily LicenseFont {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["LicenseFont"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowPluginCommands {
            get {
                return ((bool)(this["AllowPluginCommands"]));
            }
            set {
                this["AllowPluginCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveLog {
            get {
                return ((bool)(this["SaveLog"]));
            }
            set {
                this["SaveLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableNLog {
            get {
                return ((bool)(this["EnableNLog"]));
            }
            set {
                this["EnableNLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowXIVDBIntegration {
            get {
                return ((bool)(this["AllowXIVDBIntegration"]));
            }
            set {
                this["AllowXIVDBIntegration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableHelpLabels {
            get {
                return ((bool)(this["EnableHelpLabels"]));
            }
            set {
                this["EnableHelpLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TopMost {
            get {
                return ((bool)(this["TopMost"]));
            }
            set {
                this["TopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color ChatBackgroundColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ChatBackgroundColor"]));
            }
            set {
                this["ChatBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800080")]
        public global::System.Windows.Media.Color TimeStampColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TimeStampColor"]));
            }
            set {
                this["TimeStampColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 12pt")]
        public global::System.Drawing.Font ChatFont {
            get {
                return ((global::System.Drawing.Font)(this["ChatFont"]));
            }
            set {
                this["ChatFont"] = value;
            }
        }
    }
}
