//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVAPP.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Application_UpgradeRequired {
            get {
                return ((bool)(this["Application_UpgradeRequired"]));
            }
            set {
                this["Application_UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Top {
            get {
                return ((int)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Left {
            get {
                return ((int)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public global::System.Globalization.CultureInfo Culture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CultureSet {
            get {
                return ((bool)(this["CultureSet"]));
            }
            set {
                this["CultureSet"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Red|Light</string>\r\n  <string>Green|Light</string>\r\n  <string>Blue|Light</" +
            "string>\r\n  <string>Purple|Light</string>\r\n  <string>Orange|Light</string>\r\n  <st" +
            "ring>Brown|Light</string>\r\n  <string>Cobalt|Light</string>\r\n  <string>Crimson|Li" +
            "ght</string>\r\n  <string>Cyan|Light</string>\r\n  <string>Emerald|Light</string>\r\n " +
            " <string>Indigo|Light</string>\r\n  <string>Magenta|Light</string>\r\n  <string>Mauv" +
            "e|Light</string>\r\n  <string>Olive|Light</string>\r\n  <string>Sienna|Light</string" +
            ">\r\n  <string>Steel|Light</string>\r\n  <string>Teal|Light</string>\r\n  <string>Viol" +
            "et|Light</string>\r\n  <string>Amber|Light</string>\r\n  <string>Yellow|Light</strin" +
            "g>\r\n  <string>Lime|Light</string>\r\n  <string>Pink|Light</string>\r\n  <string>Red|" +
            "Dark</string>\r\n  <string>Green|Dark</string>\r\n  <string>Blue|Dark</string>\r\n  <s" +
            "tring>Purple|Dark</string>\r\n  <string>Orange|Dark</string>\r\n  <string>Brown|Dark" +
            "</string>\r\n  <string>Cobalt|Dark</string>\r\n  <string>Crimson|Dark</string>\r\n  <s" +
            "tring>Cyan|Dark</string>\r\n  <string>Emerald|Dark</string>\r\n  <string>Indigo|Dark" +
            "</string>\r\n  <string>Magenta|Dark</string>\r\n  <string>Mauve|Dark</string>\r\n  <st" +
            "ring>Olive|Dark</string>\r\n  <string>Sienna|Dark</string>\r\n  <string>Steel|Dark</" +
            "string>\r\n  <string>Teal|Dark</string>\r\n  <string>Violet|Dark</string>\r\n  <string" +
            ">Amber|Dark</string>\r\n  <string>Yellow|Dark</string>\r\n  <string>Lime|Dark</strin" +
            "g>\r\n  <string>Pink|Dark</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ThemeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ThemeList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue|Light")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Adamantoise</string>\r\n  <string>Aegis</string>\r\n  <string>Alexander</strin" +
            "g>\r\n  <string>Anima</string>\r\n  <string>Asura</string>\r\n  <string>Atomos</string" +
            ">\r\n  <string>Bahamut</string>\r\n  <string>Balmung</string>\r\n  <string>Behemoth</s" +
            "tring>\r\n  <string>Belias</string>\r\n  <string>Brynhildr</string>\r\n  <string>Cactu" +
            "ar</string>\r\n  <string>Carbuncle</string>\r\n  <string>Cerberus</string>\r\n  <strin" +
            "g>Chocobo</string>\r\n  <string>Coeurl</string>\r\n  <string>Diabolos</string>\r\n  <s" +
            "tring>Durandal</string>\r\n  <string>Excalibur</string>\r\n  <string>Exodus</string>" +
            "\r\n  <string>Faerie</string>\r\n  <string>Famfrit</string>\r\n  <string>Fenrir</strin" +
            "g>\r\n  <string>Garuda</string>\r\n  <string>Gilgamesh</string>\r\n  <string>Goblin</s" +
            "tring>\r\n  <string>Gungnir</string>\r\n  <string>Hades</string>\r\n  <string>Hyperion" +
            "</string>\r\n  <string>Ifrit</string>\r\n  <string>Ixion</string>\r\n  <string>Jenova<" +
            "/string>\r\n  <string>Kujata</string>\r\n  <string>Lamia</string>\r\n  <string>Leviath" +
            "an</string>\r\n  <string>Lich</string>\r\n  <string>Malboro</string>\r\n  <string>Mand" +
            "ragora</string>\r\n  <string>Masamune</string>\r\n  <string>Mateus</string>\r\n  <stri" +
            "ng>Midgardsormr</string>\r\n  <string>Moogle</string>\r\n  <string>Odin</string>\r\n  " +
            "<string>Pandaemonium</string>\r\n  <string>Phoenix</string>\r\n  <string>Ragnarok</s" +
            "tring>\r\n  <string>Ramuh</string>\r\n  <string>Ridill</string>\r\n  <string>Sargatana" +
            "s</string>\r\n  <string>Shinryu</string>\r\n  <string>Shiva</string>\r\n  <string>Sire" +
            "n</string>\r\n  <string>Tiamat</string>\r\n  <string>Titan</string>\r\n  <string>Tonbe" +
            "rry</string>\r\n  <string>Typhon</string>\r\n  <string>Ultima</string>\r\n  <string>Ul" +
            "tros</string>\r\n  <string>Unicorn</string>\r\n  <string>Valefor</string>\r\n  <string" +
            ">Yojimbo</string>\r\n  <string>Zalera</string>\r\n  <string>Zeromus</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>English</string>
  <string>Japanese</string>
  <string>French</string>
  <string>German</string>
  <string>Chinese</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GameLanguageList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameLanguageList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string GameLanguage {
            get {
                return ((string)(this["GameLanguage"]));
            }
            set {
                this["GameLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CICUID {
            get {
                return ((string)(this["CICUID"]));
            }
            set {
                this["CICUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
            set {
                this["ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CharacterName {
            get {
                return ((string)(this["CharacterName"]));
            }
            set {
                this["CharacterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstName {
            get {
                return ((string)(this["FirstName"]));
            }
            set {
                this["FirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastName {
            get {
                return ((string)(this["LastName"]));
            }
            set {
                this["LastName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily LicenseFont {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["LicenseFont"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveLog {
            get {
                return ((bool)(this["SaveLog"]));
            }
            set {
                this["SaveLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableNLog {
            get {
                return ((bool)(this["EnableNLog"]));
            }
            set {
                this["EnableNLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowXIVDBIntegration {
            get {
                return ((bool)(this["AllowXIVDBIntegration"]));
            }
            set {
                this["AllowXIVDBIntegration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableHelpLabels {
            get {
                return ((bool)(this["EnableHelpLabels"]));
            }
            set {
                this["EnableHelpLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TopMost {
            get {
                return ((bool)(this["TopMost"]));
            }
            set {
                this["TopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color ChatBackgroundColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ChatBackgroundColor"]));
            }
            set {
                this["ChatBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800080")]
        public global::System.Windows.Media.Color TimeStampColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TimeStampColor"]));
            }
            set {
                this["TimeStampColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 12pt")]
        public global::System.Drawing.Font ChatFont {
            get {
                return ((global::System.Drawing.Font)(this["ChatFont"]));
            }
            set {
                this["ChatFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parse")]
        public string HomePlugin {
            get {
                return ((string)(this["HomePlugin"]));
            }
            set {
                this["HomePlugin"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HomePluginList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HomePluginList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string UIScale {
            get {
                return ((string)(this["UIScale"]));
            }
            set {
                this["UIScale"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0.8</string>
  <string>0.9</string>
  <string>1.0</string>
  <string>1.1</string>
  <string>1.2</string>
  <string>1.3</string>
  <string>1.4</string>
  <string>1.5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIScaleList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIScaleList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Default")]
        public string DefaultAudioDevice {
            get {
                return ((string)(this["DefaultAudioDevice"]));
            }
            set {
                this["DefaultAudioDevice"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>System Default</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultAudioDeviceList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultAudioDeviceList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string ActorWorkerRefresh {
            get {
                return ((string)(this["ActorWorkerRefresh"]));
            }
            set {
                this["ActorWorkerRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string ChatLogWorkerRefresh {
            get {
                return ((string)(this["ChatLogWorkerRefresh"]));
            }
            set {
                this["ChatLogWorkerRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PartyInfoWorkerRefresh {
            get {
                return ((string)(this["PartyInfoWorkerRefresh"]));
            }
            set {
                this["PartyInfoWorkerRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PlayerInfoWorkerRefresh {
            get {
                return ((string)(this["PlayerInfoWorkerRefresh"]));
            }
            set {
                this["PlayerInfoWorkerRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string TargetWorkerRefresh {
            get {
                return ((string)(this["TargetWorkerRefresh"]));
            }
            set {
                this["TargetWorkerRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string MonsterWorkerRefresh {
            get {
                return ((string)(this["MonsterWorkerRefresh"]));
            }
            set {
                this["MonsterWorkerRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string InventoryWorkerRefresh {
            get {
                return ((string)(this["InventoryWorkerRefresh"]));
            }
            set {
                this["InventoryWorkerRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultNetworkInterface {
            get {
                return ((string)(this["DefaultNetworkInterface"]));
            }
            set {
                this["DefaultNetworkInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableNetworkReading {
            get {
                return ((bool)(this["EnableNetworkReading"]));
            }
            set {
                this["EnableNetworkReading"] = value;
            }
        }
    }
}
