cd "..\build\Debug"
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Client.exe
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Client.exe.config
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Client.exe.nlog
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.Common.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip FFXIVAPP.IPluginInterface.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip HtmlAgilityPack.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip MahApps.Metro.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Newtonsoft.Json.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip NLog.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip System.Windows.Interactivity.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Licenses\*.txt
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Chat\FFXIVAPP.Plugin.Chat.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Chat\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Chat\Settings.xml
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\aruba.wav
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\FFXIVAPP.Plugin.Event.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Event\Settings.xml
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Log\FFXIVAPP.Plugin.Log.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Log\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Log\Settings.xml
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Parse\FFXIVAPP.Plugin.Parse.dll
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Parse\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Debug.zip Plugins\FFXIVAPP.Plugin.Parse\Settings.xml

cd "..\Release"
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Client.exe
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Client.exe.config
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Client.exe.nlog
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.Common.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip FFXIVAPP.IPluginInterface.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip HtmlAgilityPack.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip MahApps.Metro.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Newtonsoft.Json.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip NLog.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip System.Windows.Interactivity.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Licenses\
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Chat\FFXIVAPP.Plugin.Chat.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Chat\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Chat\Settings.xml
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\aruba.wav
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\FFXIVAPP.Plugin.Event.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Event\Settings.xml
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Log\FFXIVAPP.Plugin.Log.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Log\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Log\Settings.xml
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Parse\FFXIVAPP.Plugin.Parse.dll
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Parse\Logo.png
"C:\Program Files\7-Zip\7z.exe" a Release.zip Plugins\FFXIVAPP.Plugin.Parse\Settings.xml

cd "..\SmartAssembly"
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Client.exe
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Client.exe.config
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Client.exe.nlog
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.Common.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip FFXIVAPP.IPluginInterface.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip HtmlAgilityPack.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip MahApps.Metro.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Newtonsoft.Json.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip NLog.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip System.Windows.Interactivity.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Licenses\*.txt
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Chat\FFXIVAPP.Plugin.Chat.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Chat\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Chat\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\aruba.wav
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\FFXIVAPP.Plugin.Event.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Event\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Log\FFXIVAPP.Plugin.Log.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Log\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Log\PluginInfo.xml
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Parse\FFXIVAPP.Plugin.Parse.dll
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Parse\Logo.png
"C:\Program Files\7-Zip\7z.exe" a SmartAssembly.zip Plugins\FFXIVAPP.Plugin.Parse\PluginInfo.xml