// FFXIVAPP.Client
// German.Parse.cs
// 
// © 2013 Ryan Wilson

namespace FFXIVAPP.Client.Localization
{
    public static partial class German
    {
        private static void SetParseLocale()
        {
            Dictionary.Add("parse_PLACEHOLDER", "*PH*");
            Dictionary.Add("parse_TotalOverallDamageHeader", "Total");
            Dictionary.Add("parse_RegularDamageHeader", "Reg");
            Dictionary.Add("parse_CriticalDamageHeader", "Crit");
            Dictionary.Add("parse_TotalDamageActionsUsedHeader", "Used");
            Dictionary.Add("parse_DPSHeader", "DPS");
            Dictionary.Add("parse_DamageRegHitHeader", "Hit");
            Dictionary.Add("parse_DamageRegMissHeader", "Miss");
            Dictionary.Add("parse_DamageRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_DamageRegLowHeader", "Low");
            Dictionary.Add("parse_DamageRegHighHeader", "High");
            Dictionary.Add("parse_DamageRegAverageHeader", "Avg");
            Dictionary.Add("parse_DamageRegModHeader", "Reg Mod");
            Dictionary.Add("parse_DamageRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_DamageCritHitHeader", "C.Hit");
            Dictionary.Add("parse_DamageCritPercentHeader", "Crit %");
            Dictionary.Add("parse_DamageCritLowHeader", "C.Low");
            Dictionary.Add("parse_DamageCritHighHeader", "C.High");
            Dictionary.Add("parse_DamageCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_DamageCritModHeader", "Crit Mod");
            Dictionary.Add("parse_DamageCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_DamageCounterHeader", "Counter");
            Dictionary.Add("parse_DamageCounterPercentHeader", "Counter %");
            Dictionary.Add("parse_DamageCounterModHeader", "C. Mod");
            Dictionary.Add("parse_DamageCounterModAverageHeader", "C. Mod Avg");
            Dictionary.Add("parse_DamageBlockHeader", "Block");
            Dictionary.Add("parse_DamageBlockPercentHeader", "Block %");
            Dictionary.Add("parse_DamageBlockModHeader", "B. Mod");
            Dictionary.Add("parse_DamageBlockModAverageHeader", "B. Mod Avg");
            Dictionary.Add("parse_DamageParryHeader", "Parry");
            Dictionary.Add("parse_DamageParryPercentHeader", "Parry %");
            Dictionary.Add("parse_DamageParryModHeader", "P. Mod");
            Dictionary.Add("parse_DamageParryModAverageHeader", "P. Mod Avg");
            Dictionary.Add("parse_DamageResistHeader", "Resist");
            Dictionary.Add("parse_DamageResistPercentHeader", "Resist %");
            Dictionary.Add("parse_DamageResistModHeader", "R. Mod");
            Dictionary.Add("parse_DamageResistModAverageHeader", "R. Mod Avg");
            Dictionary.Add("parse_DamageEvadeHeader", "Evade");
            Dictionary.Add("parse_DamageEvadePercentHeader", "Evade %");
            Dictionary.Add("parse_DamageEvadeModHeader", "E. Mod");
            Dictionary.Add("parse_DamageEvadeModAverageHeader", "E. Mod Avg");
            Dictionary.Add("parse_TotalOverallDamageOverTimeHeader", "Total");
            Dictionary.Add("parse_RegularDamageOverTimeHeader", "Reg");
            Dictionary.Add("parse_CriticalDamageOverTimeHeader", "Crit");
            Dictionary.Add("parse_TotalDamageOverTimeActionsUsedHeader", "Used");
            Dictionary.Add("parse_DOTPSHeader", "DOTPS");
            Dictionary.Add("parse_DamageOverTimeRegHitHeader", "Hit");
            Dictionary.Add("parse_DamageOverTimeRegMissHeader", "Miss");
            Dictionary.Add("parse_DamageOverTimeRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_DamageOverTimeRegLowHeader", "Low");
            Dictionary.Add("parse_DamageOverTimeRegHighHeader", "High");
            Dictionary.Add("parse_DamageOverTimeRegAverageHeader", "Avg");
            Dictionary.Add("parse_DamageOverTimeRegModHeader", "Reg Mod");
            Dictionary.Add("parse_DamageOverTimeRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_DamageOverTimeCritHitHeader", "C.Hit");
            Dictionary.Add("parse_DamageOverTimeCritPercentHeader", "Crit %");
            Dictionary.Add("parse_DamageOverTimeCritLowHeader", "C.Low");
            Dictionary.Add("parse_DamageOverTimeCritHighHeader", "C.High");
            Dictionary.Add("parse_DamageOverTimeCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_DamageOverTimeCritModHeader", "Crit Mod");
            Dictionary.Add("parse_DamageOverTimeCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_TotalOverallHealingHeader", "Total");
            Dictionary.Add("parse_RegularHealingHeader", "Reg");
            Dictionary.Add("parse_CriticalHealingHeader", "Crit");
            Dictionary.Add("parse_TotalHealingActionsUsedHeader", "Used");
            Dictionary.Add("parse_HPSHeader", "HPS");
            Dictionary.Add("parse_HealingRegHitHeader", "Hit");
            Dictionary.Add("parse_HealingRegLowHeader", "Low");
            Dictionary.Add("parse_HealingRegHighHeader", "High");
            Dictionary.Add("parse_HealingRegAverageHeader", "Avg");
            Dictionary.Add("parse_HealingRegModHeader", "Reg Mod");
            Dictionary.Add("parse_HealingRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_HealingCritHitHeader", "C.Hit");
            Dictionary.Add("parse_HealingCritPercentHeader", "Crit %");
            Dictionary.Add("parse_HealingCritLowHeader", "C.Low");
            Dictionary.Add("parse_HealingCritHighHeader", "C.High");
            Dictionary.Add("parse_HealingCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_HealingCritModHeader", "Crit Mod");
            Dictionary.Add("parse_HealingCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_TotalOverallHealingOverHealingHeader", "Total");
            Dictionary.Add("parse_RegularHealingOverHealingHeader", "Reg");
            Dictionary.Add("parse_CriticalHealingOverHealingHeader", "Crit");
            Dictionary.Add("parse_TotalHealingOverHealingActionsUsedHeader", "Used");
            Dictionary.Add("parse_HOHPSHeader", "HOHPS");
            Dictionary.Add("parse_HealingOverHealingRegHitHeader", "Hit");
            Dictionary.Add("parse_HealingOverHealingRegLowHeader", "Low");
            Dictionary.Add("parse_HealingOverHealingRegHighHeader", "High");
            Dictionary.Add("parse_HealingOverHealingRegAverageHeader", "Avg");
            Dictionary.Add("parse_HealingOverHealingRegModHeader", "Reg Mod");
            Dictionary.Add("parse_HealingOverHealingRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_HealingOverHealingCritHitHeader", "C.Hit");
            Dictionary.Add("parse_HealingOverHealingCritPercentHeader", "Crit %");
            Dictionary.Add("parse_HealingOverHealingCritLowHeader", "C.Low");
            Dictionary.Add("parse_HealingOverHealingCritHighHeader", "C.High");
            Dictionary.Add("parse_HealingOverHealingCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_HealingOverHealingCritModHeader", "Crit Mod");
            Dictionary.Add("parse_HealingOverHealingCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_TotalOverallHealingOverTimeHeader", "Total");
            Dictionary.Add("parse_RegularHealingOverTimeHeader", "Reg");
            Dictionary.Add("parse_CriticalHealingOverTimeHeader", "Crit");
            Dictionary.Add("parse_TotalHealingOverTimeActionsUsedHeader", "Used");
            Dictionary.Add("parse_HOTPSHeader", "HOTPS");
            Dictionary.Add("parse_HealingOverTimeRegHitHeader", "Hit");
            Dictionary.Add("parse_HealingOverTimeRegLowHeader", "Low");
            Dictionary.Add("parse_HealingOverTimeRegHighHeader", "High");
            Dictionary.Add("parse_HealingOverTimeRegAverageHeader", "Avg");
            Dictionary.Add("parse_HealingOverTimeRegModHeader", "Reg Mod");
            Dictionary.Add("parse_HealingOverTimeRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_HealingOverTimeCritHitHeader", "C.Hit");
            Dictionary.Add("parse_HealingOverTimeCritPercentHeader", "Crit %");
            Dictionary.Add("parse_HealingOverTimeCritLowHeader", "C.Low");
            Dictionary.Add("parse_HealingOverTimeCritHighHeader", "C.High");
            Dictionary.Add("parse_HealingOverTimeCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_HealingOverTimeCritModHeader", "Crit Mod");
            Dictionary.Add("parse_HealingOverTimeCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_TotalOverallHealingMitigatedHeader", "Total");
            Dictionary.Add("parse_RegularHealingMitigatedHeader", "Reg");
            Dictionary.Add("parse_CriticalHealingMitigatedHeader", "Crit");
            Dictionary.Add("parse_TotalHealingMitigatedActionsUsedHeader", "Used");
            Dictionary.Add("parse_HMPSHeader", "HMPS");
            Dictionary.Add("parse_HealingMitigatedRegHitHeader", "Hit");
            Dictionary.Add("parse_HealingMitigatedRegLowHeader", "Low");
            Dictionary.Add("parse_HealingMitigatedRegHighHeader", "High");
            Dictionary.Add("parse_HealingMitigatedRegAverageHeader", "Avg");
            Dictionary.Add("parse_HealingMitigatedRegModHeader", "Reg Mod");
            Dictionary.Add("parse_HealingMitigatedRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_HealingMitigatedCritHitHeader", "C.Hit");
            Dictionary.Add("parse_HealingMitigatedCritPercentHeader", "Crit %");
            Dictionary.Add("parse_HealingMitigatedCritLowHeader", "C.Low");
            Dictionary.Add("parse_HealingMitigatedCritHighHeader", "C.High");
            Dictionary.Add("parse_HealingMitigatedCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_HealingMitigatedCritModHeader", "Crit Mod");
            Dictionary.Add("parse_HealingMitigatedCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_TotalOverallDamageTakenHeader", "Total");
            Dictionary.Add("parse_RegularDamageTakenHeader", "Reg");
            Dictionary.Add("parse_CriticalDamageTakenHeader", "Crit");
            Dictionary.Add("parse_TotalDamageTakenActionsUsedHeader", "Used");
            Dictionary.Add("parse_DTPSHeader", "DTPS");
            Dictionary.Add("parse_DamageTakenRegHitHeader", "Hit");
            Dictionary.Add("parse_DamageTakenRegMissHeader", "Miss");
            Dictionary.Add("parse_DamageTakenRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_DamageTakenRegLowHeader", "Low");
            Dictionary.Add("parse_DamageTakenRegHighHeader", "High");
            Dictionary.Add("parse_DamageTakenRegAverageHeader", "Avg");
            Dictionary.Add("parse_DamageTakenRegModHeader", "Reg Mod");
            Dictionary.Add("parse_DamageTakenRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_DamageTakenCritHitHeader", "C.Hit");
            Dictionary.Add("parse_DamageTakenCritPercentHeader", "Crit %");
            Dictionary.Add("parse_DamageTakenCritLowHeader", "C.Low");
            Dictionary.Add("parse_DamageTakenCritHighHeader", "C.High");
            Dictionary.Add("parse_DamageTakenCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_DamageTakenCritModHeader", "Crit Mod");
            Dictionary.Add("parse_DamageTakenCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_DamageTakenCounterHeader", "Counter");
            Dictionary.Add("parse_DamageTakenCounterPercentHeader", "Counter %");
            Dictionary.Add("parse_DamageTakenCounterModHeader", "C. Mod");
            Dictionary.Add("parse_DamageTakenCounterModAverageHeader", "C. Mod Avg");
            Dictionary.Add("parse_DamageTakenBlockHeader", "Block");
            Dictionary.Add("parse_DamageTakenBlockPercentHeader", "Block %");
            Dictionary.Add("parse_DamageTakenBlockModHeader", "B. Mod");
            Dictionary.Add("parse_DamageTakenBlockModAverageHeader", "B. Mod Avg");
            Dictionary.Add("parse_DamageTakenParryHeader", "Parry");
            Dictionary.Add("parse_DamageTakenParryPercentHeader", "Parry %");
            Dictionary.Add("parse_DamageTakenParryModHeader", "P. Mod");
            Dictionary.Add("parse_DamageTakenParryModAverageHeader", "P. Mod Avg");
            Dictionary.Add("parse_DamageTakenResistHeader", "Resist");
            Dictionary.Add("parse_DamageTakenResistPercentHeader", "Resist %");
            Dictionary.Add("parse_DamageTakenResistModHeader", "R. Mod");
            Dictionary.Add("parse_DamageTakenResistModAverageHeader", "R. Mod Avg");
            Dictionary.Add("parse_DamageTakenEvadeHeader", "Evade");
            Dictionary.Add("parse_DamageTakenEvadePercentHeader", "Evade %");
            Dictionary.Add("parse_DamageTakenEvadeModHeader", "E. Mod");
            Dictionary.Add("parse_DamageTakenEvadeModAverageHeader", "E. Mod Avg");
            Dictionary.Add("parse_TotalOverallDamageTakenOverTimeHeader", "Total");
            Dictionary.Add("parse_RegularDamageTakenOverTimeHeader", "Reg");
            Dictionary.Add("parse_CriticalDamageTakenOverTimeHeader", "Crit");
            Dictionary.Add("parse_TotalDamageTakenOverTimeActionsUsedHeader", "Used");
            Dictionary.Add("parse_DTOTPSHeader", "DTOTPS");
            Dictionary.Add("parse_DamageTakenOverTimeRegHitHeader", "Hit");
            Dictionary.Add("parse_DamageTakenOverTimeRegMissHeader", "Miss");
            Dictionary.Add("parse_DamageTakenOverTimeRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_DamageTakenOverTimeRegLowHeader", "Low");
            Dictionary.Add("parse_DamageTakenOverTimeRegHighHeader", "High");
            Dictionary.Add("parse_DamageTakenOverTimeRegAverageHeader", "Avg");
            Dictionary.Add("parse_DamageTakenOverTimeRegModHeader", "Reg Mod");
            Dictionary.Add("parse_DamageTakenOverTimeRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_DamageTakenOverTimeCritHitHeader", "C.Hit");
            Dictionary.Add("parse_DamageTakenOverTimeCritPercentHeader", "Crit %");
            Dictionary.Add("parse_DamageTakenOverTimeCritLowHeader", "C.Low");
            Dictionary.Add("parse_DamageTakenOverTimeCritHighHeader", "C.High");
            Dictionary.Add("parse_DamageTakenOverTimeCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_DamageTakenOverTimeCritModHeader", "Crit Mod");
            Dictionary.Add("parse_DamageTakenOverTimeCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_TotalBuffTimeHeader", "Buff Time");
            Dictionary.Add("parse_TotalBuffHoursHeader", "H");
            Dictionary.Add("parse_TotalBuffMinutesHeader", "M");
            Dictionary.Add("parse_TotalBuffSecondsHeader", "S");
            Dictionary.Add("parse_CombinedTotalOverallDamageHeader", "Total");
            Dictionary.Add("parse_CombinedRegularDamageHeader", "Reg");
            Dictionary.Add("parse_CombinedCriticalDamageHeader", "Crit");
            Dictionary.Add("parse_CombinedTotalDamageActionsUsedHeader", "Used");
            Dictionary.Add("parse_CombinedDPSHeader", "DPS");
            Dictionary.Add("parse_CombinedDamageRegHitHeader", "Hit");
            Dictionary.Add("parse_CombinedDamageRegMissHeader", "Miss");
            Dictionary.Add("parse_CombinedDamageRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_CombinedDamageRegLowHeader", "Low");
            Dictionary.Add("parse_CombinedDamageRegHighHeader", "High");
            Dictionary.Add("parse_CombinedDamageRegAverageHeader", "Avg");
            Dictionary.Add("parse_CombinedDamageRegModHeader", "Reg Mod");
            Dictionary.Add("parse_CombinedDamageRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_CombinedDamageCritHitHeader", "C.Hit");
            Dictionary.Add("parse_CombinedDamageCritPercentHeader", "Crit %");
            Dictionary.Add("parse_CombinedDamageCritLowHeader", "C.Low");
            Dictionary.Add("parse_CombinedDamageCritHighHeader", "C.High");
            Dictionary.Add("parse_CombinedDamageCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_CombinedDamageCritModHeader", "Crit Mod");
            Dictionary.Add("parse_CombinedDamageCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_CombinedDamageCounterHeader", "Counter");
            Dictionary.Add("parse_CombinedDamageCounterPercentHeader", "Counter %");
            Dictionary.Add("parse_CombinedDamageCounterModHeader", "C. Mod");
            Dictionary.Add("parse_CombinedDamageCounterModAverageHeader", "C. Mod Avg");
            Dictionary.Add("parse_CombinedDamageBlockHeader", "Block");
            Dictionary.Add("parse_CombinedDamageBlockPercentHeader", "Block %");
            Dictionary.Add("parse_CombinedDamageBlockModHeader", "B. Mod");
            Dictionary.Add("parse_CombinedDamageBlockModAverageHeader", "B. Mod Avg");
            Dictionary.Add("parse_CombinedDamageParryHeader", "Parry");
            Dictionary.Add("parse_CombinedDamageParryPercentHeader", "Parry %");
            Dictionary.Add("parse_CombinedDamageParryModHeader", "P. Mod");
            Dictionary.Add("parse_CombinedDamageParryModAverageHeader", "P. Mod Avg");
            Dictionary.Add("parse_CombinedDamageResistHeader", "Resist");
            Dictionary.Add("parse_CombinedDamageResistPercentHeader", "Resist %");
            Dictionary.Add("parse_CombinedDamageResistModHeader", "R. Mod");
            Dictionary.Add("parse_CombinedDamageResistModAverageHeader", "R. Mod Avg");
            Dictionary.Add("parse_CombinedDamageEvadeHeader", "Evade");
            Dictionary.Add("parse_CombinedDamageEvadePercentHeader", "Evade %");
            Dictionary.Add("parse_CombinedDamageEvadeModHeader", "E. Mod");
            Dictionary.Add("parse_CombinedDamageEvadeModAverageHeader", "E. Mod Avg");
            Dictionary.Add("parse_CombinedTotalOverallHealingHeader", "Total");
            Dictionary.Add("parse_CombinedRegularHealingHeader", "Reg");
            Dictionary.Add("parse_CombinedCriticalHealingHeader", "Crit");
            Dictionary.Add("parse_CombinedTotalHealingActionsUsedHeader", "Used");
            Dictionary.Add("parse_CombinedHPSHeader", "HOHPS");
            Dictionary.Add("parse_CombinedHealingRegHitHeader", "Hit");
            Dictionary.Add("parse_CombinedHealingRegLowHeader", "Low");
            Dictionary.Add("parse_CombinedHealingRegHighHeader", "High");
            Dictionary.Add("parse_CombinedHealingRegAverageHeader", "Avg");
            Dictionary.Add("parse_CombinedHealingRegModHeader", "Reg Mod");
            Dictionary.Add("parse_CombinedHealingRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_CombinedHealingCritHitHeader", "C.Hit");
            Dictionary.Add("parse_CombinedHealingCritPercentHeader", "Crit %");
            Dictionary.Add("parse_CombinedHealingCritLowHeader", "C.Low");
            Dictionary.Add("parse_CombinedHealingCritHighHeader", "C.High");
            Dictionary.Add("parse_CombinedHealingCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_CombinedHealingCritModHeader", "Crit Mod");
            Dictionary.Add("parse_CombinedHealingCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_CombinedTotalOverallDamageTakenHeader", "Total");
            Dictionary.Add("parse_CombinedRegularDamageTakenHeader", "Reg");
            Dictionary.Add("parse_CombinedCriticalDamageTakenHeader", "Crit");
            Dictionary.Add("parse_CombinedTotalDamageTakenActionsUsedHeader", "Used");
            Dictionary.Add("parse_CombinedDTPSHeader", "DTPS");
            Dictionary.Add("parse_CombinedDamageTakenRegHitHeader", "Hit");
            Dictionary.Add("parse_CombinedDamageTakenRegMissHeader", "Miss");
            Dictionary.Add("parse_CombinedDamageTakenRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_CombinedDamageTakenRegLowHeader", "Low");
            Dictionary.Add("parse_CombinedDamageTakenRegHighHeader", "High");
            Dictionary.Add("parse_CombinedDamageTakenRegAverageHeader", "Avg");
            Dictionary.Add("parse_CombinedDamageTakenRegModHeader", "Reg Mod");
            Dictionary.Add("parse_CombinedDamageTakenRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_CombinedDamageTakenCritHitHeader", "C.Hit");
            Dictionary.Add("parse_CombinedDamageTakenCritPercentHeader", "Crit %");
            Dictionary.Add("parse_CombinedDamageTakenCritLowHeader", "C.Low");
            Dictionary.Add("parse_CombinedDamageTakenCritHighHeader", "C.High");
            Dictionary.Add("parse_CombinedDamageTakenCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_CombinedDamageTakenCritModHeader", "Crit Mod");
            Dictionary.Add("parse_CombinedDamageTakenCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_CombinedDamageTakenCounterHeader", "Counter");
            Dictionary.Add("parse_CombinedDamageTakenCounterPercentHeader", "Counter %");
            Dictionary.Add("parse_CombinedDamageTakenCounterModHeader", "C. Mod");
            Dictionary.Add("parse_CombinedDamageTakenCounterModAverageHeader", "C. Mod Avg");
            Dictionary.Add("parse_CombinedDamageTakenBlockHeader", "Block");
            Dictionary.Add("parse_CombinedDamageTakenBlockPercentHeader", "Block %");
            Dictionary.Add("parse_CombinedDamageTakenBlockModHeader", "B. Mod");
            Dictionary.Add("parse_CombinedDamageTakenBlockModAverageHeader", "B. Mod Avg");
            Dictionary.Add("parse_CombinedDamageTakenParryHeader", "Parry");
            Dictionary.Add("parse_CombinedDamageTakenParryPercentHeader", "Parry %");
            Dictionary.Add("parse_CombinedDamageTakenParryModHeader", "P. Mod");
            Dictionary.Add("parse_CombinedDamageTakenParryModAverageHeader", "P. Mod Avg");
            Dictionary.Add("parse_CombinedDamageTakenResistHeader", "Resist");
            Dictionary.Add("parse_CombinedDamageTakenResistPercentHeader", "Resist %");
            Dictionary.Add("parse_CombinedDamageTakenResistModHeader", "R. Mod");
            Dictionary.Add("parse_CombinedDamageTakenResistModAverageHeader", "R. Mod Avg");
            Dictionary.Add("parse_CombinedDamageTakenEvadeHeader", "Evade");
            Dictionary.Add("parse_CombinedDamageTakenEvadePercentHeader", "Evade %");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModHeader", "E. Mod");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModAverageHeader", "E. Mod Avg");
            Dictionary.Add("parse_PercentOfTotalOverallDamageHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularDamageHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalDamageHeader", "% of Crit");
            Dictionary.Add("parse_PercentOfTotalOverallDamageOverTimeHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularDamageOverTimeHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalDamageOverTimeHeader", "% of Crit");
            Dictionary.Add("parse_PercentOfTotalOverallHealingHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularHealingHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalHealingHeader", "% of Crit");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverHealingHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularHealingOverHealingHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalHealingOverHealingHeader", "% of Crit");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverTimeHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularHealingOverTimeHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalHealingOverTimeHeader", "% of Crit");
            Dictionary.Add("parse_PercentOfTotalOverallHealingMitigatedHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularHealingMitigatedHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalHealingMitigatedHeader", "% of Crit");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularDamageTakenHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenHeader", "% of Crit");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenOverTimeHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularDamageTakenOverTimeHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenOverTimeHeader", "% of Crit");
            Dictionary.Add("parse_TotalOverallDamageLabel", "Gesamtschaden:");
            Dictionary.Add("parse_RegularDamageLabel", "Normaler Schaden:");
            Dictionary.Add("parse_CriticalDamageLabel", "Kritischer Schaden:");
            Dictionary.Add("parse_TotalDamageActionsUsedLabel", "Gesamte benutze Schadensaktionen:");
            Dictionary.Add("parse_DPSLabel", "DPS:");
            Dictionary.Add("parse_DamageRegHitLabel", "Normaler Schaden b Treffer:");
            Dictionary.Add("parse_DamageRegMissLabel", "Normaler Schaden b. Verfehlen:");
            Dictionary.Add("parse_DamageRegAccuracyLabel", "Normaler Schaden Genauigkeit:");
            Dictionary.Add("parse_DamageRegLowLabel", "Niedrigster Normaler Schaden:");
            Dictionary.Add("parse_DamageRegHighLabel", "Höchster Normaler Schaden:");
            Dictionary.Add("parse_DamageRegAverageLabel", "Durchschn. Normaler Schaden:");
            Dictionary.Add("parse_DamageRegModLabel", "Modifizierter Normaler Schaden:");
            Dictionary.Add("parse_DamageRegModAverageLabel", "Modifizierter Normaler Schaden i. Durchschn.:");
            Dictionary.Add("parse_DamageCritHitLabel", "Kritischer Schaden b. Treffer:");
            Dictionary.Add("parse_DamageCritPercentLabel", "Kritischer Schaden b. Verfehlen:");
            Dictionary.Add("parse_DamageCritLowLabel", "Niedrigster Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritHighLabel", "Höchster Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritAverageLabel", "Durchschn. Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritModLabel", "Modifizierter Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritModAverageLabel", "Modifizierter Kritischer Schaden i. Durchschn.:");
            Dictionary.Add("parse_DamageCounterLabel", "Schadenszähler:");
            Dictionary.Add("parse_DamageCounterPercentLabel", "Schadenszähler in %:");
            Dictionary.Add("parse_DamageCounterModLabel", "Modifizierter Schadenszähler:");
            Dictionary.Add("parse_DamageCounterModAverageLabel", "Durchschn. Modifizierter Schadenszähler:");
            Dictionary.Add("parse_DamageBlockLabel", "Geblockter Schaden:");
            Dictionary.Add("parse_DamageBlockPercentLabel", "eblockter Schaden in %:");
            Dictionary.Add("parse_DamageBlockModLabel", "Modifizierter Geblockter Schaden:");
            Dictionary.Add("parse_DamageBlockModAverageLabel", "Durchschn. Modifizierter Geblockter Schaden:");
            Dictionary.Add("parse_DamageParryLabel", "Parierter Schaden:");
            Dictionary.Add("parse_DamageParryPercentLabel", "Parierter Schaden in %:");
            Dictionary.Add("parse_DamageParryModLabel", "Modifizierter Parierter Schaden:");
            Dictionary.Add("parse_DamageParryModAverageLabel", "Durchschn. Modifizierter Parierter Schaden:");
            Dictionary.Add("parse_DamageResistLabel", "Widerstandener Schaden:");
            Dictionary.Add("parse_DamageResistPercentLabel", "Widerst. Schaden in %:");
            Dictionary.Add("parse_DamageResistModLabel", "Modifizierter Widerst. Schaden:");
            Dictionary.Add("parse_DamageResistModAverageLabel", "Durchschn. Modifizierter Widerst. Schaden:");
            Dictionary.Add("parse_DamageEvadeLabel", "Ausgewicherner Schaden:");
            Dictionary.Add("parse_DamageEvadePercentLabel", "Ausgew. Schaden in %:");
            Dictionary.Add("parse_DamageEvadeModLabel", "Mod. Ausgew. Schaden:");
            Dictionary.Add("parse_DamageEvadeModAverageLabel", "Durchschn, Mod. Ausgew. Schaden:");
            Dictionary.Add("parse_TotalOverallDamageOverTimeLabel", "Total Overall Damage OT:");
            Dictionary.Add("parse_RegularDamageOverTimeLabel", "Regular Damage OT:");
            Dictionary.Add("parse_CriticalDamageOverTimeLabel", "Critical Damage OT:");
            Dictionary.Add("parse_TotalDamageOverTimeActionsUsedLabel", "Total Damage OT Actions Used:");
            Dictionary.Add("parse_DOTPSLabel", "DOTPS:");
            Dictionary.Add("parse_DamageOverTimeRegHitLabel", "Damage OT Reg Hit:");
            Dictionary.Add("parse_DamageOverTimeRegMissLabel", "Damage OT Reg Miss:");
            Dictionary.Add("parse_DamageOverTimeRegAccuracyLabel", "Damage OT Reg Accuracy:");
            Dictionary.Add("parse_DamageOverTimeRegLowLabel", "Damage OT Reg Low:");
            Dictionary.Add("parse_DamageOverTimeRegHighLabel", "Damage OT Reg High:");
            Dictionary.Add("parse_DamageOverTimeRegAverageLabel", "Damage OT Reg Average:");
            Dictionary.Add("parse_DamageOverTimeRegModLabel", "Damage OT Reg Mod:");
            Dictionary.Add("parse_DamageOverTimeRegModAverageLabel", "Damage OT Reg Mod Average:");
            Dictionary.Add("parse_DamageOverTimeCritHitLabel", "Damage OT Crit Hit:");
            Dictionary.Add("parse_DamageOverTimeCritPercentLabel", "Damage OT Crit Percent:");
            Dictionary.Add("parse_DamageOverTimeCritLowLabel", "Damage OT Crit Low:");
            Dictionary.Add("parse_DamageOverTimeCritHighLabel", "Damage OT Crit High:");
            Dictionary.Add("parse_DamageOverTimeCritAverageLabel", "Damage OT Crit Average:");
            Dictionary.Add("parse_DamageOverTimeCritModLabel", "Damage OT Crit Mod:");
            Dictionary.Add("parse_DamageOverTimeCritModAverageLabel", "Damage OT Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallHealingLabel", "Komplette Gesamtheilung:");
            Dictionary.Add("parse_RegularHealingLabel", "Normale Heilung:");
            Dictionary.Add("parse_CriticalHealingLabel", "Kritische Heilung:");
            Dictionary.Add("parse_TotalHealingActionsUsedLabel", "Gesamte benutzte Heilaktionen:");
            Dictionary.Add("parse_HPSLabel", "HPS:");
            Dictionary.Add("parse_HealingRegHitLabel", "Norm. Heilung b Treffer:");
            Dictionary.Add("parse_HealingRegLowLabel", "Niedrigste Norm. Heilung:");
            Dictionary.Add("parse_HealingRegHighLabel", "Höchste Norm. Heilung:");
            Dictionary.Add("parse_HealingRegAverageLabel", "Durchschn. Norm. Heilung:");
            Dictionary.Add("parse_HealingRegModLabel", "Mod. Norm. Heilung:");
            Dictionary.Add("parse_HealingRegModAverageLabel", "Durchschn. Mod. Norm. Heilung:");
            Dictionary.Add("parse_HealingCritHitLabel", "Krit. Heilung b. Treffer:");
            Dictionary.Add("parse_HealingCritPercentLabel", "Krit. Heilung in %:");
            Dictionary.Add("parse_HealingCritLowLabel", "Niedrigste Krit. Heilung:");
            Dictionary.Add("parse_HealingCritHighLabel", "Höchste Krit. Heilung:");
            Dictionary.Add("parse_HealingCritAverageLabel", "Durchschn. Krit. Heilung:");
            Dictionary.Add("parse_HealingCritModLabel", "Mod. Krit. Heilung:");
            Dictionary.Add("parse_HealingCritModAverageLabel", "Durchschn. Mod. Krit. Heilung:");
            Dictionary.Add("parse_TotalOverallHealingOverHealingLabel", "Total Overall Healing OH:");
            Dictionary.Add("parse_RegularHealingOverHealingLabel", "Regular Healing OH:");
            Dictionary.Add("parse_CriticalHealingOverHealingLabel", "Critical Healing OH:");
            Dictionary.Add("parse_TotalHealingOverHealingActionsUsedLabel", "Total Healing OH Actions Used:");
            Dictionary.Add("parse_HOHPSLabel", "HOHPS:");
            Dictionary.Add("parse_HealingOverHealingRegHitLabel", "Healing OH Reg Hit:");
            Dictionary.Add("parse_HealingOverHealingRegLowLabel", "Healing OH Reg Low:");
            Dictionary.Add("parse_HealingOverHealingRegHighLabel", "Healing OH Reg High:");
            Dictionary.Add("parse_HealingOverHealingRegAverageLabel", "Healing OH Reg Average:");
            Dictionary.Add("parse_HealingOverHealingRegModLabel", "Healing OH Reg Mod:");
            Dictionary.Add("parse_HealingOverHealingRegModAverageLabel", "Healing OH Reg Mod Average:");
            Dictionary.Add("parse_HealingOverHealingCritHitLabel", "Healing OH Crit Hit:");
            Dictionary.Add("parse_HealingOverHealingCritPercentLabel", "Healing OH Crit Percent:");
            Dictionary.Add("parse_HealingOverHealingCritLowLabel", "Healing OH Crit Low:");
            Dictionary.Add("parse_HealingOverHealingCritHighLabel", "Healing OH Crit High:");
            Dictionary.Add("parse_HealingOverHealingCritAverageLabel", "Healing OH Crit Average:");
            Dictionary.Add("parse_HealingOverHealingCritModLabel", "Healing OH Crit Mod:");
            Dictionary.Add("parse_HealingOverHealingCritModAverageLabel", "Healing OH Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallHealingOverTimeLabel", "Total Overall Healing OT:");
            Dictionary.Add("parse_RegularHealingOverTimeLabel", "Regular Healing OT:");
            Dictionary.Add("parse_CriticalHealingOverTimeLabel", "Critical Healing OT:");
            Dictionary.Add("parse_TotalHealingOverTimeActionsUsedLabel", "Total Healing OT Actions Used:");
            Dictionary.Add("parse_HOTPSLabel", "HOTPS:");
            Dictionary.Add("parse_HealingOverTimeRegHitLabel", "Healing OT Reg Hit:");
            Dictionary.Add("parse_HealingOverTimeRegLowLabel", "Healing OT Reg Low:");
            Dictionary.Add("parse_HealingOverTimeRegHighLabel", "Healing OT Reg High:");
            Dictionary.Add("parse_HealingOverTimeRegAverageLabel", "Healing OT Reg Average:");
            Dictionary.Add("parse_HealingOverTimeRegModLabel", "Healing OT Reg Mod:");
            Dictionary.Add("parse_HealingOverTimeRegModAverageLabel", "Healing OT Reg Mod Average:");
            Dictionary.Add("parse_HealingOverTimeCritHitLabel", "Healing OT Crit Hit:");
            Dictionary.Add("parse_HealingOverTimeCritPercentLabel", "Healing OT Crit Percent:");
            Dictionary.Add("parse_HealingOverTimeCritLowLabel", "Healing OT Crit Low:");
            Dictionary.Add("parse_HealingOverTimeCritHighLabel", "Healing OT Crit High:");
            Dictionary.Add("parse_HealingOverTimeCritAverageLabel", "Healing OT Crit Average:");
            Dictionary.Add("parse_HealingOverTimeCritModLabel", "Healing OT Crit Mod:");
            Dictionary.Add("parse_HealingOverTimeCritModAverageLabel", "Healing OT Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallHealingMitigatedLabel", "Total Overall Healing Mitigated:");
            Dictionary.Add("parse_RegularHealingMitigatedLabel", "Regular Healing Mitigated:");
            Dictionary.Add("parse_CriticalHealingMitigatedLabel", "Critical Healing Mitigated:");
            Dictionary.Add("parse_TotalHealingMitigatedActionsUsedLabel", "Total Healing Mitigated Actions Used:");
            Dictionary.Add("parse_HMPSLabel", "HMPS:");
            Dictionary.Add("parse_HealingMitigatedRegHitLabel", "Healing Mitigated Reg Hit:");
            Dictionary.Add("parse_HealingMitigatedRegLowLabel", "Healing Mitigated Reg Low:");
            Dictionary.Add("parse_HealingMitigatedRegHighLabel", "Healing Mitigated Reg High:");
            Dictionary.Add("parse_HealingMitigatedRegAverageLabel", "Healing Mitigated Reg Average:");
            Dictionary.Add("parse_HealingMitigatedRegModLabel", "Healing Mitigated Reg Mod:");
            Dictionary.Add("parse_HealingMitigatedRegModAverageLabel", "Healing Mitigated Reg Mod Average:");
            Dictionary.Add("parse_HealingMitigatedCritHitLabel", "Healing Mitigated Crit Hit:");
            Dictionary.Add("parse_HealingMitigatedCritPercentLabel", "Healing Mitigated Crit Percent:");
            Dictionary.Add("parse_HealingMitigatedCritLowLabel", "Healing Mitigated Crit Low:");
            Dictionary.Add("parse_HealingMitigatedCritHighLabel", "Healing Mitigated Crit High:");
            Dictionary.Add("parse_HealingMitigatedCritAverageLabel", "Healing Mitigated Crit Average:");
            Dictionary.Add("parse_HealingMitigatedCritModLabel", "Healing Mitigated Crit Mod:");
            Dictionary.Add("parse_HealingMitigatedCritModAverageLabel", "Healing Mitigated Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallDamageTakenLabel", "Gesamter Erlittener Schaden:");
            Dictionary.Add("parse_RegularDamageTakenLabel", "Normaler Erlittener Schaden:");
            Dictionary.Add("parse_CriticalDamageTakenLabel", "Kritischer erlittener Schaden:");
            Dictionary.Add("parse_TotalDamageTakenActionsUsedLabel", "Gesamte benutzte Aktionen bei erlittenem Schaden:");
            Dictionary.Add("parse_DTPSLabel", "DTPS:");
            Dictionary.Add("parse_DamageTakenRegHitLabel", "Erlittener Schaden d. Treffer:");
            Dictionary.Add("parse_DamageTakenRegMissLabel", "Erlittener Schaden d. Verfehlen:");
            Dictionary.Add("parse_DamageTakenRegAccuracyLabel", "Genauigkeit Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegLowLabel", "Niedrigster Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegHighLabel", "Höchster Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegAverageLabel", "Durchschn. Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegModLabel", "Mod. Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegModAverageLabel", "Durchschn. Mod. Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenCritHitLabel", "Erlittener Krit. Schaden d. Treffer:");
            Dictionary.Add("parse_DamageTakenCritPercentLabel", "Erlittener Krit. Schaden d. Verfehlen:");
            Dictionary.Add("parse_DamageTakenCritLowLabel", "Niedrigster Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritHighLabel", "Höchster Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritAverageLabel", "Durchschn- Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritModLabel", "Mod. Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritModAverageLabel", "Durchschn. Mod. Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCounterLabel", "Zähler Erl Schaden:");
            Dictionary.Add("parse_DamageTakenCounterPercentLabel", "Zähler Erl Schaden in %:");
            Dictionary.Add("parse_DamageTakenCounterModLabel", "Zähler Erl Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenCounterModAverageLabel", "Zähler Mod. Erl Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenBlockLabel", "Erl. gebl. Schaden:");
            Dictionary.Add("parse_DamageTakenBlockPercentLabel", "Erl. gebl. Schaden in %:");
            Dictionary.Add("parse_DamageTakenBlockModLabel", "Erl. gebl. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenBlockModAverageLabel", "Erl. gebl. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenParryLabel", "Erl. par. Schaden:");
            Dictionary.Add("parse_DamageTakenParryPercentLabel", "Erl. par. Schaden in %:");
            Dictionary.Add("parse_DamageTakenParryModLabel", "Erl. par. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenParryModAverageLabel", "Erl. par. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenResistLabel", "Erl. widerst. Schaden:");
            Dictionary.Add("parse_DamageTakenResistPercentLabel", "Erl. widerst. Schaden in %:");
            Dictionary.Add("parse_DamageTakenResistModLabel", "Erl. widerst. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenResistModAverageLabel", "Erl. widerst. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenEvadeLabel", "Ausgew. Erl. Schaden:");
            Dictionary.Add("parse_DamageTakenEvadePercentLabel", "Ausgew. Erl. Schaden in %:");
            Dictionary.Add("parse_DamageTakenEvadeModLabel", "Ausgew. Erl. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenEvadeModAverageLabel", "Ausgew. Erl. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_TotalOverallDamageTakenOverTimeLabel", "Total Overall DT OT:");
            Dictionary.Add("parse_RegularDamageTakenOverTimeLabel", "Regular DT OT:");
            Dictionary.Add("parse_CriticalDamageTakenOverTimeLabel", "Critical DT OT:");
            Dictionary.Add("parse_TotalDamageTakenOverTimeActionsUsedLabel", "Total DT OT Actions Used:");
            Dictionary.Add("parse_DTOTPSLabel", "DTOTPS:");
            Dictionary.Add("parse_DamageTakenOverTimeRegHitLabel", "Damage Taken OT Reg Hit:");
            Dictionary.Add("parse_DamageTakenOverTimeRegMissLabel", "Damage Taken OT Reg Miss:");
            Dictionary.Add("parse_DamageTakenOverTimeRegAccuracyLabel", "Damage Taken OT Reg Accuracy:");
            Dictionary.Add("parse_DamageTakenOverTimeRegLowLabel", "Damage Taken OT Reg Low:");
            Dictionary.Add("parse_DamageTakenOverTimeRegHighLabel", "Damage Taken OT Reg High:");
            Dictionary.Add("parse_DamageTakenOverTimeRegAverageLabel", "Damage Taken OT Reg Average:");
            Dictionary.Add("parse_DamageTakenOverTimeRegModLabel", "Damage Taken OT Reg Mod:");
            Dictionary.Add("parse_DamageTakenOverTimeRegModAverageLabel", "Damage Taken OT Reg Mod Average:");
            Dictionary.Add("parse_DamageTakenOverTimeCritHitLabel", "Damage Taken OT Crit Hit:");
            Dictionary.Add("parse_DamageTakenOverTimeCritPercentLabel", "Damage Taken OT Crit Percent:");
            Dictionary.Add("parse_DamageTakenOverTimeCritLowLabel", "Damage Taken OT Crit Low:");
            Dictionary.Add("parse_DamageTakenOverTimeCritHighLabel", "Damage Taken OT Crit High:");
            Dictionary.Add("parse_DamageTakenOverTimeCritAverageLabel", "Damage Taken OT Crit Average:");
            Dictionary.Add("parse_DamageTakenOverTimeCritModLabel", "Damage Taken OT Crit Mod:");
            Dictionary.Add("parse_DamageTakenOverTimeCritModAverageLabel", "Damage Taken OT Crit Mod Average:");
            Dictionary.Add("parse_TotalBuffTimeLabel", "Total Buff Time:");
            Dictionary.Add("parse_TotalBuffHoursLabel", "Total Buff Hours:");
            Dictionary.Add("parse_TotalBuffMinutesLabel", "Total Buff Minutes:");
            Dictionary.Add("parse_TotalBuffSecondsLabel", "Total Buff Seconds:");
            Dictionary.Add("parse_CombinedTotalOverallDamageLabel", "Combined Total Overall Damage:");
            Dictionary.Add("parse_CombinedRegularDamageLabel", "Combined Regular Damage:");
            Dictionary.Add("parse_CombinedCriticalDamageLabel", "Combined Critical Damage:");
            Dictionary.Add("parse_CombinedTotalDamageActionsUsedLabel", "Combined Total Damage Actions Used:");
            Dictionary.Add("parse_CombinedDPSLabel", "Combined DPS:");
            Dictionary.Add("parse_CombinedDamageRegHitLabel", "Combined Damage Reg Hit:");
            Dictionary.Add("parse_CombinedDamageRegMissLabel", "Combined Damage Reg Miss:");
            Dictionary.Add("parse_CombinedDamageRegAccuracyLabel", "Combined Damage Reg Accuracy:");
            Dictionary.Add("parse_CombinedDamageRegLowLabel", "Combined Damage Reg Low:");
            Dictionary.Add("parse_CombinedDamageRegHighLabel", "Combined Damage Reg High:");
            Dictionary.Add("parse_CombinedDamageRegAverageLabel", "Combined Damage Reg Average:");
            Dictionary.Add("parse_CombinedDamageRegModLabel", "Combined Damage Reg Mod:");
            Dictionary.Add("parse_CombinedDamageRegModAverageLabel", "Combined Damage Reg Mod Average:");
            Dictionary.Add("parse_CombinedDamageCritHitLabel", "Combined Damage Crit Hit:");
            Dictionary.Add("parse_CombinedDamageCritPercentLabel", "Combined Damage Crit Percent:");
            Dictionary.Add("parse_CombinedDamageCritLowLabel", "Combined Damage Crit Low:");
            Dictionary.Add("parse_CombinedDamageCritHighLabel", "Combined Damage Crit High:");
            Dictionary.Add("parse_CombinedDamageCritAverageLabel", "Combined Damage Crit Average:");
            Dictionary.Add("parse_CombinedDamageCritModLabel", "Combined Damage Crit Mod:");
            Dictionary.Add("parse_CombinedDamageCritModAverageLabel", "Combined Damage Crit Mod Average:");
            Dictionary.Add("parse_CombinedDamageCounterLabel", "Combined Damage Counter:");
            Dictionary.Add("parse_CombinedDamageCounterPercentLabel", "Combined Damage Counter Percent:");
            Dictionary.Add("parse_CombinedDamageCounterModLabel", "Combined Damage Counter Mod:");
            Dictionary.Add("parse_CombinedDamageCounterModAverageLabel", "Combined Damage Counter Mod Average:");
            Dictionary.Add("parse_CombinedDamageBlockLabel", "Combined Damage Block:");
            Dictionary.Add("parse_CombinedDamageBlockPercentLabel", "Combined Damage Block Percent:");
            Dictionary.Add("parse_CombinedDamageBlockModLabel", "Combined Damage Block Mod:");
            Dictionary.Add("parse_CombinedDamageBlockModAverageLabel", "Combined Damage Block Mod Average:");
            Dictionary.Add("parse_CombinedDamageParryLabel", "Combined Damage Parry:");
            Dictionary.Add("parse_CombinedDamageParryPercentLabel", "Combined Damage Parry Percent:");
            Dictionary.Add("parse_CombinedDamageParryModLabel", "Combined Damage Parry Mod:");
            Dictionary.Add("parse_CombinedDamageParryModAverageLabel", "Combined Damage Parry Mod Average:");
            Dictionary.Add("parse_CombinedDamageResistLabel", "Combined Damage Resist:");
            Dictionary.Add("parse_CombinedDamageResistPercentLabel", "Combined Damage Resist Percent:");
            Dictionary.Add("parse_CombinedDamageResistModLabel", "Combined Damage Resist Mod:");
            Dictionary.Add("parse_CombinedDamageResistModAverageLabel", "Combined Damage Resist Mod Average:");
            Dictionary.Add("parse_CombinedDamageEvadeLabel", "Combined Damage Evade:");
            Dictionary.Add("parse_CombinedDamageEvadePercentLabel", "Combined Damage Evade Percent:");
            Dictionary.Add("parse_CombinedDamageEvadeModLabel", "Combined Damage Evade Mod:");
            Dictionary.Add("parse_CombinedDamageEvadeModAverageLabel", "Combined Damage Evade Mod Average:");
            Dictionary.Add("parse_CombinedTotalOverallHealingLabel", "Combined Total Overall Healing:");
            Dictionary.Add("parse_CombinedRegularHealingLabel", "Combined Regular Healing:");
            Dictionary.Add("parse_CombinedCriticalHealingLabel", "Combined Critical Healing:");
            Dictionary.Add("parse_CombinedTotalHealingActionsUsedLabel", "Combined Total Healing Actions Used:");
            Dictionary.Add("parse_CombinedHPSLabel", "Combined HPS:");
            Dictionary.Add("parse_CombinedHealingRegHitLabel", "Combined Healing Reg Hit:");
            Dictionary.Add("parse_CombinedHealingRegLowLabel", "Combined Healing Reg Low:");
            Dictionary.Add("parse_CombinedHealingRegHighLabel", "Combined Healing Reg High:");
            Dictionary.Add("parse_CombinedHealingRegAverageLabel", "Combined Healing Reg Average:");
            Dictionary.Add("parse_CombinedHealingRegModLabel", "Combined Healing Reg Mod:");
            Dictionary.Add("parse_CombinedHealingRegModAverageLabel", "Combined Healing Reg Mod Average:");
            Dictionary.Add("parse_CombinedHealingCritHitLabel", "Combined Healing Crit Hit:");
            Dictionary.Add("parse_CombinedHealingCritPercentLabel", "Combined Healing Crit Percent:");
            Dictionary.Add("parse_CombinedHealingCritLowLabel", "Combined Healing Crit Low:");
            Dictionary.Add("parse_CombinedHealingCritHighLabel", "Combined Healing Crit High:");
            Dictionary.Add("parse_CombinedHealingCritAverageLabel", "Combined Healing Crit Average:");
            Dictionary.Add("parse_CombinedHealingCritModLabel", "Combined Healing Crit Mod:");
            Dictionary.Add("parse_CombinedHealingCritModAverageLabel", "Combined Healing Crit Mod Average:");
            Dictionary.Add("parse_CombinedTotalOverallDamageTakenLabel", "Combined Total Overall Damage Taken:");
            Dictionary.Add("parse_CombinedRegularDamageTakenLabel", "Combined Regular Damage Taken:");
            Dictionary.Add("parse_CombinedCriticalDamageTakenLabel", "Combined Critical Damage Taken:");
            Dictionary.Add("parse_CombinedTotalDamageTakenActionsUsedLabel", "Combined Total DT Actions Used:");
            Dictionary.Add("parse_CombinedDTPSLabel", "Combined DTPS:");
            Dictionary.Add("parse_CombinedDamageTakenRegHitLabel", "Combined DT Reg Hit:");
            Dictionary.Add("parse_CombinedDamageTakenRegMissLabel", "Combined DT Reg Miss:");
            Dictionary.Add("parse_CombinedDamageTakenRegAccuracyLabel", "Combined DT Reg Accuracy:");
            Dictionary.Add("parse_CombinedDamageTakenRegLowLabel", "Combined DT Reg Low:");
            Dictionary.Add("parse_CombinedDamageTakenRegHighLabel", "Combined DT Reg High:");
            Dictionary.Add("parse_CombinedDamageTakenRegAverageLabel", "Combined DT Reg Average:");
            Dictionary.Add("parse_CombinedDamageTakenRegModLabel", "Combined DT Reg Mod:");
            Dictionary.Add("parse_CombinedDamageTakenRegModAverageLabel", "Combined DT Reg Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenCritHitLabel", "Combined DT Crit Hit:");
            Dictionary.Add("parse_CombinedDamageTakenCritPercentLabel", "Combined DT Crit Percent:");
            Dictionary.Add("parse_CombinedDamageTakenCritLowLabel", "Combined DT Crit Low:");
            Dictionary.Add("parse_CombinedDamageTakenCritHighLabel", "Combined DT Crit High:");
            Dictionary.Add("parse_CombinedDamageTakenCritAverageLabel", "Combined DT Crit Average:");
            Dictionary.Add("parse_CombinedDamageTakenCritModLabel", "Combined DT Crit Mod:");
            Dictionary.Add("parse_CombinedDamageTakenCritModAverageLabel", "Combined DT Crit Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenCounterLabel", "Combined DT Counter:");
            Dictionary.Add("parse_CombinedDamageTakenCounterPercentLabel", "Combined DT Counter Percent:");
            Dictionary.Add("parse_CombinedDamageTakenCounterModLabel", "Combined DT Counter Mod:");
            Dictionary.Add("parse_CombinedDamageTakenCounterModAverageLabel", "Combined DT Counter Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenBlockLabel", "Combined DT Block:");
            Dictionary.Add("parse_CombinedDamageTakenBlockPercentLabel", "Combined DT Block Percent:");
            Dictionary.Add("parse_CombinedDamageTakenBlockModLabel", "Combined DT Block Mod:");
            Dictionary.Add("parse_CombinedDamageTakenBlockModAverageLabel", "Combined DT Block Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenParryLabel", "Combined DT Parry:");
            Dictionary.Add("parse_CombinedDamageTakenParryPercentLabel", "Combined DT Parry Percent:");
            Dictionary.Add("parse_CombinedDamageTakenParryModLabel", "Combined DT Parry Mod:");
            Dictionary.Add("parse_CombinedDamageTakenParryModAverageLabel", "Combined DT Parry Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenResistLabel", "Combined DT Resist:");
            Dictionary.Add("parse_CombinedDamageTakenResistPercentLabel", "Combined DT Resist Percent:");
            Dictionary.Add("parse_CombinedDamageTakenResistModLabel", "Combined DT Resist Mod:");
            Dictionary.Add("parse_CombinedDamageTakenResistModAverageLabel", "Combined DT Resist Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenEvadeLabel", "Combined DT Evade:");
            Dictionary.Add("parse_CombinedDamageTakenEvadePercentLabel", "Combined DT Evade Percent:");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModLabel", "Combined DT Evade Mod:");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModAverageLabel", "Combined DT Evade Mod Average:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageLabel", "Gesamtschaden in %:");
            Dictionary.Add("parse_PercentOfRegularDamageLabel", "Normaler Schaden in %:");
            Dictionary.Add("parse_PercentOfCriticalDamageLabel", "Kritischer Schaden in %:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageOverTimeLabel", "Percent Of Total Overall Damage OT:");
            Dictionary.Add("parse_PercentOfRegularDamageOverTimeLabel", "Percent Of Regular Damage OT:");
            Dictionary.Add("parse_PercentOfCriticalDamageOverTimeLabel", "Percent Of Critical Damage OT:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingLabel", "Kompl. gesamtheilung in %:");
            Dictionary.Add("parse_PercentOfRegularHealingLabel", "Norm. Heilung in %:");
            Dictionary.Add("parse_PercentOfCriticalHealingLabel", "Krit. Heilung in %:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverHealingLabel", "Percent Of Total Overall Healing OH:");
            Dictionary.Add("parse_PercentOfRegularHealingOverHealingLabel", "Percent Of Regular Healing OH:");
            Dictionary.Add("parse_PercentOfCriticalHealingOverHealingLabel", "Percent Of Critical Healing OH:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverTimeLabel", "Percent Of Total Overall Healing OT:");
            Dictionary.Add("parse_PercentOfRegularHealingOverTimeLabel", "Percent Of Regular Healing OT:");
            Dictionary.Add("parse_PercentOfCriticalHealingOverTimeLabel", "Percent Of Critical Healing OT:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingMitigatedLabel", "Percent Of Total Overall Healing Mitigated:");
            Dictionary.Add("parse_PercentOfRegularHealingMitigatedLabel", "Percent Of Regular Healing Mitigated:");
            Dictionary.Add("parse_PercentOfCriticalHealingMitigatedLabel", "Percent Of Critical Healing Mitigated:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenLabel", "Erl. Gesamtschaden in %:");
            Dictionary.Add("parse_PercentOfRegularDamageTakenLabel", "Erl. Normal schaden in %:");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenLabel", "Erl. Krit. Schaden in %:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenOverTimeLabel", "Percent Of Total Overall DT OT:");
            Dictionary.Add("parse_PercentOfRegularDamageTakenOverTimeLabel", "Percent Of Regular DT OT:");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenOverTimeLabel", "Percent Of Critical DT OT:");
            Dictionary.Add("parse_ShowTotalOverallDamageInfoHeader", "Gesamtschadens Info Anzeigen");
            Dictionary.Add("parse_ShowRegularDamageInfoHeader", "Gesamt Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowCriticalDamageInfoHeader", "Gesamt Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowTotalDamageActionsUsedInfoHeader", "Ges. ben. Schadensaktion Info Anzeigen");
            Dictionary.Add("parse_ShowDPSInfoHeader", "DPS Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegHitInfoHeader", "Treffer Schadens info anzeigen");
            Dictionary.Add("parse_ShowDamageRegMissInfoHeader", "Verfehlt Schadens Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegAccuracyInfoHeader", "Genauigkeit Schadens Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegLowInfoHeader", "Niedrigster Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegHighInfoHeader", "Höchster Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegAverageInfoHeader", "Durchschn. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegModInfoHeader", "Mod. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegModAverageInfoHeader", "Mod. Durchschn. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritHitInfoHeader", "Treffer Krit. Schadens info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritPercentInfoHeader", "Krit. Schadens info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageCritLowInfoHeader", "Niedirgster Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritHighInfoHeader", "Höchster Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritAverageInfoHeader", "Durchschn. Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritModInfoHeader", "Mod. Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritModAverageInfoHeader", "Durchschn. Mod. Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCounterInfoHeader", "Schadenszähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageCounterPercentInfoHeader", "Schadenszähler Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageCounterModInfoHeader", "Mod. Schadenszähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageCounterModAverageInfoHeader", "Durchschn. Mod. Schadenszähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageBlockInfoHeader", "Gebl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageBlockPercentInfoHeader", "Gebl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageBlockModInfoHeader", "Mod. Gebl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageBlockModAverageInfoHeader", "Durchschn. Mod. Gebl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageParryInfoHeader", "Parierter Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageParryPercentInfoHeader", "Parierter Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageParryModInfoHeader", "Durchschn. Mod. Parierter Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageParryModAverageInfoHeader", "Mod. Parierter Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageResistInfoHeader", "Widerst. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageResistPercentInfoHeader", "Widerst. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageResistModInfoHeader", "Mod. Widerst. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageResistModAverageInfoHeader", "Durchschn. Mod. Widerst. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageEvadeInfoHeader", "Ausgew. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageEvadePercentInfoHeader", "Ausgew. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageEvadeModInfoHeader", "Mod. Ausgew. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageEvadeModAverageInfoHeader", "Durchschn. Mod Ausgew. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowTotalOverallDamageOverTimeInfoHeader", "Show Total Overall Damage OT Information");
            Dictionary.Add("parse_ShowRegularDamageOverTimeInfoHeader", "Show Regular Damage OT Information");
            Dictionary.Add("parse_ShowCriticalDamageOverTimeInfoHeader", "Show Critical Damage OT Information");
            Dictionary.Add("parse_ShowTotalDamageOverTimeActionsUsedInfoHeader", "Show Total Damage OT Actions Used Information");
            Dictionary.Add("parse_ShowDOTPSInfoHeader", "Show DOTPS Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegHitInfoHeader", "Show Damage OT Reg Hit Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegMissInfoHeader", "Show Damage OT Reg Miss Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegAccuracyInfoHeader", "Show Damage OT Reg Accuracy Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegLowInfoHeader", "Show Damage OT Reg Low Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegHighInfoHeader", "Show Damage OT Reg High Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegAverageInfoHeader", "Show Damage OT Reg Average Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegModInfoHeader", "Show Damage OT Reg Mod Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegModAverageInfoHeader", "Show Damage OT Reg Mod Average Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritHitInfoHeader", "Show Damage OT Crit Hit Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritPercentInfoHeader", "Show Damage OT Crit Percent Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritLowInfoHeader", "Show Damage OT Crit Low Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritHighInfoHeader", "Show Damage OT Crit High Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritAverageInfoHeader", "Show Damage OT Crit Average Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritModInfoHeader", "Show Damage OT Crit Mod Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritModAverageInfoHeader", "Show Damage OT Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallHealingInfoHeader", "Totale Gesamtheilung Info Anzeigen");
            Dictionary.Add("parse_ShowRegularHealingInfoHeader", "Totale Norm. Heilung Info Anzeigen");
            Dictionary.Add("parse_ShowCriticalHealingInfoHeader", "Totale Krit. Heilung Info Anzeigen");
            Dictionary.Add("parse_ShowTotalHealingActionsUsedInfoHeader", "Totale ben. Ges. Heilungs Aktionen Info Anzeigen");
            Dictionary.Add("parse_ShowHPSInfoHeader", "HPS Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegHitInfoHeader", "Normale Heilungs Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegLowInfoHeader", "Niedrigste Norm. Heilungs Info Anzeigen.");
            Dictionary.Add("parse_ShowHealingRegHighInfoHeader", "Höchste. Norm. Heilungs Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegAverageInfoHeader", "Durchschn. Norm. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegModInfoHeader", "Mod. Norm. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegModAverageInfoHeader", "Durchchn. Mod. Norm. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritHitInfoHeader", "Crit. Heilungs Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritPercentInfoHeader", "Crit. Heilungs Info Anzeigen in %");
            Dictionary.Add("parse_ShowHealingCritLowInfoHeader", "Niedrigste Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritHighInfoHeader", "Höchste Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritAverageInfoHeader", "Durschschn. Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritModInfoHeader", "Mod. Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritModAverageInfoHeader", "Durchschn. Mod Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowTotalOverallHealingOverHealingInfoHeader", "Show Total Overall Healing OH Information");
            Dictionary.Add("parse_ShowRegularHealingOverHealingInfoHeader", "Show Regular Healing OH Information");
            Dictionary.Add("parse_ShowCriticalHealingOverHealingInfoHeader", "Show Critical Healing OH Information");
            Dictionary.Add("parse_ShowTotalHealingOverHealingActionsUsedInfoHeader", "Show Total Healing OH Actions Used Information");
            Dictionary.Add("parse_ShowHOHPSInfoHeader", "Show HOHPS Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegHitInfoHeader", "Show Healing OH Reg Hit Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegLowInfoHeader", "Show Healing OH Reg Low Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegHighInfoHeader", "Show Healing OH Reg High Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegAverageInfoHeader", "Show Healing OH Reg Average Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegModInfoHeader", "Show Healing OH Reg Mod Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegModAverageInfoHeader", "Show Healing OH Reg Mod Average Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritHitInfoHeader", "Show Healing OH Crit Hit Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritPercentInfoHeader", "Show Healing OH Crit Percent Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritLowInfoHeader", "Show Healing OH Crit Low Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritHighInfoHeader", "Show Healing OH Crit High Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritAverageInfoHeader", "Show Healing OH Crit Average Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritModInfoHeader", "Show Healing OH Crit Mod Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritModAverageInfoHeader", "Show Healing OH Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallHealingOverTimeInfoHeader", "Show Total Overall Healing OT Information");
            Dictionary.Add("parse_ShowRegularHealingOverTimeInfoHeader", "Show Regular Healing OT Information");
            Dictionary.Add("parse_ShowCriticalHealingOverTimeInfoHeader", "Show Critical Healing OT Information");
            Dictionary.Add("parse_ShowTotalHealingOverTimeActionsUsedInfoHeader", "Show Total Healing OT Actions Used Information");
            Dictionary.Add("parse_ShowHOTPSInfoHeader", "Show HOTPS Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegHitInfoHeader", "Show Healing OT Reg Hit Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegLowInfoHeader", "Show Healing OT Reg Low Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegHighInfoHeader", "Show Healing OT Reg High Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegAverageInfoHeader", "Show Healing OT Reg Average Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegModInfoHeader", "Show Healing OT Reg Mod Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegModAverageInfoHeader", "Show Healing OT Reg Mod Average Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritHitInfoHeader", "Show Healing OT Crit Hit Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritPercentInfoHeader", "Show Healing OT Crit Percent Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritLowInfoHeader", "Show Healing OT Crit Low Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritHighInfoHeader", "Show Healing OT Crit High Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritAverageInfoHeader", "Show Healing OT Crit Average Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritModInfoHeader", "Show Healing OT Crit Mod Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritModAverageInfoHeader", "Show Healing OT Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallHealingMitigatedInfoHeader", "Show Total Overall Healing Mitigated Information");
            Dictionary.Add("parse_ShowRegularHealingMitigatedInfoHeader", "Show Regular Healing Mitigated Information");
            Dictionary.Add("parse_ShowCriticalHealingMitigatedInfoHeader", "Show Critical Healing Mitigated Information");
            Dictionary.Add("parse_ShowTotalHealingMitigatedActionsUsedInfoHeader", "Show Total Healing Mitigated Actions Used Information");
            Dictionary.Add("parse_ShowHMPSInfoHeader", "Show HMPS Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegHitInfoHeader", "Show Healing Mitigated Reg Hit Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegLowInfoHeader", "Show Healing Mitigated Reg Low Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegHighInfoHeader", "Show Healing Mitigated Reg High Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegAverageInfoHeader", "Show Healing Mitigated Reg Average Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegModInfoHeader", "Show Healing Mitigated Reg Mod Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegModAverageInfoHeader", "Show Healing Mitigated Reg Mod Average Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritHitInfoHeader", "Show Healing Mitigated Crit Hit Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritPercentInfoHeader", "Show Healing Mitigated Crit Percent Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritLowInfoHeader", "Show Healing Mitigated Crit Low Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritHighInfoHeader", "Show Healing Mitigated Crit High Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritAverageInfoHeader", "Show Healing Mitigated Crit Average Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritModInfoHeader", "Show Healing Mitigated Crit Mod Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritModAverageInfoHeader", "Show Healing Mitigated Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallDamageTakenInfoHeader", "Totalern Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowRegularDamageTakenInfoHeader", "Norm. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowCriticalDamageTakenInfoHeader", "Krit. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowTotalDamageTakenActionsUsedInfoHeader", "Totaler erl. Schaden Aktionen Info Anzeigen");
            Dictionary.Add("parse_ShowDTPSInfoHeader", "DTPS Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegHitInfoHeader", "Erl. Norm. Schaden. Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegMissInfoHeader", "Verfehlter erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegAccuracyInfoHeader", "Genauigkeit erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegLowInfoHeader", "Niedrigster erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegHighInfoHeader", "Höchster erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegAverageInfoHeader", "Durchschn. erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegModInfoHeader", "Mod erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegModAverageInfoHeader", "Durchschn. Mod. erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritHitInfoHeader", "Erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritPercentInfoHeader", "Erl. Krit. Schaden Info Anzeigen In %");
            Dictionary.Add("parse_ShowDamageTakenCritLowInfoHeader", "Niedrigster erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritHighInfoHeader", "Höchster erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritAverageInfoHeader", "Durchschn. erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritModInfoHeader", "Mod. erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritModAverageInfoHeader", "Durchschn. Mod. erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCounterInfoHeader", "Erl. Schaden Zähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCounterPercentInfoHeader", "Erl. Schaden Zähler Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenCounterModInfoHeader", "Mod. Erl. Schaden Zähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCounterModAverageInfoHeader", "Durchschn.Mod. Mod. Erl. Schaden Zähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenBlockInfoHeader", "Geblockt erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenBlockPercentInfoHeader", "Geblockt erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenBlockModInfoHeader", "Mod. Geblockt erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenBlockModAverageInfoHeader", "Durchschn. Mod. Geblockt erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenParryInfoHeader", "Parierter erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenParryPercentInfoHeader", "Parierter erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenParryModInfoHeader", "Mod. Parierter erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenParryModAverageInfoHeader", "Durchschn. Mod. Parierter erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenResistInfoHeader", "Widerst. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenResistPercentInfoHeader", "Widerst. erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenResistModInfoHeader", "Mod. Widerst. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenResistModAverageInfoHeader", "Durchschn. Mod. Widerst. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenEvadeInfoHeader", "Ausgew. Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenEvadePercentInfoHeader", "Ausgew. Erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenEvadeModInfoHeader", "Mod. Ausgew. Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenEvadeModAverageInfoHeader", "Durchschn. Mod. Ausgew. Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowTotalOverallDamageTakenOverTimeInfoHeader", "Show Total Overall DT OT Information");
            Dictionary.Add("parse_ShowRegularDamageTakenOverTimeInfoHeader", "Show Regular DT OT Information");
            Dictionary.Add("parse_ShowCriticalDamageTakenOverTimeInfoHeader", "Show Critical DT OT Information");
            Dictionary.Add("parse_ShowTotalDamageTakenOverTimeActionsUsedInfoHeader", "Show Total DT OT Actions Used Information");
            Dictionary.Add("parse_ShowDTOTPSInfoHeader", "Show DTOTPS Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegHitInfoHeader", "Show DT OT Reg Hit Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegMissInfoHeader", "Show DT OT Reg Miss Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegAccuracyInfoHeader", "Show DT OT Reg Accuracy Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegLowInfoHeader", "Show DT OT Reg Low Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegHighInfoHeader", "Show DT OT Reg High Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegAverageInfoHeader", "Show DT OT Reg Average Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegModInfoHeader", "Show DT OT Reg Mod Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegModAverageInfoHeader", "Show DT OT Reg Mod Average Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritHitInfoHeader", "Show DT OT Crit Hit Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritPercentInfoHeader", "Show DT OT Crit Percent Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritLowInfoHeader", "Show DT OT Crit Low Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritHighInfoHeader", "Show DT OT Crit High Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritAverageInfoHeader", "Show DT OT Crit Average Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritModInfoHeader", "Show DT OT Crit Mod Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritModAverageInfoHeader", "Show DT OT Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalBuffTimeInfoHeader", "Show Total Buff Time Info");
            Dictionary.Add("parse_ShowTotalBuffHoursInfoHeader", "Show Total Buff Hours Info");
            Dictionary.Add("parse_ShowTotalBuffMinutesInfoHeader", "Show Total Buff Minutes Info");
            Dictionary.Add("parse_ShowTotalBuffSecondsInfoHeader", "Show Total Buff Seconds Info");
            Dictionary.Add("parse_ShowCombinedTotalOverallDamageInfoHeader", "Show Combined Total Overall Damage Info:");
            Dictionary.Add("parse_ShowCombinedRegularDamageInfoHeader", "Show Combined Regular Damage Info:");
            Dictionary.Add("parse_ShowCombinedCriticalDamageInfoHeader", "Show Combined Critical Damage Info:");
            Dictionary.Add("parse_ShowCombinedTotalDamageActionsUsedInfoHeader", "Show Combined Total Damage Actions Used Info:");
            Dictionary.Add("parse_ShowCombinedDPSInfoHeader", "Show Combined DPS Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegHitInfoHeader", "Show Combined Damage Reg Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegMissInfoHeader", "Show Combined Damage Reg Miss Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegAccuracyInfoHeader", "Show Combined Damage Reg Accuracy Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegLowInfoHeader", "Show Combined Damage Reg Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegHighInfoHeader", "Show Combined Damage Reg High Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegAverageInfoHeader", "Show Combined Damage Reg Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegModInfoHeader", "Show Combined Damage Reg Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegModAverageInfoHeader", "Show Combined Damage Reg Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritHitInfoHeader", "Show Combined Damage Crit Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritPercentInfoHeader", "Show Combined Damage Crit Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritLowInfoHeader", "Show Combined Damage Crit Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritHighInfoHeader", "Show Combined Damage Crit High Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritAverageInfoHeader", "Show Combined Damage Crit Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritModInfoHeader", "Show Combined Damage Crit Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritModAverageInfoHeader", "Show Combined Damage Crit Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterInfoHeader", "Show Combined Damage Counter Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterPercentInfoHeader", "Show Combined Damage Counter Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterModInfoHeader", "Show Combined Damage Counter Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterModAverageInfoHeader", "Show Combined Damage Counter Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockInfoHeader", "Show Combined Damage Block Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockPercentInfoHeader", "Show Combined Damage Block Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockModInfoHeader", "Show Combined Damage Block Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockModAverageInfoHeader", "Show Combined Damage Block Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryInfoHeader", "Show Combined Damage Parry Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryPercentInfoHeader", "Show Combined Damage Parry Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryModInfoHeader", "Show Combined Damage Parry Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryModAverageInfoHeader", "Show Combined Damage Parry Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistInfoHeader", "Show Combined Damage Resist Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistPercentInfoHeader", "Show Combined Damage Resist Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistModInfoHeader", "Show Combined Damage Resist Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistModAverageInfoHeader", "Show Combined Damage Resist Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadeInfoHeader", "Show Combined Damage Evade Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadePercentInfoHeader", "Show Combined Damage Evade Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadeModInfoHeader", "Show Combined Damage Evade Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadeModAverageInfoHeader", "Show Combined Damage Evade Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedTotalOverallHealingInfoHeader", "Show Combined Total Overall Healing Info:");
            Dictionary.Add("parse_ShowCombinedRegularHealingInfoHeader", "Show Combined Regular Healing Info:");
            Dictionary.Add("parse_ShowCombinedCriticalHealingInfoHeader", "Show Combined Critical Healing Info:");
            Dictionary.Add("parse_ShowCombinedTotalHealingActionsUsedInfoHeader", "Show Combined Total Healing Actions Used Info:");
            Dictionary.Add("parse_ShowCombinedHPSInfoHeader", "Show Combined HPS Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegHitInfoHeader", "Show Combined Healing Reg Hit Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegLowInfoHeader", "Show Combined Healing Reg Low Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegHighInfoHeader", "Show Combined Healing Reg High Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegAverageInfoHeader", "Show Combined Healing Reg Average Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegModInfoHeader", "Show Combined Healing Reg Mod Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegModAverageInfoHeader", "Show Combined Healing Reg Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritHitInfoHeader", "Show Combined Healing Crit Hit Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritPercentInfoHeader", "Show Combined Healing Crit Percent Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritLowInfoHeader", "Show Combined Healing Crit Low Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritHighInfoHeader", "Show Combined Healing Crit High Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritAverageInfoHeader", "Show Combined Healing Crit Average Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritModInfoHeader", "Show Combined Healing Crit Mod Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritModAverageInfoHeader", "Show Combined Healing Crit Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedTotalOverallDamageTakenInfoHeader", "Show Combined Total Overall Damage Taken Info:");
            Dictionary.Add("parse_ShowCombinedRegularDamageTakenInfoHeader", "Show Combined Regular Damage Taken Info:");
            Dictionary.Add("parse_ShowCombinedCriticalDamageTakenInfoHeader", "Show Combined Critical Damage Taken Info:");
            Dictionary.Add("parse_ShowCombinedTotalDamageTakenActionsUsedInfoHeader", "Show Combined Total DT Actions Used Info:");
            Dictionary.Add("parse_ShowCombinedDTPSInfoHeader", "Show Combined DTPS Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegHitInfoHeader", "Show Combined DT Reg Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegMissInfoHeader", "Show Combined DT Reg Miss Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegAccuracyInfoHeader", "Show Combined DT Reg Accuracy Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegLowInfoHeader", "Show Combined DT Reg Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegHighInfoHeader", "Show Combined DT Reg High Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegAverageInfoHeader", "Show Combined DT Reg Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegModInfoHeader", "Show Combined DT Reg Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegModAverageInfoHeader", "Show Combined DT Reg Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritHitInfoHeader", "Show Combined DT Crit Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritPercentInfoHeader", "Show Combined DT Crit Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritLowInfoHeader", "Show Combined DT Crit Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritHighInfoHeader", "Show Combined DT Crit High Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritAverageInfoHeader", "Show Combined DT Crit Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritModInfoHeader", "Show Combined DT Crit Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritModAverageInfoHeader", "Show Combined DT Crit Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterInfoHeader", "Show Combined DT Counter Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterPercentInfoHeader", "Show Combined DT Counter Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterModInfoHeader", "Show Combined DT Counter Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterModAverageInfoHeader", "Show Combined DT Counter Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockInfoHeader", "Show Combined DT Block Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockPercentInfoHeader", "Show Combined DT Block Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockModInfoHeader", "Show Combined DT Block Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockModAverageInfoHeader", "Show Combined DT Block Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryInfoHeader", "Show Combined DT Parry Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryPercentInfoHeader", "Show Combined DT Parry Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryModInfoHeader", "Show Combined DT Parry Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryModAverageInfoHeader", "Show Combined DT Parry Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistInfoHeader", "Show Combined DT Resist Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistPercentInfoHeader", "Show Combined DT Resist Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistModInfoHeader", "Show Combined DT Resist Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistModAverageInfoHeader", "Show Combined DT Resist Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadeInfoHeader", "Show Combined DT Evade Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadePercentInfoHeader", "Show Combined DT Evade Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadeModInfoHeader", "Show Combined DT Evade Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadeModAverageInfoHeader", "Show Combined DT Evade Mod Average Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageInfoHeader", "Show Percent Of Total Overall Damage Info:");
            Dictionary.Add("parse_ShowPercentOfRegularDamageInfoHeader", "Show Percent Of Regular Damage Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageInfoHeader", "Show Percent Of Critical Damage Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageOverTimeInfoHeader", "Show Percent Of Total Overall Damage OT Info:");
            Dictionary.Add("parse_ShowPercentOfRegularDamageOverTimeInfoHeader", "Show Percent Of Regular Damage OT Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageOverTimeInfoHeader", "Show Percent Of Critical Damage OT Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingInfoHeader", "Show Percent Of Total Overall Healing Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingInfoHeader", "Show Percent Of Regular Healing Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingInfoHeader", "Show Percent Of Critical Healing Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingOverHealingInfoHeader", "Show Percent Of Total Overall Healing OH Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingOverHealingInfoHeader", "Show Percent Of Regular Healing OH Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingOverHealingInfoHeader", "Show Percent Of Critical Healing OH Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingOverTimeInfoHeader", "Show Percent Of Total Overall Healing OT Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingOverTimeInfoHeader", "Show Percent Of Regular Healing OT Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingOverTimeInfoHeader", "Show Percent Of Critical Healing OT Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingMitigatedInfoHeader", "Show Percent Of Total Overall Healing Mitigated Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingMitigatedInfoHeader", "Show Percent Of Regular Healing Mitigated Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingMitigatedInfoHeader", "Show Percent Of Critical Healing Mitigated Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageTakenInfoHeader", "Totaler ges. erl. Schaden info Anzeigen in %");
            Dictionary.Add("parse_ShowPercentOfRegularDamageTakenInfoHeader", "Ges. Erl. Norm. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageTakenInfoHeader", "Ges. Erl. Krit. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageTakenOverTimeInfoHeader", "Show Percent Of Total Overall DT OT Info:");
            Dictionary.Add("parse_ShowPercentOfRegularDamageTakenOverTimeInfoHeader", "Show Percent Of Regular DT OT Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageTakenOverTimeInfoHeader", "Show Percent Of Critical DT OT Info:");
            Dictionary.Add("parse_LoadExistingLogFileButtonText", "Bestehende Protokolldatei Laden");
            Dictionary.Add("parse_BasicGlobalWarningLabel", "Dies ist eine globale tracker und hat als solche Werte im globalen Maßstab. Für körnige Vergleiche pro Spieler oder Monster (wie DPS) klicken Sie auf \"Erweitert\"");
            Dictionary.Add("parse_HistoryToolTip", "History");
            Dictionary.Add("parse_StoreHistoryIntervalHeader", "Store History Interval");
            Dictionary.Add("parse_EnableStoreHistoryResetHeader", "Enabled Store History Auto-Reset");
            Dictionary.Add("parse_StoreHistoryEventHeader", "Store History Event Trigger");
            Dictionary.Add("parse_StoreHistoryEventHelperText", "*If enabled the history and parser will be stored and reset if the selected event type does not happen after the chosen interval.");
            Dictionary.Add("parse_IgnoreLimitBreaksHeader", "Ignore Limit Break Damage");
            Dictionary.Add("parse_AutoLoadLastParseFromHistoryHeader", "Automatically Load The Last Parse From History On Each Reset");
            Dictionary.Add("parse_ResetDamageOnlyOption", "Damage Only");
            Dictionary.Add("parse_ResetAnyOption", "Any");
            Dictionary.Add("parse_ScoreCardHeader", "Score Card(Party)");
            Dictionary.Add("parse_TrackXPSFromParseStartEventHeader", "Track (D|DT|H)PS From Parse Start (ALL)");
            Dictionary.Add("parse_TrackXPSFromParseStartEventHelpText", "*With this enabled all PerSecond tracking will be done globablly from the start of the parse. This means if someone doesn't do anything for a minute their DPS on their second attack will be much lower than if it was tracking from Action StartTime");
            Dictionary.Add("parse_NameHeader", "Name");
            Dictionary.Add("parse_ColumnDisplaySettingsTabHeader", "Spaltenanzeige einstellungen");
            Dictionary.Add("parse_BasicDisplaySettingsTabHeader", "Grundlegendeanzeige einstelluingen");
            Dictionary.Add("parse_ResetStatsMessage", "Willst du wirklich alle aktuellen statistiken zurücksetzen und löschen");
            Dictionary.Add("parse_ResetStatsToolTip", "Stats zurücksetzen");
            Dictionary.Add("parse_AdvancedCheckBoxText", "Erweitert");
            Dictionary.Add("parse_PartyComboBoxItemText", "Party");
            Dictionary.Add("parse_PartyAllComboBoxItemText", "Party (ALL)");
            Dictionary.Add("parse_MonsterComboBoxItemText", "Monster");
            Dictionary.Add("parse_MonsterAllComboBoxItemText", "Monster (ALL)");
            Dictionary.Add("parse_ScoreCardsComboBoxItemText", "Score Cards");
            Dictionary.Add("parse_PartyDamageActionsHeader", "Damage (Actions)");
            Dictionary.Add("parse_PartyDamageMonstersHeader", "Damage (Monsters)");
            Dictionary.Add("parse_PartyHealingActionsHeader", "Healing (Actions)");
            Dictionary.Add("parse_PartyHealingPlayersHeader", "Healing (Players)");
            Dictionary.Add("parse_PartyBuffsHeader", "Buffs");
            Dictionary.Add("parse_PartyDamageTakenActionsHeader", "Damage Taken (Actions)");
            Dictionary.Add("parse_PartyDamageTakenMonstersHeader", "Damage Taken (Monsters)");
            Dictionary.Add("parse_MonsterDamageActionsHeader", "Damage (Actions)");
            Dictionary.Add("parse_MonsterDamagePlayersHeader", "Damage (Players)");
            Dictionary.Add("parse_MonsterDamageTakenActionsHeader", "Damage Taken (Actions)");
            Dictionary.Add("parse_MonsterDamageTakenPlayersHeader", "Damage Taken (Players)");
            Dictionary.Add("parse_TotalsNormalHeader", "Totals (Normal)");
            Dictionary.Add("parse_TotalsActionsHeader", "Totals (Actions)");
            Dictionary.Add("parse_TotalsOverTimeHeader", "Totals (Over Time)");
            Dictionary.Add("parse_TotalsOverHealingHeader", "Totals (Over Healing)");
            Dictionary.Add("parse_TotalsMitigatedHeader", "Totals (Mitigated)");
            Dictionary.Add("parse_TotalsOverallHeader", "Totals (Overall)");
            Dictionary.Add("parse_TotalsPlayersHeader", "Totals (Players)");
            Dictionary.Add("parse_TotalsPlayersByActionHeader", "Totals (Players By Action)");
            Dictionary.Add("parse_RefreshSelectedButtonText", "Refresh Selected");
            Dictionary.Add("parse_ViewSourceLabel", "View Source:");
            Dictionary.Add("parse_ViewTypeLabel", "View Type:");
            Dictionary.Add("parse_ParseableTabHeader", "Parseable");
            Dictionary.Add("parse_YouHeader", "You");
            Dictionary.Add("parse_PartyHeader", "Party");
            Dictionary.Add("parse_AllianceHeader", "Alliance");
            Dictionary.Add("parse_OtherHeader", "Other");
            Dictionary.Add("parse_OverallTotalsDamageHeader", "Overall Totals (Damage)");
            Dictionary.Add("parse_OverallTotalsDamageOverTimeHeader", "Overall Totals (Damage Over Time)");
            Dictionary.Add("parse_OverallTotalsHealingHeader", "Overall Totals (Healing)");
            Dictionary.Add("parse_OverallTotalsHealingOverHealingHeader", "Overall Totals (Healing Over Healing)");
            Dictionary.Add("parse_OverallTotalsHealingOverTimeHeader", "Overall Totals (Healing Over Time)");
            Dictionary.Add("parse_OverallTotalsHealingMitigatedHeader", "Overall Totals (Healing Mitigated)");
            Dictionary.Add("parse_OverallTotalsDamageTakenHeader", "Overall Totals (Damage Taken)");
            Dictionary.Add("parse_OverallTotalsDamageTakenOverTimeHeader", "Overall Totals (Damage Taken Over Time)");
            Dictionary.Add("parse_OverallTotalsBuffsHeader", "Overall Totals (Buffs)");
        }
    }
}
