// FFXIVAPP.Client
// German.Parse.cs
// 
// © 2013 Ryan Wilson

namespace FFXIVAPP.Client.Localization
{
    public static partial class German
    {
        private static void SetParseLocale()
        {
            Dictionary.Add("parse_PLACEHOLDER", "*PH*");
            Dictionary.Add("parse_NameHeader", "Name");
            Dictionary.Add("parse_TotalOverallDamageHeader", "Total");
            Dictionary.Add("parse_RegularDamageHeader", "Reg");
            Dictionary.Add("parse_CriticalDamageHeader", "Crit");
            Dictionary.Add("parse_TotalDamageActionsUsedHeader", "Used");
            Dictionary.Add("parse_DPSHeader", "DPS");
            Dictionary.Add("parse_DamageDOTHeader", "DOT");
            Dictionary.Add("parse_DamageDOTAverageHeader", "DOT Avg");
            Dictionary.Add("parse_DamageRegHitHeader", "Hit");
            Dictionary.Add("parse_DamageRegMissHeader", "Miss");
            Dictionary.Add("parse_DamageRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_DamageRegLowHeader", "Low");
            Dictionary.Add("parse_DamageRegHighHeader", "High");
            Dictionary.Add("parse_DamageRegAverageHeader", "Avg");
            Dictionary.Add("parse_DamageRegModHeader", "Reg Mod");
            Dictionary.Add("parse_DamageRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_DamageCritHitHeader", "C.Hit");
            Dictionary.Add("parse_DamageCritPercentHeader", "Crit %");
            Dictionary.Add("parse_DamageCritLowHeader", "C.Low");
            Dictionary.Add("parse_DamageCritHighHeader", "C.High");
            Dictionary.Add("parse_DamageCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_DamageCritModHeader", "Crit Mod");
            Dictionary.Add("parse_DamageCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_DamageCounterHeader", "Counter");
            Dictionary.Add("parse_DamageCounterPercentHeader", "Counter %");
            Dictionary.Add("parse_DamageCounterModHeader", "C. Mod");
            Dictionary.Add("parse_DamageCounterModAverageHeader", "C. Mod Avg");
            Dictionary.Add("parse_DamageBlockHeader", "Block");
            Dictionary.Add("parse_DamageBlockPercentHeader", "Block %");
            Dictionary.Add("parse_DamageBlockModHeader", "B. Mod");
            Dictionary.Add("parse_DamageBlockModAverageHeader", "B. Mod Avg");
            Dictionary.Add("parse_DamageParryHeader", "Parry");
            Dictionary.Add("parse_DamageParryPercentHeader", "Parry %");
            Dictionary.Add("parse_DamageParryModHeader", "P. Mod");
            Dictionary.Add("parse_DamageParryModAverageHeader", "P. Mod Avg");
            Dictionary.Add("parse_DamageResistHeader", "Resist");
            Dictionary.Add("parse_DamageResistPercentHeader", "Resist %");
            Dictionary.Add("parse_DamageResistModHeader", "R. Mod");
            Dictionary.Add("parse_DamageResistModAverageHeader", "R. Mod Avg");
            Dictionary.Add("parse_DamageEvadeHeader", "Evade");
            Dictionary.Add("parse_DamageEvadePercentHeader", "Evade %");
            Dictionary.Add("parse_DamageEvadeModHeader", "E. Mod");
            Dictionary.Add("parse_DamageEvadeModAverageHeader", "E. Mod Avg");
            Dictionary.Add("parse_PercentOfTotalOverallDamageHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularDamageHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalDamageHeader", "% of Crit");
            Dictionary.Add("parse_TotalOverallHealingHeader", "Total");
            Dictionary.Add("parse_RegularHealingHeader", "Reg");
            Dictionary.Add("parse_CriticalHealingHeader", "Crit");
            Dictionary.Add("parse_TotalHealingActionsUsedHeader", "Used");
            Dictionary.Add("parse_HPSHeader", "HPS");
            Dictionary.Add("parse_HealingRegHitHeader", "Hit");
            Dictionary.Add("parse_HealingRegLowHeader", "Low");
            Dictionary.Add("parse_HealingRegHighHeader", "High");
            Dictionary.Add("parse_HealingRegAverageHeader", "Avg");
            Dictionary.Add("parse_HealingRegModHeader", "Reg Mod");
            Dictionary.Add("parse_HealingRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_HealingCritHitHeader", "C.Hit");
            Dictionary.Add("parse_HealingCritPercentHeader", "Crit %");
            Dictionary.Add("parse_HealingCritLowHeader", "C.Low");
            Dictionary.Add("parse_HealingCritHighHeader", "C.High");
            Dictionary.Add("parse_HealingCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_HealingCritModHeader", "Crit Mod");
            Dictionary.Add("parse_HealingCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_PercentOfTotalOverallHealingHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularHealingHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalHealingHeader", "% of Crit");
            Dictionary.Add("parse_TotalOverallDamageTakenHeader", "Total");
            Dictionary.Add("parse_RegularDamageTakenHeader", "Reg");
            Dictionary.Add("parse_CriticalDamageTakenHeader", "Crit");
            Dictionary.Add("parse_TotalDamageTakenActionsUsedHeader", "Used");
            Dictionary.Add("parse_DTPSHeader", "DTPS");
            Dictionary.Add("parse_DamageTakenDOTHeader", "DOT");
            Dictionary.Add("parse_DamageTakenDOTAverageHeader", "DOT Avg");
            Dictionary.Add("parse_DamageTakenRegHitHeader", "Hit");
            Dictionary.Add("parse_DamageTakenRegMissHeader", "Miss");
            Dictionary.Add("parse_DamageTakenRegAccuracyHeader", "Acc");
            Dictionary.Add("parse_DamageTakenRegLowHeader", "Low");
            Dictionary.Add("parse_DamageTakenRegHighHeader", "High");
            Dictionary.Add("parse_DamageTakenRegAverageHeader", "Avg");
            Dictionary.Add("parse_DamageTakenRegModHeader", "Reg Mod");
            Dictionary.Add("parse_DamageTakenRegModAverageHeader", "Reg Mod Avg");
            Dictionary.Add("parse_DamageTakenCritHitHeader", "C.Hit");
            Dictionary.Add("parse_DamageTakenCritPercentHeader", "Crit %");
            Dictionary.Add("parse_DamageTakenCritLowHeader", "C.Low");
            Dictionary.Add("parse_DamageTakenCritHighHeader", "C.High");
            Dictionary.Add("parse_DamageTakenCritAverageHeader", "C.Avg");
            Dictionary.Add("parse_DamageTakenCritModHeader", "Crit Mod");
            Dictionary.Add("parse_DamageTakenCritModAverageHeader", "Crit Mod Avg");
            Dictionary.Add("parse_DamageTakenCounterHeader", "Counter");
            Dictionary.Add("parse_DamageTakenCounterPercentHeader", "Counter %");
            Dictionary.Add("parse_DamageTakenCounterModHeader", "C. Mod");
            Dictionary.Add("parse_DamageTakenCounterModAverageHeader", "C. Mod Avg");
            Dictionary.Add("parse_DamageTakenBlockHeader", "Block");
            Dictionary.Add("parse_DamageTakenBlockPercentHeader", "Block %");
            Dictionary.Add("parse_DamageTakenBlockModHeader", "B. Mod");
            Dictionary.Add("parse_DamageTakenBlockModAverageHeader", "B. Mod Avg");
            Dictionary.Add("parse_DamageTakenParryHeader", "Parry");
            Dictionary.Add("parse_DamageTakenParryPercentHeader", "Parry %");
            Dictionary.Add("parse_DamageTakenParryModHeader", "P. Mod");
            Dictionary.Add("parse_DamageTakenParryModAverageHeader", "P. Mod Avg");
            Dictionary.Add("parse_DamageTakenResistHeader", "Resist");
            Dictionary.Add("parse_DamageTakenResistPercentHeader", "Resist %");
            Dictionary.Add("parse_DamageTakenResistModHeader", "R. Mod");
            Dictionary.Add("parse_DamageTakenResistModAverageHeader", "R. Mod Avg");
            Dictionary.Add("parse_DamageTakenEvadeHeader", "Evade");
            Dictionary.Add("parse_DamageTakenEvadePercentHeader", "Evade %");
            Dictionary.Add("parse_DamageTakenEvadeModHeader", "E. Mod");
            Dictionary.Add("parse_DamageTakenEvadeModAverageHeader", "E. Mod Avg");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenHeader", "% of Total");
            Dictionary.Add("parse_PercentOfRegularDamageTakenHeader", "% of Reg");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenHeader", "% of Crit");
            Dictionary.Add("parse_BasicButtonText", "Grund");
            Dictionary.Add("parse_AdvancedButtonText", "Erweitert");
            Dictionary.Add("parse_PartyDamageTabHeader", "Gruppenschaden");
            Dictionary.Add("parse_PartyHealingTabHeader", "Gruppenheilung");
            Dictionary.Add("parse_PartyDamageTakenTabHeader", "Erlittener Gruppenschaden");
            Dictionary.Add("parse_MonsterDamageTabHeader", "Monsterschaden");
            Dictionary.Add("parse_MonsterHealingTabHeader", "Monsterheilung");
            Dictionary.Add("parse_MonsterDamageTakenTabHeader", "Erlittener Monsterschaden");
            Dictionary.Add("parse_ResetStatsToolTip", "Stats zurücksetzen");
            Dictionary.Add("parse_ShowActionLogHeader", "Aktionsprotokoll Anzeigen");
            Dictionary.Add("parse_ShowPartyDamageHeader", "Gruppenschaden Anzeigen");
            Dictionary.Add("parse_ShowPartyHealingHeader", "Gruppenheilung Anzeigen");
            Dictionary.Add("parse_ShowPartyDamageTakenHeader", "Erlittener Gruppenschaden Anzeigen");
            Dictionary.Add("parse_ShowMonsterDamageHeader", "Monsterschaden Anzeigen");
            Dictionary.Add("parse_ShowMonsterHealingHeader", "Monsterheilung Anzeigen");
            Dictionary.Add("parse_ShowMonsterDamageTakenHeader", "Erlittener Monsterschaden Anzeigen");
            Dictionary.Add("parse_PlayerDamageByActionText", "Schd. sort. nach Aktion sort. nach sel. Spieler.");
            Dictionary.Add("parse_PlayerDamageToMonstersText", "Schd. an Monster von sel. Spieler");
            Dictionary.Add("parse_PlayerDamageToMonstersByActionText", "Schd. an Monster sort. nach Aktion von sel. Spieler");
            Dictionary.Add("parse_PlayerHealingByActionText", "Heilung sort. nach Aktion von sel. Spieler");
            Dictionary.Add("parse_PlayerHealingToPlayersText", "Heilung an Spielern von sel. Spieler.");
            Dictionary.Add("parse_PlayerHealingToPlayersByActionText", "Heilung an Spielern sort. nach Aktion von sel. Spieler");
            Dictionary.Add("parse_PlayerDamageTakenByActionText", "Erl. Schd. von Monstern, sort. n. Aktion  an sel. Spieler");
            Dictionary.Add("parse_PlayerDamageTakenByMonstersText", "Erl Schd. v. Monstern sort. n sel. Spieler");
            Dictionary.Add("parse_PlayerDamageTakenByMonstersByActionText", "Erl Schd. v. Monstern sort. n. Aktion. n. sel. Spieler.");
            Dictionary.Add("parse_MonsterDamageByActionText", "Schaden nach Aktion von sel Monster");
            Dictionary.Add("parse_MonsterDamageToPlayersText", "Schaden an Spielern von sel. Monster");
            Dictionary.Add("parse_MonsterDamageToPlayersByActionText", "Schd. an Spielern sort. n. Aktion von sel. Monster");
            Dictionary.Add("parse_MonsterHealingByActionText", "Heliung sort. n. Aktion v. sel. Monster");
            Dictionary.Add("parse_MonsterHealingToMonstersText", "Heilung an Monstern von sel. Monster.");
            Dictionary.Add("parse_MonsterHealingToMonstersByActionText", "Heiling an Monstern sort. n. Aktion v. sel. Monster");
            Dictionary.Add("parse_MonsterDamageTakenByActionText", "Erl.Schd. sort. n. Aktion v. sel. Monster");
            Dictionary.Add("parse_MonsterDamageTakenByPlayersText", "Erl Schd v. Spielern sort. n. Aktion an sel. Monster");
            Dictionary.Add("parse_MonsterDamageTakenByPlayersByActionText", "Erl Schd v. Spielern sort. n. Aktion u. sel. Spieler an sel. Monster");
            Dictionary.Add("parse_MonsterDropsByMonsterText", "Beute sort. nach sel. Monster");
            Dictionary.Add("parse_TotalOverallDropsHeader", "Beute");
            Dictionary.Add("parse_TotalKilledHeader", "Getötet");
            Dictionary.Add("parse_AverageHPHeader", "Durchschnittl. TP");
            Dictionary.Add("parse_TotalDropsHeader", "Gesamt");
            Dictionary.Add("parse_DropPercentHeader", "% Beutechance");
            Dictionary.Add("parse_ResetStatsMessage", "Willst du wirklich alle aktuellen statistiken zurücksetzen und löschen");
            Dictionary.Add("parse_ColumnDisplaySettingsTabHeader", "Spaltenanzeige einstellungen");
            Dictionary.Add("parse_BasicDisplaySettingsTabHeader", "Grundlegendeanzeige einstelluingen");
            Dictionary.Add("parse_TotalOverallDamageLabel", "Gesamtschaden:");
            Dictionary.Add("parse_RegularDamageLabel", "Normaler Schaden:");
            Dictionary.Add("parse_CriticalDamageLabel", "Kritischer Schaden:");
            Dictionary.Add("parse_TotalDamageActionsUsedLabel", "Gesamte benutze Schadensaktionen:");
            Dictionary.Add("parse_DPSLabel", "DPS:");
            Dictionary.Add("parse_DamageDOTLabel", "Schaden DOT:");
            Dictionary.Add("parse_DamageDOTAverageLabel", "Durchschn. DOT Schaden:");
            Dictionary.Add("parse_DamageRegHitLabel", "Normaler Schaden b Treffer:");
            Dictionary.Add("parse_DamageRegMissLabel", "Normaler Schaden b. Verfehlen:");
            Dictionary.Add("parse_DamageRegAccuracyLabel", "Normaler Schaden Genauigkeit:");
            Dictionary.Add("parse_DamageRegLowLabel", "Niedrigster Normaler Schaden:");
            Dictionary.Add("parse_DamageRegHighLabel", "Höchster Normaler Schaden:");
            Dictionary.Add("parse_DamageRegAverageLabel", "Durchschn. Normaler Schaden:");
            Dictionary.Add("parse_DamageRegModLabel", "Modifizierter Normaler Schaden:");
            Dictionary.Add("parse_DamageRegModAverageLabel", "Modifizierter Normaler Schaden i. Durchschn.:");
            Dictionary.Add("parse_DamageCritHitLabel", "Kritischer Schaden b. Treffer:");
            Dictionary.Add("parse_DamageCritPercentLabel", "Kritischer Schaden b. Verfehlen:");
            Dictionary.Add("parse_DamageCritLowLabel", "Niedrigster Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritHighLabel", "Höchster Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritAverageLabel", "Durchschn. Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritModLabel", "Modifizierter Kritischer Schaden:");
            Dictionary.Add("parse_DamageCritModAverageLabel", "Modifizierter Kritischer Schaden i. Durchschn.:");
            Dictionary.Add("parse_DamageCounterLabel", "Schadenszähler:");
            Dictionary.Add("parse_DamageCounterPercentLabel", "Schadenszähler in %:");
            Dictionary.Add("parse_DamageCounterModLabel", "Modifizierter Schadenszähler:");
            Dictionary.Add("parse_DamageCounterModAverageLabel", "Durchschn. Modifizierter Schadenszähler:");
            Dictionary.Add("parse_DamageBlockLabel", "Geblockter Schaden:");
            Dictionary.Add("parse_DamageBlockPercentLabel", "eblockter Schaden in %:");
            Dictionary.Add("parse_DamageBlockModLabel", "Modifizierter Geblockter Schaden:");
            Dictionary.Add("parse_DamageBlockModAverageLabel", "Durchschn. Modifizierter Geblockter Schaden:");
            Dictionary.Add("parse_DamageParryLabel", "Parierter Schaden:");
            Dictionary.Add("parse_DamageParryPercentLabel", "Parierter Schaden in %:");
            Dictionary.Add("parse_DamageParryModLabel", "Modifizierter Parierter Schaden:");
            Dictionary.Add("parse_DamageParryModAverageLabel", "Durchschn. Modifizierter Parierter Schaden:");
            Dictionary.Add("parse_DamageResistLabel", "Widerstandener Schaden:");
            Dictionary.Add("parse_DamageResistPercentLabel", "Widerst. Schaden in %:");
            Dictionary.Add("parse_DamageResistModLabel", "Modifizierter Widerst. Schaden:");
            Dictionary.Add("parse_DamageResistModAverageLabel", "Durchschn. Modifizierter Widerst. Schaden:");
            Dictionary.Add("parse_DamageEvadeLabel", "Ausgewicherner Schaden:");
            Dictionary.Add("parse_DamageEvadePercentLabel", "Ausgew. Schaden in %:");
            Dictionary.Add("parse_DamageEvadeModLabel", "Mod. Ausgew. Schaden:");
            Dictionary.Add("parse_DamageEvadeModAverageLabel", "Durchschn, Mod. Ausgew. Schaden:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageLabel", "Gesamtschaden in %:");
            Dictionary.Add("parse_PercentOfRegularDamageLabel", "Normaler Schaden in %:");
            Dictionary.Add("parse_PercentOfCriticalDamageLabel", "Kritischer Schaden in %:");
            Dictionary.Add("parse_TotalOverallHealingLabel", "Komplette Gesamtheilung:");
            Dictionary.Add("parse_RegularHealingLabel", "Normale Heilung:");
            Dictionary.Add("parse_CriticalHealingLabel", "Kritische Heilung:");
            Dictionary.Add("parse_TotalHealingActionsUsedLabel", "Gesamte benutzte Heilaktionen:");
            Dictionary.Add("parse_HPSLabel", "HPS:");
            Dictionary.Add("parse_HealingRegHitLabel", "Norm. Heilung b Treffer:");
            Dictionary.Add("parse_HealingRegLowLabel", "Niedrigste Norm. Heilung:");
            Dictionary.Add("parse_HealingRegHighLabel", "Höchste Norm. Heilung:");
            Dictionary.Add("parse_HealingRegAverageLabel", "Durchschn. Norm. Heilung:");
            Dictionary.Add("parse_HealingRegModLabel", "Mod. Norm. Heilung:");
            Dictionary.Add("parse_HealingRegModAverageLabel", "Durchschn. Mod. Norm. Heilung:");
            Dictionary.Add("parse_HealingCritHitLabel", "Krit. Heilung b. Treffer:");
            Dictionary.Add("parse_HealingCritPercentLabel", "Krit. Heilung in %:");
            Dictionary.Add("parse_HealingCritLowLabel", "Niedrigste Krit. Heilung:");
            Dictionary.Add("parse_HealingCritHighLabel", "Höchste Krit. Heilung:");
            Dictionary.Add("parse_HealingCritAverageLabel", "Durchschn. Krit. Heilung:");
            Dictionary.Add("parse_HealingCritModLabel", "Mod. Krit. Heilung:");
            Dictionary.Add("parse_HealingCritModAverageLabel", "Durchschn. Mod. Krit. Heilung:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingLabel", "Kompl. gesamtheilung in %:");
            Dictionary.Add("parse_PercentOfRegularHealingLabel", "Norm. Heilung in %:");
            Dictionary.Add("parse_PercentOfCriticalHealingLabel", "Krit. Heilung in %:");
            Dictionary.Add("parse_TotalOverallDamageTakenLabel", "Gesamter Erlittener Schaden:");
            Dictionary.Add("parse_RegularDamageTakenLabel", "Normaler Erlittener Schaden:");
            Dictionary.Add("parse_CriticalDamageTakenLabel", "Kritischer erlittener Schaden:");
            Dictionary.Add("parse_TotalDamageTakenActionsUsedLabel", "Gesamte benutzte Aktionen bei erlittenem Schaden:");
            Dictionary.Add("parse_DTPSLabel", "DTPS:");
            Dictionary.Add("parse_DamageTakenDOTLabel", "Erlitterer DOT Schaden:");
            Dictionary.Add("parse_DamageTakenDOTAverageLabel", "Durchschn. Erlitterer DOT Schaden:");
            Dictionary.Add("parse_DamageTakenRegHitLabel", "Erlittener Schaden d. Treffer:");
            Dictionary.Add("parse_DamageTakenRegMissLabel", "Erlittener Schaden d. Verfehlen:");
            Dictionary.Add("parse_DamageTakenRegAccuracyLabel", "Genauigkeit Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegLowLabel", "Niedrigster Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegHighLabel", "Höchster Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegAverageLabel", "Durchschn. Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegModLabel", "Mod. Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenRegModAverageLabel", "Durchschn. Mod. Erlittener Norm. Schaden:");
            Dictionary.Add("parse_DamageTakenCritHitLabel", "Erlittener Krit. Schaden d. Treffer:");
            Dictionary.Add("parse_DamageTakenCritPercentLabel", "Erlittener Krit. Schaden d. Verfehlen:");
            Dictionary.Add("parse_DamageTakenCritLowLabel", "Niedrigster Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritHighLabel", "Höchster Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritAverageLabel", "Durchschn- Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritModLabel", "Mod. Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCritModAverageLabel", "Durchschn. Mod. Erlittener Krit. Schaden:");
            Dictionary.Add("parse_DamageTakenCounterLabel", "Zähler Erl Schaden:");
            Dictionary.Add("parse_DamageTakenCounterPercentLabel", "Zähler Erl Schaden in %:");
            Dictionary.Add("parse_DamageTakenCounterModLabel", "Zähler Erl Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenCounterModAverageLabel", "Zähler Mod. Erl Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenBlockLabel", "Erl. gebl. Schaden:");
            Dictionary.Add("parse_DamageTakenBlockPercentLabel", "Erl. gebl. Schaden in %:");
            Dictionary.Add("parse_DamageTakenBlockModLabel", "Erl. gebl. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenBlockModAverageLabel", "Erl. gebl. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenParryLabel", "Erl. par. Schaden:");
            Dictionary.Add("parse_DamageTakenParryPercentLabel", "Erl. par. Schaden in %:");
            Dictionary.Add("parse_DamageTakenParryModLabel", "Erl. par. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenParryModAverageLabel", "Erl. par. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenResistLabel", "Erl. widerst. Schaden:");
            Dictionary.Add("parse_DamageTakenResistPercentLabel", "Erl. widerst. Schaden in %:");
            Dictionary.Add("parse_DamageTakenResistModLabel", "Erl. widerst. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenResistModAverageLabel", "Erl. widerst. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_DamageTakenEvadeLabel", "Ausgew. Erl. Schaden:");
            Dictionary.Add("parse_DamageTakenEvadePercentLabel", "Ausgew. Erl. Schaden in %:");
            Dictionary.Add("parse_DamageTakenEvadeModLabel", "Ausgew. Erl. Mod. Schaden:");
            Dictionary.Add("parse_DamageTakenEvadeModAverageLabel", "Ausgew. Erl. Mod. Schaden Durchschn.:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenLabel", "Erl. Gesamtschaden in %:");
            Dictionary.Add("parse_PercentOfRegularDamageTakenLabel", "Erl. Normal schaden in %:");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenLabel", "Erl. Krit. Schaden in %:");
            Dictionary.Add("parse_ShowTotalOverallDamageInfoHeader", "Gesamtschadens Info Anzeigen");
            Dictionary.Add("parse_ShowRegularDamageInfoHeader", "Gesamt Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowCriticalDamageInfoHeader", "Gesamt Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowTotalDamageActionsUsedInfoHeader", "Ges. ben. Schadensaktion Info Anzeigen");
            Dictionary.Add("parse_ShowDPSInfoHeader", "DPS Info Anzeigen");
            Dictionary.Add("parse_ShowDamageDOTInfoHeader", "DOT Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageDOTAverageInfoHeader", "Durchschn. DOT Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegHitInfoHeader", "Treffer Schadens info anzeigen");
            Dictionary.Add("parse_ShowDamageRegMissInfoHeader", "Verfehlt Schadens Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegAccuracyInfoHeader", "Genauigkeit Schadens Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegLowInfoHeader", "Niedrigster Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegHighInfoHeader", "Höchster Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegAverageInfoHeader", "Durchschn. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegModInfoHeader", "Mod. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageRegModAverageInfoHeader", "Mod. Durchschn. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritHitInfoHeader", "Treffer Krit. Schadens info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritPercentInfoHeader", "Krit. Schadens info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageCritLowInfoHeader", "Niedirgster Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritHighInfoHeader", "Höchster Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritAverageInfoHeader", "Durchschn. Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritModInfoHeader", "Mod. Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCritModAverageInfoHeader", "Durchschn. Mod. Krit. Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageCounterInfoHeader", "Schadenszähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageCounterPercentInfoHeader", "Schadenszähler Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageCounterModInfoHeader", "Mod. Schadenszähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageCounterModAverageInfoHeader", "Durchschn. Mod. Schadenszähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageBlockInfoHeader", "Gebl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageBlockPercentInfoHeader", "Gebl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageBlockModInfoHeader", "Mod. Gebl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageBlockModAverageInfoHeader", "Durchschn. Mod. Gebl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageParryInfoHeader", "Parierter Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageParryPercentInfoHeader", "Parierter Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageParryModInfoHeader", "Durchschn. Mod. Parierter Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageParryModAverageInfoHeader", "Mod. Parierter Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageResistInfoHeader", "Widerst. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageResistPercentInfoHeader", "Widerst. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageResistModInfoHeader", "Mod. Widerst. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageResistModAverageInfoHeader", "Durchschn. Mod. Widerst. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageEvadeInfoHeader", "Ausgew. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageEvadePercentInfoHeader", "Ausgew. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageEvadeModInfoHeader", "Mod. Ausgew. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageEvadeModAverageInfoHeader", "Durchschn. Mod Ausgew. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageInfoHeader", "Totaler Gesamtschaden Info in %");
            Dictionary.Add("parse_ShowPercentOfRegularDamageInfoHeader", "Totaler Norm. Schaden Info in %");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageInfoHeader", "Totaler Krit. Schaden Info in %");
            Dictionary.Add("parse_ShowTotalOverallHealingInfoHeader", "Totale Gesamtheilung Info Anzeigen");
            Dictionary.Add("parse_ShowRegularHealingInfoHeader", "Totale Norm. Heilung Info Anzeigen");
            Dictionary.Add("parse_ShowCriticalHealingInfoHeader", "Totale Krit. Heilung Info Anzeigen");
            Dictionary.Add("parse_ShowTotalHealingActionsUsedInfoHeader", "Totale ben. Ges. Heilungs Aktionen Info Anzeigen");
            Dictionary.Add("parse_ShowHPSInfoHeader", "HPS Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegHitInfoHeader", "Normale Heilungs Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegLowInfoHeader", "Niedrigste Norm. Heilungs Info Anzeigen.");
            Dictionary.Add("parse_ShowHealingRegHighInfoHeader", "Höchste. Norm. Heilungs Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegAverageInfoHeader", "Durchschn. Norm. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegModInfoHeader", "Mod. Norm. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingRegModAverageInfoHeader", "Durchchn. Mod. Norm. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritHitInfoHeader", "Crit. Heilungs Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritPercentInfoHeader", "Crit. Heilungs Info Anzeigen in %");
            Dictionary.Add("parse_ShowHealingCritLowInfoHeader", "Niedrigste Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritHighInfoHeader", "Höchste Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritAverageInfoHeader", "Durschschn. Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritModInfoHeader", "Mod. Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowHealingCritModAverageInfoHeader", "Durchschn. Mod Krit. Heilungs Info Anzeigen");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingInfoHeader", "Totale Ges. Heilung in % Anzeigen");
            Dictionary.Add("parse_ShowPercentOfRegularHealingInfoHeader", "Totale Ges. Norm. Heilung in % Anzeigen");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingInfoHeader", "Totale Ges. Krit. Heilung in % Anzeigen");
            Dictionary.Add("parse_ShowTotalOverallDamageTakenInfoHeader", "Totalern Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowRegularDamageTakenInfoHeader", "Norm. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowCriticalDamageTakenInfoHeader", "Krit. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowTotalDamageTakenActionsUsedInfoHeader", "Totaler erl. Schaden Aktionen Info Anzeigen");
            Dictionary.Add("parse_ShowDTPSInfoHeader", "DTPS Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenDOTInfoHeader", "Erl. DOT Schaden info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenDOTAverageInfoHeader", "Durchsch. Erl. DOT Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegHitInfoHeader", "Erl. Norm. Schaden. Treffer Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegMissInfoHeader", "Verfehlter erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegAccuracyInfoHeader", "Genauigkeit erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegLowInfoHeader", "Niedrigster erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegHighInfoHeader", "Höchster erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegAverageInfoHeader", "Durchschn. erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegModInfoHeader", "Mod erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenRegModAverageInfoHeader", "Durchschn. Mod. erl. Norm. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritHitInfoHeader", "Erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritPercentInfoHeader", "Erl. Krit. Schaden Info Anzeigen In %");
            Dictionary.Add("parse_ShowDamageTakenCritLowInfoHeader", "Niedrigster erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritHighInfoHeader", "Höchster erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritAverageInfoHeader", "Durchschn. erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritModInfoHeader", "Mod. erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCritModAverageInfoHeader", "Durchschn. Mod. erl. Krit. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCounterInfoHeader", "Erl. Schaden Zähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCounterPercentInfoHeader", "Erl. Schaden Zähler Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenCounterModInfoHeader", "Mod. Erl. Schaden Zähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenCounterModAverageInfoHeader", "Durchschn.Mod. Mod. Erl. Schaden Zähler Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenBlockInfoHeader", "Geblockt erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenBlockPercentInfoHeader", "Geblockt erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenBlockModInfoHeader", "Mod. Geblockt erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenBlockModAverageInfoHeader", "Durchschn. Mod. Geblockt erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenParryInfoHeader", "Parierter erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenParryPercentInfoHeader", "Parierter erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenParryModInfoHeader", "Mod. Parierter erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenParryModAverageInfoHeader", "Durchschn. Mod. Parierter erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenResistInfoHeader", "Widerst. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenResistPercentInfoHeader", "Widerst. erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenResistModInfoHeader", "Mod. Widerst. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenResistModAverageInfoHeader", "Durchschn. Mod. Widerst. erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenEvadeInfoHeader", "Ausgew. Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenEvadePercentInfoHeader", "Ausgew. Erl. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowDamageTakenEvadeModInfoHeader", "Mod. Ausgew. Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowDamageTakenEvadeModAverageInfoHeader", "Durchschn. Mod. Ausgew. Erl. Schaden Info Anzeigen");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageTakenInfoHeader", "Totaler ges. erl. Schaden info Anzeigen in %");
            Dictionary.Add("parse_ShowPercentOfRegularDamageTakenInfoHeader", "Ges. Erl. Norm. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageTakenInfoHeader", "Ges. Erl. Krit. Schaden Info Anzeigen in %");
            Dictionary.Add("parse_LoadExistingLogFileButtonText", "Bestehende Protokolldatei Laden");
            Dictionary.Add("parse_BasicGlobalWarningLabel", "Dies ist eine globale tracker und hat als solche Werte im globalen Maßstab. Für körnige Vergleiche pro Spieler oder Monster (wie DPS) klicken Sie auf \"Erweitert\"");
            Dictionary.Add("parse_HistoryToolTip", "History");
            Dictionary.Add("parse_StoreHistoryIntervalHeader", "Store History Interval");
            Dictionary.Add("parse_EnableStoreHistoryResetHeader", "Enabled Store History Auto-Reset");
            Dictionary.Add("parse_StoreHistoryEventHeader", "Store History Event Trigger");
            Dictionary.Add("parse_StoreHistoryEventHelperText", "*If enabled the history and parser will be stored and reset if the selected event type does not happen after the chosen interval.");
            Dictionary.Add("parse_IgnoreLimitBreaksHeader", "Ignore Limit Break Damage");
            Dictionary.Add("parse_SelectItemText", "Select Item:");
            Dictionary.Add("parse_AutoLoadLastParseFromHistoryHeader", "Automatically Load The Last Parse From History On Each Reset");
            Dictionary.Add("parse_ResetDamageOnlyOption", "Damage Only");
            Dictionary.Add("parse_ResetAnyOption", "Any");
            Dictionary.Add("parse_ScoreCardHeader", "Score Card (Party)");
            Dictionary.Add("parse_ShowTotalOverallOverHealingInfoHeader", "Show Total Overall Over Healing Information");
            Dictionary.Add("parse_ShowTotalOverallMitigatedHealingInfoHeader", "Show Total Overall Mitigated Healing Information");
            Dictionary.Add("parse_ShowTotalOverallHealingOverTimeOverHealingInfoHeader", "Show Total Healing Over Time Over Healing Information");
            Dictionary.Add("parse_TotalOverallOverHealingLabel", "Total Overall Over Healing:");
            Dictionary.Add("parse_TotalOverallMitigatedHealingLabel", "Total Overall Mitigated Healing:");
            Dictionary.Add("parse_TotalOverallHealingOverTimeOverHealingLabel", "Total Overall Healing Over Time Over Healing:");
        }
    }
}
