// FFXIVAPP.Client
// Japanese.Parse.cs
// 
// © 2013 Ryan Wilson

namespace FFXIVAPP.Client.Localization
{
    public static partial class Japanese
    {
        private static void SetParseLocale()
        {
            Dictionary.Add("parse_PLACEHOLDER", "*PH*");
            Dictionary.Add("parse_TotalOverallDamageHeader", "合計");
            Dictionary.Add("parse_RegularDamageHeader", "通常");
            Dictionary.Add("parse_CriticalDamageHeader", "クリ");
            Dictionary.Add("parse_TotalDamageActionsUsedHeader", "回数");
            Dictionary.Add("parse_DPSHeader", "DPS");
            Dictionary.Add("parse_DamageRegHitHeader", "命中");
            Dictionary.Add("parse_DamageRegMissHeader", "ミス");
            Dictionary.Add("parse_DamageRegAccuracyHeader", "命中率");
            Dictionary.Add("parse_DamageRegLowHeader", "最小");
            Dictionary.Add("parse_DamageRegHighHeader", "最大");
            Dictionary.Add("parse_DamageRegAverageHeader", "平均");
            Dictionary.Add("parse_DamageRegModHeader", "修正通常");
            Dictionary.Add("parse_DamageRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_DamageCritHitHeader", "クリ回数");
            Dictionary.Add("parse_DamageCritPercentHeader", "クリ率");
            Dictionary.Add("parse_DamageCritLowHeader", "クリ率");
            Dictionary.Add("parse_DamageCritHighHeader", "最大クリ");
            Dictionary.Add("parse_DamageCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_DamageCritModHeader", "修正クリ");
            Dictionary.Add("parse_DamageCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_DamageCounterHeader", "カウンター");
            Dictionary.Add("parse_DamageCounterPercentHeader", "カウンター率");
            Dictionary.Add("parse_DamageCounterModHeader", "修正カウンター");
            Dictionary.Add("parse_DamageCounterModAverageHeader", "平均修正カウンター");
            Dictionary.Add("parse_DamageBlockHeader", "ブロック");
            Dictionary.Add("parse_DamageBlockPercentHeader", "ブロック率");
            Dictionary.Add("parse_DamageBlockModHeader", "修正ブロック");
            Dictionary.Add("parse_DamageBlockModAverageHeader", "平均修正ブロック");
            Dictionary.Add("parse_DamageParryHeader", "受け流し");
            Dictionary.Add("parse_DamageParryPercentHeader", "受け流し率");
            Dictionary.Add("parse_DamageParryModHeader", "修正受け流し");
            Dictionary.Add("parse_DamageParryModAverageHeader", "平均修正受け流し");
            Dictionary.Add("parse_DamageResistHeader", "レジスト");
            Dictionary.Add("parse_DamageResistPercentHeader", "レジスト率");
            Dictionary.Add("parse_DamageResistModHeader", "修正レジスト");
            Dictionary.Add("parse_DamageResistModAverageHeader", "平均修正レジスト");
            Dictionary.Add("parse_DamageEvadeHeader", "回避");
            Dictionary.Add("parse_DamageEvadePercentHeader", "回避率");
            Dictionary.Add("parse_DamageEvadeModHeader", "修正回避");
            Dictionary.Add("parse_DamageEvadeModAverageHeader", "平均修正回避");
            Dictionary.Add("parse_TotalOverallDamageOverTimeHeader", "合計");
            Dictionary.Add("parse_RegularDamageOverTimeHeader", "通常");
            Dictionary.Add("parse_CriticalDamageOverTimeHeader", "クリ");
            Dictionary.Add("parse_TotalDamageOverTimeActionsUsedHeader", "回数");
            Dictionary.Add("parse_DOTPSHeader", "DOTPS");
            Dictionary.Add("parse_DamageOverTimeRegHitHeader", "命中");
            Dictionary.Add("parse_DamageOverTimeRegMissHeader", "ミス");
            Dictionary.Add("parse_DamageOverTimeRegAccuracyHeader", "命中率");
            Dictionary.Add("parse_DamageOverTimeRegLowHeader", "最小");
            Dictionary.Add("parse_DamageOverTimeRegHighHeader", "最大");
            Dictionary.Add("parse_DamageOverTimeRegAverageHeader", "平均");
            Dictionary.Add("parse_DamageOverTimeRegModHeader", "修正通常");
            Dictionary.Add("parse_DamageOverTimeRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_DamageOverTimeCritHitHeader", "クリ回数");
            Dictionary.Add("parse_DamageOverTimeCritPercentHeader", "クリ率");
            Dictionary.Add("parse_DamageOverTimeCritLowHeader", "最小クリ");
            Dictionary.Add("parse_DamageOverTimeCritHighHeader", "最大クリ");
            Dictionary.Add("parse_DamageOverTimeCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_DamageOverTimeCritModHeader", "修正クリ");
            Dictionary.Add("parse_DamageOverTimeCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_TotalOverallHealingHeader", "合計");
            Dictionary.Add("parse_RegularHealingHeader", "通常");
            Dictionary.Add("parse_CriticalHealingHeader", "クリ");
            Dictionary.Add("parse_TotalHealingActionsUsedHeader", "回数");
            Dictionary.Add("parse_HPSHeader", "HPS");
            Dictionary.Add("parse_HealingRegHitHeader", "命中");
            Dictionary.Add("parse_HealingRegLowHeader", "最小");
            Dictionary.Add("parse_HealingRegHighHeader", "最大");
            Dictionary.Add("parse_HealingRegAverageHeader", "平均");
            Dictionary.Add("parse_HealingRegModHeader", "修正通常");
            Dictionary.Add("parse_HealingRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_HealingCritHitHeader", "クリ回数");
            Dictionary.Add("parse_HealingCritPercentHeader", "クリ率");
            Dictionary.Add("parse_HealingCritLowHeader", "最小クリ");
            Dictionary.Add("parse_HealingCritHighHeader", "最大クリ");
            Dictionary.Add("parse_HealingCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_HealingCritModHeader", "修正クリ");
            Dictionary.Add("parse_HealingCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_TotalOverallHealingOverHealingHeader", "合計");
            Dictionary.Add("parse_RegularHealingOverHealingHeader", "通常");
            Dictionary.Add("parse_CriticalHealingOverHealingHeader", "クリ");
            Dictionary.Add("parse_TotalHealingOverHealingActionsUsedHeader", "回数");
            Dictionary.Add("parse_HOHPSHeader", "HOHPS");
            Dictionary.Add("parse_HealingOverHealingRegHitHeader", "命中");
            Dictionary.Add("parse_HealingOverHealingRegLowHeader", "最小");
            Dictionary.Add("parse_HealingOverHealingRegHighHeader", "最大");
            Dictionary.Add("parse_HealingOverHealingRegAverageHeader", "平均");
            Dictionary.Add("parse_HealingOverHealingRegModHeader", "修正通常");
            Dictionary.Add("parse_HealingOverHealingRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_HealingOverHealingCritHitHeader", "クリ回数");
            Dictionary.Add("parse_HealingOverHealingCritPercentHeader", "クリ率");
            Dictionary.Add("parse_HealingOverHealingCritLowHeader", "最小クリ");
            Dictionary.Add("parse_HealingOverHealingCritHighHeader", "最大クリ");
            Dictionary.Add("parse_HealingOverHealingCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_HealingOverHealingCritModHeader", "修正クリ");
            Dictionary.Add("parse_HealingOverHealingCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_TotalOverallHealingOverTimeHeader", "合計");
            Dictionary.Add("parse_RegularHealingOverTimeHeader", "通常");
            Dictionary.Add("parse_CriticalHealingOverTimeHeader", "クリ");
            Dictionary.Add("parse_TotalHealingOverTimeActionsUsedHeader", "回数");
            Dictionary.Add("parse_HOTPSHeader", "HOTPS");
            Dictionary.Add("parse_HealingOverTimeRegHitHeader", "命中");
            Dictionary.Add("parse_HealingOverTimeRegLowHeader", "最小");
            Dictionary.Add("parse_HealingOverTimeRegHighHeader", "最大");
            Dictionary.Add("parse_HealingOverTimeRegAverageHeader", "平均");
            Dictionary.Add("parse_HealingOverTimeRegModHeader", "修正通常");
            Dictionary.Add("parse_HealingOverTimeRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_HealingOverTimeCritHitHeader", "クリ回数");
            Dictionary.Add("parse_HealingOverTimeCritPercentHeader", "クリ率");
            Dictionary.Add("parse_HealingOverTimeCritLowHeader", "最小クリ");
            Dictionary.Add("parse_HealingOverTimeCritHighHeader", "最大クリ");
            Dictionary.Add("parse_HealingOverTimeCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_HealingOverTimeCritModHeader", "修正クリ");
            Dictionary.Add("parse_HealingOverTimeCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_TotalOverallHealingMitigatedHeader", "合計");
            Dictionary.Add("parse_RegularHealingMitigatedHeader", "通常");
            Dictionary.Add("parse_CriticalHealingMitigatedHeader", "クリ");
            Dictionary.Add("parse_TotalHealingMitigatedActionsUsedHeader", "回数");
            Dictionary.Add("parse_HMPSHeader", "HMPS");
            Dictionary.Add("parse_HealingMitigatedRegHitHeader", "命中");
            Dictionary.Add("parse_HealingMitigatedRegLowHeader", "最小");
            Dictionary.Add("parse_HealingMitigatedRegHighHeader", "最大");
            Dictionary.Add("parse_HealingMitigatedRegAverageHeader", "平均");
            Dictionary.Add("parse_HealingMitigatedRegModHeader", "修正通常");
            Dictionary.Add("parse_HealingMitigatedRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_HealingMitigatedCritHitHeader", "クリ率");
            Dictionary.Add("parse_HealingMitigatedCritPercentHeader", "クリ率");
            Dictionary.Add("parse_HealingMitigatedCritLowHeader", "最小クリ");
            Dictionary.Add("parse_HealingMitigatedCritHighHeader", "最大クリ");
            Dictionary.Add("parse_HealingMitigatedCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_HealingMitigatedCritModHeader", "修正クリ");
            Dictionary.Add("parse_HealingMitigatedCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_TotalOverallDamageTakenHeader", "合計");
            Dictionary.Add("parse_RegularDamageTakenHeader", "通常");
            Dictionary.Add("parse_CriticalDamageTakenHeader", "クリ");
            Dictionary.Add("parse_TotalDamageTakenActionsUsedHeader", "回数");
            Dictionary.Add("parse_DTPSHeader", "DTPS");
            Dictionary.Add("parse_DamageTakenRegHitHeader", "命中");
            Dictionary.Add("parse_DamageTakenRegMissHeader", "ミス");
            Dictionary.Add("parse_DamageTakenRegAccuracyHeader", "命中率");
            Dictionary.Add("parse_DamageTakenRegLowHeader", "最小");
            Dictionary.Add("parse_DamageTakenRegHighHeader", "最大");
            Dictionary.Add("parse_DamageTakenRegAverageHeader", "平均");
            Dictionary.Add("parse_DamageTakenRegModHeader", "修正通常");
            Dictionary.Add("parse_DamageTakenRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_DamageTakenCritHitHeader", "クリ回数");
            Dictionary.Add("parse_DamageTakenCritPercentHeader", "クリ率");
            Dictionary.Add("parse_DamageTakenCritLowHeader", "最小クリ");
            Dictionary.Add("parse_DamageTakenCritHighHeader", "最大クリ");
            Dictionary.Add("parse_DamageTakenCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_DamageTakenCritModHeader", "修正クリ");
            Dictionary.Add("parse_DamageTakenCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_DamageTakenCounterHeader", "コンタクト");
            Dictionary.Add("parse_DamageTakenCounterPercentHeader", "コンタクト率");
            Dictionary.Add("parse_DamageTakenCounterModHeader", "修正カウンター");
            Dictionary.Add("parse_DamageTakenCounterModAverageHeader", "平均修正カウンター");
            Dictionary.Add("parse_DamageTakenBlockHeader", "ブロック");
            Dictionary.Add("parse_DamageTakenBlockPercentHeader", "ブロック率");
            Dictionary.Add("parse_DamageTakenBlockModHeader", "修正ブロック");
            Dictionary.Add("parse_DamageTakenBlockModAverageHeader", "平均修正ブロック");
            Dictionary.Add("parse_DamageTakenParryHeader", "受け流し");
            Dictionary.Add("parse_DamageTakenParryPercentHeader", "受け流し率");
            Dictionary.Add("parse_DamageTakenParryModHeader", "修正受け流し");
            Dictionary.Add("parse_DamageTakenParryModAverageHeader", "平均修正受け流し");
            Dictionary.Add("parse_DamageTakenResistHeader", "レジスト");
            Dictionary.Add("parse_DamageTakenResistPercentHeader", "レジスト率");
            Dictionary.Add("parse_DamageTakenResistModHeader", "修正レジスト");
            Dictionary.Add("parse_DamageTakenResistModAverageHeader", "平均修正レジスト");
            Dictionary.Add("parse_DamageTakenEvadeHeader", "回避");
            Dictionary.Add("parse_DamageTakenEvadePercentHeader", "回避率");
            Dictionary.Add("parse_DamageTakenEvadeModHeader", "修正回避");
            Dictionary.Add("parse_DamageTakenEvadeModAverageHeader", "平均回避修正");
            Dictionary.Add("parse_TotalOverallDamageTakenOverTimeHeader", "合計");
            Dictionary.Add("parse_RegularDamageTakenOverTimeHeader", "通常");
            Dictionary.Add("parse_CriticalDamageTakenOverTimeHeader", "クリ");
            Dictionary.Add("parse_TotalDamageTakenOverTimeActionsUsedHeader", "回数");
            Dictionary.Add("parse_DTOTPSHeader", "DTOTPS");
            Dictionary.Add("parse_DamageTakenOverTimeRegHitHeader", "命中");
            Dictionary.Add("parse_DamageTakenOverTimeRegMissHeader", "ミス");
            Dictionary.Add("parse_DamageTakenOverTimeRegAccuracyHeader", "命中率");
            Dictionary.Add("parse_DamageTakenOverTimeRegLowHeader", "最小");
            Dictionary.Add("parse_DamageTakenOverTimeRegHighHeader", "最大");
            Dictionary.Add("parse_DamageTakenOverTimeRegAverageHeader", "平均");
            Dictionary.Add("parse_DamageTakenOverTimeRegModHeader", "修正通常");
            Dictionary.Add("parse_DamageTakenOverTimeRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_DamageTakenOverTimeCritHitHeader", "クリ回数");
            Dictionary.Add("parse_DamageTakenOverTimeCritPercentHeader", "クリ率");
            Dictionary.Add("parse_DamageTakenOverTimeCritLowHeader", "最小クリ");
            Dictionary.Add("parse_DamageTakenOverTimeCritHighHeader", "最大クリ");
            Dictionary.Add("parse_DamageTakenOverTimeCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_DamageTakenOverTimeCritModHeader", "修正クリ");
            Dictionary.Add("parse_DamageTakenOverTimeCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_TotalBuffTimeHeader", "Buff Time");
            Dictionary.Add("parse_TotalBuffHoursHeader", "H");
            Dictionary.Add("parse_TotalBuffMinutesHeader", "M");
            Dictionary.Add("parse_TotalBuffSecondsHeader", "S");
            Dictionary.Add("parse_CombinedTotalOverallDamageHeader", "合計");
            Dictionary.Add("parse_CombinedRegularDamageHeader", "通常");
            Dictionary.Add("parse_CombinedCriticalDamageHeader", "クリ");
            Dictionary.Add("parse_CombinedTotalDamageActionsUsedHeader", "回数");
            Dictionary.Add("parse_CombinedDPSHeader", "DPS");
            Dictionary.Add("parse_CombinedDamageRegHitHeader", "命中");
            Dictionary.Add("parse_CombinedDamageRegMissHeader", "ミス");
            Dictionary.Add("parse_CombinedDamageRegAccuracyHeader", "命中率");
            Dictionary.Add("parse_CombinedDamageRegLowHeader", "最小");
            Dictionary.Add("parse_CombinedDamageRegHighHeader", "最大");
            Dictionary.Add("parse_CombinedDamageRegAverageHeader", "平均");
            Dictionary.Add("parse_CombinedDamageRegModHeader", "修正通常");
            Dictionary.Add("parse_CombinedDamageRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_CombinedDamageCritHitHeader", "クリ回数");
            Dictionary.Add("parse_CombinedDamageCritPercentHeader", "クリ率");
            Dictionary.Add("parse_CombinedDamageCritLowHeader", "最小クリ");
            Dictionary.Add("parse_CombinedDamageCritHighHeader", "最大クリ");
            Dictionary.Add("parse_CombinedDamageCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_CombinedDamageCritModHeader", "修正クリ");
            Dictionary.Add("parse_CombinedDamageCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_CombinedDamageCounterHeader", "カウンター");
            Dictionary.Add("parse_CombinedDamageCounterPercentHeader", "カウンター率");
            Dictionary.Add("parse_CombinedDamageCounterModHeader", "修正カウンター");
            Dictionary.Add("parse_CombinedDamageCounterModAverageHeader", "平均修正カウンター");
            Dictionary.Add("parse_CombinedDamageBlockHeader", "ブロック");
            Dictionary.Add("parse_CombinedDamageBlockPercentHeader", "ブロック率");
            Dictionary.Add("parse_CombinedDamageBlockModHeader", "修正ブロック");
            Dictionary.Add("parse_CombinedDamageBlockModAverageHeader", "平均修正ブロック");
            Dictionary.Add("parse_CombinedDamageParryHeader", "受け流し");
            Dictionary.Add("parse_CombinedDamageParryPercentHeader", "受け流し率");
            Dictionary.Add("parse_CombinedDamageParryModHeader", "修正受け流し");
            Dictionary.Add("parse_CombinedDamageParryModAverageHeader", "平均修正受け流し");
            Dictionary.Add("parse_CombinedDamageResistHeader", "レジスト");
            Dictionary.Add("parse_CombinedDamageResistPercentHeader", "レジスト率");
            Dictionary.Add("parse_CombinedDamageResistModHeader", "修正レジスト");
            Dictionary.Add("parse_CombinedDamageResistModAverageHeader", "平均修正レジスト");
            Dictionary.Add("parse_CombinedDamageEvadeHeader", "回避");
            Dictionary.Add("parse_CombinedDamageEvadePercentHeader", "回避率");
            Dictionary.Add("parse_CombinedDamageEvadeModHeader", "修正回避");
            Dictionary.Add("parse_CombinedDamageEvadeModAverageHeader", "平均修正回避");
            Dictionary.Add("parse_CombinedTotalOverallHealingHeader", "合計");
            Dictionary.Add("parse_CombinedRegularHealingHeader", "通常");
            Dictionary.Add("parse_CombinedCriticalHealingHeader", "クリ");
            Dictionary.Add("parse_CombinedTotalHealingActionsUsedHeader", "回数");
            Dictionary.Add("parse_CombinedHPSHeader", "HOHPS");
            Dictionary.Add("parse_CombinedHealingRegHitHeader", "命中");
            Dictionary.Add("parse_CombinedHealingRegLowHeader", "最小");
            Dictionary.Add("parse_CombinedHealingRegHighHeader", "最大");
            Dictionary.Add("parse_CombinedHealingRegAverageHeader", "平均");
            Dictionary.Add("parse_CombinedHealingRegModHeader", "修正通常");
            Dictionary.Add("parse_CombinedHealingRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_CombinedHealingCritHitHeader", "クリ回数");
            Dictionary.Add("parse_CombinedHealingCritPercentHeader", "クリ率");
            Dictionary.Add("parse_CombinedHealingCritLowHeader", "最小クリ");
            Dictionary.Add("parse_CombinedHealingCritHighHeader", "最大クリ");
            Dictionary.Add("parse_CombinedHealingCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_CombinedHealingCritModHeader", "修正クリ");
            Dictionary.Add("parse_CombinedHealingCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_CombinedTotalOverallDamageTakenHeader", "合計");
            Dictionary.Add("parse_CombinedRegularDamageTakenHeader", "通常");
            Dictionary.Add("parse_CombinedCriticalDamageTakenHeader", "クリ");
            Dictionary.Add("parse_CombinedTotalDamageTakenActionsUsedHeader", "回数");
            Dictionary.Add("parse_CombinedDTPSHeader", "DTPS");
            Dictionary.Add("parse_CombinedDamageTakenRegHitHeader", "命中");
            Dictionary.Add("parse_CombinedDamageTakenRegMissHeader", "ミス");
            Dictionary.Add("parse_CombinedDamageTakenRegAccuracyHeader", "命中率");
            Dictionary.Add("parse_CombinedDamageTakenRegLowHeader", "最小");
            Dictionary.Add("parse_CombinedDamageTakenRegHighHeader", "最大");
            Dictionary.Add("parse_CombinedDamageTakenRegAverageHeader", "平均");
            Dictionary.Add("parse_CombinedDamageTakenRegModHeader", "修正通常");
            Dictionary.Add("parse_CombinedDamageTakenRegModAverageHeader", "平均修正通常");
            Dictionary.Add("parse_CombinedDamageTakenCritHitHeader", "クリ回数");
            Dictionary.Add("parse_CombinedDamageTakenCritPercentHeader", "クリ率");
            Dictionary.Add("parse_CombinedDamageTakenCritLowHeader", "最小クリ");
            Dictionary.Add("parse_CombinedDamageTakenCritHighHeader", "最大クリ");
            Dictionary.Add("parse_CombinedDamageTakenCritAverageHeader", "平均クリ");
            Dictionary.Add("parse_CombinedDamageTakenCritModHeader", "修正クリ");
            Dictionary.Add("parse_CombinedDamageTakenCritModAverageHeader", "平均修正クリ");
            Dictionary.Add("parse_CombinedDamageTakenCounterHeader", "コンタクト");
            Dictionary.Add("parse_CombinedDamageTakenCounterPercentHeader", "コンタクト率");
            Dictionary.Add("parse_CombinedDamageTakenCounterModHeader", "修正カウンター");
            Dictionary.Add("parse_CombinedDamageTakenCounterModAverageHeader", "平均修正カウンター");
            Dictionary.Add("parse_CombinedDamageTakenBlockHeader", "ブロック");
            Dictionary.Add("parse_CombinedDamageTakenBlockPercentHeader", "ブロック率");
            Dictionary.Add("parse_CombinedDamageTakenBlockModHeader", "修正ブロック");
            Dictionary.Add("parse_CombinedDamageTakenBlockModAverageHeader", "平均修正ブロック");
            Dictionary.Add("parse_CombinedDamageTakenParryHeader", "受け流し");
            Dictionary.Add("parse_CombinedDamageTakenParryPercentHeader", "受け流し率");
            Dictionary.Add("parse_CombinedDamageTakenParryModHeader", "修正受け流し");
            Dictionary.Add("parse_CombinedDamageTakenParryModAverageHeader", "平均修正受け流し");
            Dictionary.Add("parse_CombinedDamageTakenResistHeader", "レジスト");
            Dictionary.Add("parse_CombinedDamageTakenResistPercentHeader", "レジスト率");
            Dictionary.Add("parse_CombinedDamageTakenResistModHeader", "修正レジスト");
            Dictionary.Add("parse_CombinedDamageTakenResistModAverageHeader", "平均修正レジスト");
            Dictionary.Add("parse_CombinedDamageTakenEvadeHeader", "回避");
            Dictionary.Add("parse_CombinedDamageTakenEvadePercentHeader", "回避率");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModHeader", "修正回避");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModAverageHeader", "平均回避修正");
            Dictionary.Add("parse_PercentOfTotalOverallDamageHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularDamageHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalDamageHeader", "クリ与ダメ率");
            Dictionary.Add("parse_PercentOfTotalOverallDamageOverTimeHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularDamageOverTimeHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalDamageOverTimeHeader", "クリ与ダメ率");
            Dictionary.Add("parse_PercentOfTotalOverallHealingHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularHealingHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalHealingHeader", "クリ与ダメ率");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverHealingHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularHealingOverHealingHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalHealingOverHealingHeader", "クリ与ダメ率");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverTimeHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularHealingOverTimeHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalHealingOverTimeHeader", "クリ与ダメ率");
            Dictionary.Add("parse_PercentOfTotalOverallHealingMitigatedHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularHealingMitigatedHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalHealingMitigatedHeader", "クリ与ダメ率");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularDamageTakenHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenHeader", "クリ与ダメ率");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenOverTimeHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfRegularDamageTakenOverTimeHeader", "与ダメ率");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenOverTimeHeader", "クリ与ダメ率");
            Dictionary.Add("parse_TotalOverallDamageLabel", "ダメージ全体:");
            Dictionary.Add("parse_RegularDamageLabel", "通常ダメージ:");
            Dictionary.Add("parse_CriticalDamageLabel", "クリティカルダメージ:");
            Dictionary.Add("parse_TotalDamageActionsUsedLabel", "実行された全ダメージ行動:");
            Dictionary.Add("parse_DPSLabel", "DPS:");
            Dictionary.Add("parse_DamageRegHitLabel", "ヒットした通常ダメージ:");
            Dictionary.Add("parse_DamageRegMissLabel", "ミスした通常ダメージ:");
            Dictionary.Add("parse_DamageRegAccuracyLabel", "通常ダメージ命中率:");
            Dictionary.Add("parse_DamageRegLowLabel", "通常ダメージ最少:");
            Dictionary.Add("parse_DamageRegHighLabel", "通常ダメージ最大:");
            Dictionary.Add("parse_DamageRegAverageLabel", "通常ダメージ平均:");
            Dictionary.Add("parse_DamageRegModLabel", "修正通常ダメージ:");
            Dictionary.Add("parse_DamageRegModAverageLabel", "平均修正通常ダメージ:");
            Dictionary.Add("parse_DamageCritHitLabel", "クリティカルダメージヒット数:");
            Dictionary.Add("parse_DamageCritPercentLabel", "クリティカルダメージ率:");
            Dictionary.Add("parse_DamageCritLowLabel", "最少クリティカルダメージ:");
            Dictionary.Add("parse_DamageCritHighLabel", "最大クリティカルダメージ:");
            Dictionary.Add("parse_DamageCritAverageLabel", "クリティカルダメージ平均:");
            Dictionary.Add("parse_DamageCritModLabel", "修正クリティカルダメージ:");
            Dictionary.Add("parse_DamageCritModAverageLabel", "平均修正クリティカルダメージ:");
            Dictionary.Add("parse_DamageCounterLabel", "カウンターダメージ:");
            Dictionary.Add("parse_DamageCounterPercentLabel", "カウンターダメージ率:");
            Dictionary.Add("parse_DamageCounterModLabel", "修正カウンターダメージ:");
            Dictionary.Add("parse_DamageCounterModAverageLabel", "平均修正カウンターダメージ:");
            Dictionary.Add("parse_DamageBlockLabel", "ダメージブロック:");
            Dictionary.Add("parse_DamageBlockPercentLabel", "ダメージブロック率:");
            Dictionary.Add("parse_DamageBlockModLabel", "修正ダメージブロック:");
            Dictionary.Add("parse_DamageBlockModAverageLabel", "平均修正ダメージブロック:");
            Dictionary.Add("parse_DamageParryLabel", "受け流し数:");
            Dictionary.Add("parse_DamageParryPercentLabel", "受け流し率:");
            Dictionary.Add("parse_DamageParryModLabel", "修正受け流し:");
            Dictionary.Add("parse_DamageParryModAverageLabel", "平均修正受け流し:");
            Dictionary.Add("parse_DamageResistLabel", "レジスト:");
            Dictionary.Add("parse_DamageResistPercentLabel", "レジスト率:");
            Dictionary.Add("parse_DamageResistModLabel", "修正レジスト:");
            Dictionary.Add("parse_DamageResistModAverageLabel", "平均修正レジスト:");
            Dictionary.Add("parse_DamageEvadeLabel", "回避:");
            Dictionary.Add("parse_DamageEvadePercentLabel", "回避率:");
            Dictionary.Add("parse_DamageEvadeModLabel", "修正回避:");
            Dictionary.Add("parse_DamageEvadeModAverageLabel", "平均修正回避:");
            Dictionary.Add("parse_TotalOverallDamageOverTimeLabel", "Total Overall Damage OT:");
            Dictionary.Add("parse_RegularDamageOverTimeLabel", "Regular Damage OT:");
            Dictionary.Add("parse_CriticalDamageOverTimeLabel", "Critical Damage OT:");
            Dictionary.Add("parse_TotalDamageOverTimeActionsUsedLabel", "Total Damage OT Actions Used:");
            Dictionary.Add("parse_DOTPSLabel", "DOTPS:");
            Dictionary.Add("parse_DamageOverTimeRegHitLabel", "Damage OT Reg Hit:");
            Dictionary.Add("parse_DamageOverTimeRegMissLabel", "Damage OT Reg Miss:");
            Dictionary.Add("parse_DamageOverTimeRegAccuracyLabel", "Damage OT Reg Accuracy:");
            Dictionary.Add("parse_DamageOverTimeRegLowLabel", "Damage OT Reg Low:");
            Dictionary.Add("parse_DamageOverTimeRegHighLabel", "Damage OT Reg High:");
            Dictionary.Add("parse_DamageOverTimeRegAverageLabel", "Damage OT Reg Average:");
            Dictionary.Add("parse_DamageOverTimeRegModLabel", "Damage OT Reg Mod:");
            Dictionary.Add("parse_DamageOverTimeRegModAverageLabel", "Damage OT Reg Mod Average:");
            Dictionary.Add("parse_DamageOverTimeCritHitLabel", "Damage OT Crit Hit:");
            Dictionary.Add("parse_DamageOverTimeCritPercentLabel", "Damage OT Crit Percent:");
            Dictionary.Add("parse_DamageOverTimeCritLowLabel", "Damage OT Crit Low:");
            Dictionary.Add("parse_DamageOverTimeCritHighLabel", "Damage OT Crit High:");
            Dictionary.Add("parse_DamageOverTimeCritAverageLabel", "Damage OT Crit Average:");
            Dictionary.Add("parse_DamageOverTimeCritModLabel", "Damage OT Crit Mod:");
            Dictionary.Add("parse_DamageOverTimeCritModAverageLabel", "Damage OT Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallHealingLabel", "全回復率:");
            Dictionary.Add("parse_RegularHealingLabel", "通常回復数:");
            Dictionary.Add("parse_CriticalHealingLabel", "クリティカル回復数:");
            Dictionary.Add("parse_TotalHealingActionsUsedLabel", "回復行動数:");
            Dictionary.Add("parse_HPSLabel", "HPS:");
            Dictionary.Add("parse_HealingRegHitLabel", "通常回復数:");
            Dictionary.Add("parse_HealingRegLowLabel", "最少通常回復:");
            Dictionary.Add("parse_HealingRegHighLabel", "最大通常回復:");
            Dictionary.Add("parse_HealingRegAverageLabel", "平均通常回復:");
            Dictionary.Add("parse_HealingRegModLabel", "修正通常回復:");
            Dictionary.Add("parse_HealingRegModAverageLabel", "平均修正通常回復:");
            Dictionary.Add("parse_HealingCritHitLabel", "クリティカル回復:");
            Dictionary.Add("parse_HealingCritPercentLabel", "クリティカル回復率:");
            Dictionary.Add("parse_HealingCritLowLabel", "最少クリティカル回復:");
            Dictionary.Add("parse_HealingCritHighLabel", "最大クリティカル回復:");
            Dictionary.Add("parse_HealingCritAverageLabel", "平均クリティカル回復:");
            Dictionary.Add("parse_HealingCritModLabel", "修正クリティカル回復:");
            Dictionary.Add("parse_HealingCritModAverageLabel", "平均修正クリティカル回復:");
            Dictionary.Add("parse_TotalOverallHealingOverHealingLabel", "Total Overall Healing OH:");
            Dictionary.Add("parse_RegularHealingOverHealingLabel", "Regular Healing OH:");
            Dictionary.Add("parse_CriticalHealingOverHealingLabel", "Critical Healing OH:");
            Dictionary.Add("parse_TotalHealingOverHealingActionsUsedLabel", "Total Healing OH Actions Used:");
            Dictionary.Add("parse_HOHPSLabel", "HOHPS:");
            Dictionary.Add("parse_HealingOverHealingRegHitLabel", "Healing OH Reg Hit:");
            Dictionary.Add("parse_HealingOverHealingRegLowLabel", "Healing OH Reg Low:");
            Dictionary.Add("parse_HealingOverHealingRegHighLabel", "Healing OH Reg High:");
            Dictionary.Add("parse_HealingOverHealingRegAverageLabel", "Healing OH Reg Average:");
            Dictionary.Add("parse_HealingOverHealingRegModLabel", "Healing OH Reg Mod:");
            Dictionary.Add("parse_HealingOverHealingRegModAverageLabel", "Healing OH Reg Mod Average:");
            Dictionary.Add("parse_HealingOverHealingCritHitLabel", "Healing OH Crit Hit:");
            Dictionary.Add("parse_HealingOverHealingCritPercentLabel", "Healing OH Crit Percent:");
            Dictionary.Add("parse_HealingOverHealingCritLowLabel", "Healing OH Crit Low:");
            Dictionary.Add("parse_HealingOverHealingCritHighLabel", "Healing OH Crit High:");
            Dictionary.Add("parse_HealingOverHealingCritAverageLabel", "Healing OH Crit Average:");
            Dictionary.Add("parse_HealingOverHealingCritModLabel", "Healing OH Crit Mod:");
            Dictionary.Add("parse_HealingOverHealingCritModAverageLabel", "Healing OH Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallHealingOverTimeLabel", "Total Overall Healing OT:");
            Dictionary.Add("parse_RegularHealingOverTimeLabel", "Regular Healing OT:");
            Dictionary.Add("parse_CriticalHealingOverTimeLabel", "Critical Healing OT:");
            Dictionary.Add("parse_TotalHealingOverTimeActionsUsedLabel", "Total Healing OT Actions Used:");
            Dictionary.Add("parse_HOTPSLabel", "HOTPS:");
            Dictionary.Add("parse_HealingOverTimeRegHitLabel", "Healing OT Reg Hit:");
            Dictionary.Add("parse_HealingOverTimeRegLowLabel", "Healing OT Reg Low:");
            Dictionary.Add("parse_HealingOverTimeRegHighLabel", "Healing OT Reg High:");
            Dictionary.Add("parse_HealingOverTimeRegAverageLabel", "Healing OT Reg Average:");
            Dictionary.Add("parse_HealingOverTimeRegModLabel", "Healing OT Reg Mod:");
            Dictionary.Add("parse_HealingOverTimeRegModAverageLabel", "Healing OT Reg Mod Average:");
            Dictionary.Add("parse_HealingOverTimeCritHitLabel", "Healing OT Crit Hit:");
            Dictionary.Add("parse_HealingOverTimeCritPercentLabel", "Healing OT Crit Percent:");
            Dictionary.Add("parse_HealingOverTimeCritLowLabel", "Healing OT Crit Low:");
            Dictionary.Add("parse_HealingOverTimeCritHighLabel", "Healing OT Crit High:");
            Dictionary.Add("parse_HealingOverTimeCritAverageLabel", "Healing OT Crit Average:");
            Dictionary.Add("parse_HealingOverTimeCritModLabel", "Healing OT Crit Mod:");
            Dictionary.Add("parse_HealingOverTimeCritModAverageLabel", "Healing OT Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallHealingMitigatedLabel", "Total Overall Healing Mitigated:");
            Dictionary.Add("parse_RegularHealingMitigatedLabel", "Regular Healing Mitigated:");
            Dictionary.Add("parse_CriticalHealingMitigatedLabel", "Critical Healing Mitigated:");
            Dictionary.Add("parse_TotalHealingMitigatedActionsUsedLabel", "Total Healing Mitigated Actions Used:");
            Dictionary.Add("parse_HMPSLabel", "HMPS:");
            Dictionary.Add("parse_HealingMitigatedRegHitLabel", "Healing Mitigated Reg Hit:");
            Dictionary.Add("parse_HealingMitigatedRegLowLabel", "Healing Mitigated Reg Low:");
            Dictionary.Add("parse_HealingMitigatedRegHighLabel", "Healing Mitigated Reg High:");
            Dictionary.Add("parse_HealingMitigatedRegAverageLabel", "Healing Mitigated Reg Average:");
            Dictionary.Add("parse_HealingMitigatedRegModLabel", "Healing Mitigated Reg Mod:");
            Dictionary.Add("parse_HealingMitigatedRegModAverageLabel", "Healing Mitigated Reg Mod Average:");
            Dictionary.Add("parse_HealingMitigatedCritHitLabel", "Healing Mitigated Crit Hit:");
            Dictionary.Add("parse_HealingMitigatedCritPercentLabel", "Healing Mitigated Crit Percent:");
            Dictionary.Add("parse_HealingMitigatedCritLowLabel", "Healing Mitigated Crit Low:");
            Dictionary.Add("parse_HealingMitigatedCritHighLabel", "Healing Mitigated Crit High:");
            Dictionary.Add("parse_HealingMitigatedCritAverageLabel", "Healing Mitigated Crit Average:");
            Dictionary.Add("parse_HealingMitigatedCritModLabel", "Healing Mitigated Crit Mod:");
            Dictionary.Add("parse_HealingMitigatedCritModAverageLabel", "Healing Mitigated Crit Mod Average:");
            Dictionary.Add("parse_TotalOverallDamageTakenLabel", "合計被ダメージ:");
            Dictionary.Add("parse_RegularDamageTakenLabel", "通常被ダメージ数:");
            Dictionary.Add("parse_CriticalDamageTakenLabel", "クリティカル被ダメージ数:");
            Dictionary.Add("parse_TotalDamageTakenActionsUsedLabel", "合計被ダメージ行動数:");
            Dictionary.Add("parse_DTPSLabel", "DTPS:");
            Dictionary.Add("parse_DamageTakenRegHitLabel", "通常被ダメージ数:");
            Dictionary.Add("parse_DamageTakenRegMissLabel", "通常被ダメージミス数:");
            Dictionary.Add("parse_DamageTakenRegAccuracyLabel", "通常被ダメージ命中率:");
            Dictionary.Add("parse_DamageTakenRegLowLabel", "最少通常被ダメージ:");
            Dictionary.Add("parse_DamageTakenRegHighLabel", "最大通常被ダメージ:");
            Dictionary.Add("parse_DamageTakenRegAverageLabel", "平均通常被ダメージ:");
            Dictionary.Add("parse_DamageTakenRegModLabel", "修正通常被ダメージ:");
            Dictionary.Add("parse_DamageTakenRegModAverageLabel", "平均修正通常被ダメージ:");
            Dictionary.Add("parse_DamageTakenCritHitLabel", "クリティカル被ダメージ数:");
            Dictionary.Add("parse_DamageTakenCritPercentLabel", "クリティカル被ダメージ率:");
            Dictionary.Add("parse_DamageTakenCritLowLabel", "最小クリティカル被ダメージ:");
            Dictionary.Add("parse_DamageTakenCritHighLabel", "最大クリティカル被ダメージ:");
            Dictionary.Add("parse_DamageTakenCritAverageLabel", "平均クリティカル被ダメージ:");
            Dictionary.Add("parse_DamageTakenCritModLabel", "修正クリティカル被ダメージ:");
            Dictionary.Add("parse_DamageTakenCritModAverageLabel", "平均修正クリティカル被ダメージ:");
            Dictionary.Add("parse_DamageTakenCounterLabel", "カウンター被ダメージ数:");
            Dictionary.Add("parse_DamageTakenCounterPercentLabel", "カウンター被ダメージ率:");
            Dictionary.Add("parse_DamageTakenCounterModLabel", "修正カウンター被ダメージ:");
            Dictionary.Add("parse_DamageTakenCounterModAverageLabel", "平均修正カウンター被ダメージ:");
            Dictionary.Add("parse_DamageTakenBlockLabel", "ダメージブロック数:");
            Dictionary.Add("parse_DamageTakenBlockPercentLabel", "ダメージブロック率:");
            Dictionary.Add("parse_DamageTakenBlockModLabel", "修正ダメージブロック:");
            Dictionary.Add("parse_DamageTakenBlockModAverageLabel", "平均修正ダメージブロック:");
            Dictionary.Add("parse_DamageTakenParryLabel", "被ダメージ受け流し:");
            Dictionary.Add("parse_DamageTakenParryPercentLabel", "被ダメージ受け流し率:");
            Dictionary.Add("parse_DamageTakenParryModLabel", "修正被ダメージ受け流し:");
            Dictionary.Add("parse_DamageTakenParryModAverageLabel", "平均修正被ダメージ受け流し:");
            Dictionary.Add("parse_DamageTakenResistLabel", "被ダメージレジスト:");
            Dictionary.Add("parse_DamageTakenResistPercentLabel", "被ダメージレジスト率:");
            Dictionary.Add("parse_DamageTakenResistModLabel", "修正被ダメージレジスト");
            Dictionary.Add("parse_DamageTakenResistModAverageLabel", "平均修正被ダメージレジスト:");
            Dictionary.Add("parse_DamageTakenEvadeLabel", "被ダメージ回避:");
            Dictionary.Add("parse_DamageTakenEvadePercentLabel", "被ダメージ回避率:");
            Dictionary.Add("parse_DamageTakenEvadeModLabel", "通常被ダメージ回避:");
            Dictionary.Add("parse_DamageTakenEvadeModAverageLabel", "通常被ダメージ回避率:");
            Dictionary.Add("parse_TotalOverallDamageTakenOverTimeLabel", "Total Overall DT OT:");
            Dictionary.Add("parse_RegularDamageTakenOverTimeLabel", "Regular DT OT:");
            Dictionary.Add("parse_CriticalDamageTakenOverTimeLabel", "Critical DT OT:");
            Dictionary.Add("parse_TotalDamageTakenOverTimeActionsUsedLabel", "Total DT OT Actions Used:");
            Dictionary.Add("parse_DTOTPSLabel", "DTOTPS:");
            Dictionary.Add("parse_DamageTakenOverTimeRegHitLabel", "Damage Taken OT Reg Hit:");
            Dictionary.Add("parse_DamageTakenOverTimeRegMissLabel", "Damage Taken OT Reg Miss:");
            Dictionary.Add("parse_DamageTakenOverTimeRegAccuracyLabel", "Damage Taken OT Reg Accuracy:");
            Dictionary.Add("parse_DamageTakenOverTimeRegLowLabel", "Damage Taken OT Reg Low:");
            Dictionary.Add("parse_DamageTakenOverTimeRegHighLabel", "Damage Taken OT Reg High:");
            Dictionary.Add("parse_DamageTakenOverTimeRegAverageLabel", "Damage Taken OT Reg Average:");
            Dictionary.Add("parse_DamageTakenOverTimeRegModLabel", "Damage Taken OT Reg Mod:");
            Dictionary.Add("parse_DamageTakenOverTimeRegModAverageLabel", "Damage Taken OT Reg Mod Average:");
            Dictionary.Add("parse_DamageTakenOverTimeCritHitLabel", "Damage Taken OT Crit Hit:");
            Dictionary.Add("parse_DamageTakenOverTimeCritPercentLabel", "Damage Taken OT Crit Percent:");
            Dictionary.Add("parse_DamageTakenOverTimeCritLowLabel", "Damage Taken OT Crit Low:");
            Dictionary.Add("parse_DamageTakenOverTimeCritHighLabel", "Damage Taken OT Crit High:");
            Dictionary.Add("parse_DamageTakenOverTimeCritAverageLabel", "Damage Taken OT Crit Average:");
            Dictionary.Add("parse_DamageTakenOverTimeCritModLabel", "Damage Taken OT Crit Mod:");
            Dictionary.Add("parse_DamageTakenOverTimeCritModAverageLabel", "Damage Taken OT Crit Mod Average:");
            Dictionary.Add("parse_TotalBuffTimeLabel", "Total Buff Time:");
            Dictionary.Add("parse_TotalBuffHoursLabel", "Total Buff Hours:");
            Dictionary.Add("parse_TotalBuffMinutesLabel", "Total Buff Minutes:");
            Dictionary.Add("parse_TotalBuffSecondsLabel", "Total Buff Seconds:");
            Dictionary.Add("parse_CombinedTotalOverallDamageLabel", "Combined Total Overall Damage:");
            Dictionary.Add("parse_CombinedRegularDamageLabel", "Combined Regular Damage:");
            Dictionary.Add("parse_CombinedCriticalDamageLabel", "Combined Critical Damage:");
            Dictionary.Add("parse_CombinedTotalDamageActionsUsedLabel", "Combined Total Damage Actions Used:");
            Dictionary.Add("parse_CombinedDPSLabel", "Combined DPS:");
            Dictionary.Add("parse_CombinedDamageRegHitLabel", "Combined Damage Reg Hit:");
            Dictionary.Add("parse_CombinedDamageRegMissLabel", "Combined Damage Reg Miss:");
            Dictionary.Add("parse_CombinedDamageRegAccuracyLabel", "Combined Damage Reg Accuracy:");
            Dictionary.Add("parse_CombinedDamageRegLowLabel", "Combined Damage Reg Low:");
            Dictionary.Add("parse_CombinedDamageRegHighLabel", "Combined Damage Reg High:");
            Dictionary.Add("parse_CombinedDamageRegAverageLabel", "Combined Damage Reg Average:");
            Dictionary.Add("parse_CombinedDamageRegModLabel", "Combined Damage Reg Mod:");
            Dictionary.Add("parse_CombinedDamageRegModAverageLabel", "Combined Damage Reg Mod Average:");
            Dictionary.Add("parse_CombinedDamageCritHitLabel", "Combined Damage Crit Hit:");
            Dictionary.Add("parse_CombinedDamageCritPercentLabel", "Combined Damage Crit Percent:");
            Dictionary.Add("parse_CombinedDamageCritLowLabel", "Combined Damage Crit Low:");
            Dictionary.Add("parse_CombinedDamageCritHighLabel", "Combined Damage Crit High:");
            Dictionary.Add("parse_CombinedDamageCritAverageLabel", "Combined Damage Crit Average:");
            Dictionary.Add("parse_CombinedDamageCritModLabel", "Combined Damage Crit Mod:");
            Dictionary.Add("parse_CombinedDamageCritModAverageLabel", "Combined Damage Crit Mod Average:");
            Dictionary.Add("parse_CombinedDamageCounterLabel", "Combined Damage Counter:");
            Dictionary.Add("parse_CombinedDamageCounterPercentLabel", "Combined Damage Counter Percent:");
            Dictionary.Add("parse_CombinedDamageCounterModLabel", "Combined Damage Counter Mod:");
            Dictionary.Add("parse_CombinedDamageCounterModAverageLabel", "Combined Damage Counter Mod Average:");
            Dictionary.Add("parse_CombinedDamageBlockLabel", "Combined Damage Block:");
            Dictionary.Add("parse_CombinedDamageBlockPercentLabel", "Combined Damage Block Percent:");
            Dictionary.Add("parse_CombinedDamageBlockModLabel", "Combined Damage Block Mod:");
            Dictionary.Add("parse_CombinedDamageBlockModAverageLabel", "Combined Damage Block Mod Average:");
            Dictionary.Add("parse_CombinedDamageParryLabel", "Combined Damage Parry:");
            Dictionary.Add("parse_CombinedDamageParryPercentLabel", "Combined Damage Parry Percent:");
            Dictionary.Add("parse_CombinedDamageParryModLabel", "Combined Damage Parry Mod:");
            Dictionary.Add("parse_CombinedDamageParryModAverageLabel", "Combined Damage Parry Mod Average:");
            Dictionary.Add("parse_CombinedDamageResistLabel", "Combined Damage Resist:");
            Dictionary.Add("parse_CombinedDamageResistPercentLabel", "Combined Damage Resist Percent:");
            Dictionary.Add("parse_CombinedDamageResistModLabel", "Combined Damage Resist Mod:");
            Dictionary.Add("parse_CombinedDamageResistModAverageLabel", "Combined Damage Resist Mod Average:");
            Dictionary.Add("parse_CombinedDamageEvadeLabel", "Combined Damage Evade:");
            Dictionary.Add("parse_CombinedDamageEvadePercentLabel", "Combined Damage Evade Percent:");
            Dictionary.Add("parse_CombinedDamageEvadeModLabel", "Combined Damage Evade Mod:");
            Dictionary.Add("parse_CombinedDamageEvadeModAverageLabel", "Combined Damage Evade Mod Average:");
            Dictionary.Add("parse_CombinedTotalOverallHealingLabel", "Combined Total Overall Healing:");
            Dictionary.Add("parse_CombinedRegularHealingLabel", "Combined Regular Healing:");
            Dictionary.Add("parse_CombinedCriticalHealingLabel", "Combined Critical Healing:");
            Dictionary.Add("parse_CombinedTotalHealingActionsUsedLabel", "Combined Total Healing Actions Used:");
            Dictionary.Add("parse_CombinedHPSLabel", "Combined HPS:");
            Dictionary.Add("parse_CombinedHealingRegHitLabel", "Combined Healing Reg Hit:");
            Dictionary.Add("parse_CombinedHealingRegLowLabel", "Combined Healing Reg Low:");
            Dictionary.Add("parse_CombinedHealingRegHighLabel", "Combined Healing Reg High:");
            Dictionary.Add("parse_CombinedHealingRegAverageLabel", "Combined Healing Reg Average:");
            Dictionary.Add("parse_CombinedHealingRegModLabel", "Combined Healing Reg Mod:");
            Dictionary.Add("parse_CombinedHealingRegModAverageLabel", "Combined Healing Reg Mod Average:");
            Dictionary.Add("parse_CombinedHealingCritHitLabel", "Combined Healing Crit Hit:");
            Dictionary.Add("parse_CombinedHealingCritPercentLabel", "Combined Healing Crit Percent:");
            Dictionary.Add("parse_CombinedHealingCritLowLabel", "Combined Healing Crit Low:");
            Dictionary.Add("parse_CombinedHealingCritHighLabel", "Combined Healing Crit High:");
            Dictionary.Add("parse_CombinedHealingCritAverageLabel", "Combined Healing Crit Average:");
            Dictionary.Add("parse_CombinedHealingCritModLabel", "Combined Healing Crit Mod:");
            Dictionary.Add("parse_CombinedHealingCritModAverageLabel", "Combined Healing Crit Mod Average:");
            Dictionary.Add("parse_CombinedTotalOverallDamageTakenLabel", "Combined Total Overall Damage Taken:");
            Dictionary.Add("parse_CombinedRegularDamageTakenLabel", "Combined Regular Damage Taken:");
            Dictionary.Add("parse_CombinedCriticalDamageTakenLabel", "Combined Critical Damage Taken:");
            Dictionary.Add("parse_CombinedTotalDamageTakenActionsUsedLabel", "Combined Total DT Actions Used:");
            Dictionary.Add("parse_CombinedDTPSLabel", "Combined DTPS:");
            Dictionary.Add("parse_CombinedDamageTakenRegHitLabel", "Combined DT Reg Hit:");
            Dictionary.Add("parse_CombinedDamageTakenRegMissLabel", "Combined DT Reg Miss:");
            Dictionary.Add("parse_CombinedDamageTakenRegAccuracyLabel", "Combined DT Reg Accuracy:");
            Dictionary.Add("parse_CombinedDamageTakenRegLowLabel", "Combined DT Reg Low:");
            Dictionary.Add("parse_CombinedDamageTakenRegHighLabel", "Combined DT Reg High:");
            Dictionary.Add("parse_CombinedDamageTakenRegAverageLabel", "Combined DT Reg Average:");
            Dictionary.Add("parse_CombinedDamageTakenRegModLabel", "Combined DT Reg Mod:");
            Dictionary.Add("parse_CombinedDamageTakenRegModAverageLabel", "Combined DT Reg Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenCritHitLabel", "Combined DT Crit Hit:");
            Dictionary.Add("parse_CombinedDamageTakenCritPercentLabel", "Combined DT Crit Percent:");
            Dictionary.Add("parse_CombinedDamageTakenCritLowLabel", "Combined DT Crit Low:");
            Dictionary.Add("parse_CombinedDamageTakenCritHighLabel", "Combined DT Crit High:");
            Dictionary.Add("parse_CombinedDamageTakenCritAverageLabel", "Combined DT Crit Average:");
            Dictionary.Add("parse_CombinedDamageTakenCritModLabel", "Combined DT Crit Mod:");
            Dictionary.Add("parse_CombinedDamageTakenCritModAverageLabel", "Combined DT Crit Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenCounterLabel", "Combined DT Counter:");
            Dictionary.Add("parse_CombinedDamageTakenCounterPercentLabel", "Combined DT Counter Percent:");
            Dictionary.Add("parse_CombinedDamageTakenCounterModLabel", "Combined DT Counter Mod:");
            Dictionary.Add("parse_CombinedDamageTakenCounterModAverageLabel", "Combined DT Counter Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenBlockLabel", "Combined DT Block:");
            Dictionary.Add("parse_CombinedDamageTakenBlockPercentLabel", "Combined DT Block Percent:");
            Dictionary.Add("parse_CombinedDamageTakenBlockModLabel", "Combined DT Block Mod:");
            Dictionary.Add("parse_CombinedDamageTakenBlockModAverageLabel", "Combined DT Block Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenParryLabel", "Combined DT Parry:");
            Dictionary.Add("parse_CombinedDamageTakenParryPercentLabel", "Combined DT Parry Percent:");
            Dictionary.Add("parse_CombinedDamageTakenParryModLabel", "Combined DT Parry Mod:");
            Dictionary.Add("parse_CombinedDamageTakenParryModAverageLabel", "Combined DT Parry Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenResistLabel", "Combined DT Resist:");
            Dictionary.Add("parse_CombinedDamageTakenResistPercentLabel", "Combined DT Resist Percent:");
            Dictionary.Add("parse_CombinedDamageTakenResistModLabel", "Combined DT Resist Mod:");
            Dictionary.Add("parse_CombinedDamageTakenResistModAverageLabel", "Combined DT Resist Mod Average:");
            Dictionary.Add("parse_CombinedDamageTakenEvadeLabel", "Combined DT Evade:");
            Dictionary.Add("parse_CombinedDamageTakenEvadePercentLabel", "Combined DT Evade Percent:");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModLabel", "Combined DT Evade Mod:");
            Dictionary.Add("parse_CombinedDamageTakenEvadeModAverageLabel", "Combined DT Evade Mod Average:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageLabel", "全ダメージ率:");
            Dictionary.Add("parse_PercentOfRegularDamageLabel", "通常ダメージ率:");
            Dictionary.Add("parse_PercentOfCriticalDamageLabel", "クリティカルダメージ率:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageOverTimeLabel", "Percent Of Total Overall Damage OT:");
            Dictionary.Add("parse_PercentOfRegularDamageOverTimeLabel", "Percent Of Regular Damage OT:");
            Dictionary.Add("parse_PercentOfCriticalDamageOverTimeLabel", "Percent Of Critical Damage OT:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingLabel", "合計回復率:");
            Dictionary.Add("parse_PercentOfRegularHealingLabel", "通常回復率:");
            Dictionary.Add("parse_PercentOfCriticalHealingLabel", "クリティカル回復率:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverHealingLabel", "Percent Of Total Overall Healing OH:");
            Dictionary.Add("parse_PercentOfRegularHealingOverHealingLabel", "Percent Of Regular Healing OH:");
            Dictionary.Add("parse_PercentOfCriticalHealingOverHealingLabel", "Percent Of Critical Healing OH:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingOverTimeLabel", "Percent Of Total Overall Healing OT:");
            Dictionary.Add("parse_PercentOfRegularHealingOverTimeLabel", "Percent Of Regular Healing OT:");
            Dictionary.Add("parse_PercentOfCriticalHealingOverTimeLabel", "Percent Of Critical Healing OT:");
            Dictionary.Add("parse_PercentOfTotalOverallHealingMitigatedLabel", "Percent Of Total Overall Healing Mitigated:");
            Dictionary.Add("parse_PercentOfRegularHealingMitigatedLabel", "Percent Of Regular Healing Mitigated:");
            Dictionary.Add("parse_PercentOfCriticalHealingMitigatedLabel", "Percent Of Critical Healing Mitigated:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenLabel", "合計被ダメージ率:");
            Dictionary.Add("parse_PercentOfRegularDamageTakenLabel", "通常被ダメージ率:");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenLabel", "クリティカル被ダメージ率:");
            Dictionary.Add("parse_PercentOfTotalOverallDamageTakenOverTimeLabel", "Percent Of Total Overall DT OT:");
            Dictionary.Add("parse_PercentOfRegularDamageTakenOverTimeLabel", "Percent Of Regular DT OT:");
            Dictionary.Add("parse_PercentOfCriticalDamageTakenOverTimeLabel", "Percent Of Critical DT OT:");
            Dictionary.Add("parse_ShowTotalOverallDamageInfoHeader", "全与ダメージ数を表示する");
            Dictionary.Add("parse_ShowRegularDamageInfoHeader", "通常攻撃与ダメージ数を表示する");
            Dictionary.Add("parse_ShowCriticalDamageInfoHeader", "クリティカル与ダメージ数を表示する");
            Dictionary.Add("parse_ShowTotalDamageActionsUsedInfoHeader", "実行した全与ダメージ行動数を表示する");
            Dictionary.Add("parse_ShowDPSInfoHeader", "DPSを表示する");
            Dictionary.Add("parse_ShowDamageRegHitInfoHeader", "通常与ダメージヒット数を表示する");
            Dictionary.Add("parse_ShowDamageRegMissInfoHeader", "通常与ダメージミス数を表示する");
            Dictionary.Add("parse_ShowDamageRegAccuracyInfoHeader", "通常与ダメージ命中率を表示する");
            Dictionary.Add("parse_ShowDamageRegLowInfoHeader", "最少通常与ダメージを表示する");
            Dictionary.Add("parse_ShowDamageRegHighInfoHeader", "最大通常与ダメージを表示する");
            Dictionary.Add("parse_ShowDamageRegAverageInfoHeader", "平均通常与ダメージを表示する");
            Dictionary.Add("parse_ShowDamageRegModInfoHeader", "修正通常ダメージを表示する");
            Dictionary.Add("parse_ShowDamageRegModAverageInfoHeader", "平均修正通常ダメージを表示する");
            Dictionary.Add("parse_ShowDamageCritHitInfoHeader", "クリティカルヒット与ダメージ数を表示する");
            Dictionary.Add("parse_ShowDamageCritPercentInfoHeader", "クリティカルヒット与ダメージ率を表示する");
            Dictionary.Add("parse_ShowDamageCritLowInfoHeader", "最少クリティカルヒット与ダメージを表示する");
            Dictionary.Add("parse_ShowDamageCritHighInfoHeader", "最大クリティカルヒット与ダメージを表示する");
            Dictionary.Add("parse_ShowDamageCritAverageInfoHeader", "平均クリティカルヒット与ダメージを表示する");
            Dictionary.Add("parse_ShowDamageCritModInfoHeader", "修正クリティカルダメージを表示する");
            Dictionary.Add("parse_ShowDamageCritModAverageInfoHeader", "平均修正クリティカルダメージを表示する");
            Dictionary.Add("parse_ShowDamageCounterInfoHeader", "カウンターダメージを表示する");
            Dictionary.Add("parse_ShowDamageCounterPercentInfoHeader", "カウンターダメージ率を表示する");
            Dictionary.Add("parse_ShowDamageCounterModInfoHeader", "修正カウンターダメージを表示する");
            Dictionary.Add("parse_ShowDamageCounterModAverageInfoHeader", "平均修正カウンターダメージを表示する");
            Dictionary.Add("parse_ShowDamageBlockInfoHeader", "ブロック数を表示する");
            Dictionary.Add("parse_ShowDamageBlockPercentInfoHeader", "ブロック率を表示する");
            Dictionary.Add("parse_ShowDamageBlockModInfoHeader", "修正ブロック量を表示する");
            Dictionary.Add("parse_ShowDamageBlockModAverageInfoHeader", "平均修正ブロック量を表示する");
            Dictionary.Add("parse_ShowDamageParryInfoHeader", "受け流し数を表示する");
            Dictionary.Add("parse_ShowDamageParryPercentInfoHeader", "受け流し率を表示する");
            Dictionary.Add("parse_ShowDamageParryModInfoHeader", "修正ダメージ受け流し量を表示する");
            Dictionary.Add("parse_ShowDamageParryModAverageInfoHeader", "平均修正ダメージ受け流し量を表示する");
            Dictionary.Add("parse_ShowDamageResistInfoHeader", "ダメージレジストを表示する");
            Dictionary.Add("parse_ShowDamageResistPercentInfoHeader", "ダメージレジスト率を表示する");
            Dictionary.Add("parse_ShowDamageResistModInfoHeader", "修正ダメージレジストを表示する");
            Dictionary.Add("parse_ShowDamageResistModAverageInfoHeader", "平均修正ダメージレジストを表示する");
            Dictionary.Add("parse_ShowDamageEvadeInfoHeader", "回避数を表示する");
            Dictionary.Add("parse_ShowDamageEvadePercentInfoHeader", "回避率を表示する");
            Dictionary.Add("parse_ShowDamageEvadeModInfoHeader", "修正回避量を表示する");
            Dictionary.Add("parse_ShowDamageEvadeModAverageInfoHeader", "平均修正回避量を表示する");
            Dictionary.Add("parse_ShowTotalOverallDamageOverTimeInfoHeader", "Show Total Overall Damage OT Information");
            Dictionary.Add("parse_ShowRegularDamageOverTimeInfoHeader", "Show Regular Damage OT Information");
            Dictionary.Add("parse_ShowCriticalDamageOverTimeInfoHeader", "Show Critical Damage OT Information");
            Dictionary.Add("parse_ShowTotalDamageOverTimeActionsUsedInfoHeader", "Show Total Damage OT Actions Used Information");
            Dictionary.Add("parse_ShowDOTPSInfoHeader", "Show DOTPS Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegHitInfoHeader", "Show Damage OT Reg Hit Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegMissInfoHeader", "Show Damage OT Reg Miss Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegAccuracyInfoHeader", "Show Damage OT Reg Accuracy Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegLowInfoHeader", "Show Damage OT Reg Low Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegHighInfoHeader", "Show Damage OT Reg High Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegAverageInfoHeader", "Show Damage OT Reg Average Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegModInfoHeader", "Show Damage OT Reg Mod Information");
            Dictionary.Add("parse_ShowDamageOverTimeRegModAverageInfoHeader", "Show Damage OT Reg Mod Average Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritHitInfoHeader", "Show Damage OT Crit Hit Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritPercentInfoHeader", "Show Damage OT Crit Percent Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritLowInfoHeader", "Show Damage OT Crit Low Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritHighInfoHeader", "Show Damage OT Crit High Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritAverageInfoHeader", "Show Damage OT Crit Average Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritModInfoHeader", "Show Damage OT Crit Mod Information");
            Dictionary.Add("parse_ShowDamageOverTimeCritModAverageInfoHeader", "Show Damage OT Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallHealingInfoHeader", "全回復量を表示する");
            Dictionary.Add("parse_ShowRegularHealingInfoHeader", "平均回復量を表示する");
            Dictionary.Add("parse_ShowCriticalHealingInfoHeader", "クリティカル回復量を表示する");
            Dictionary.Add("parse_ShowTotalHealingActionsUsedInfoHeader", "実行された回復行動数を表示する");
            Dictionary.Add("parse_ShowHPSInfoHeader", "HPSを表示する");
            Dictionary.Add("parse_ShowHealingRegHitInfoHeader", "通常回復ヒット数を表示する");
            Dictionary.Add("parse_ShowHealingRegLowInfoHeader", "最少通常回復量を表示する");
            Dictionary.Add("parse_ShowHealingRegHighInfoHeader", "最大通常回復量を表示する");
            Dictionary.Add("parse_ShowHealingRegAverageInfoHeader", "平均通常回復量を表示する");
            Dictionary.Add("parse_ShowHealingRegModInfoHeader", "修正通常回復量を表示する");
            Dictionary.Add("parse_ShowHealingRegModAverageInfoHeader", "平均修正通常回復量を表示する");
            Dictionary.Add("parse_ShowHealingCritHitInfoHeader", "クリティカル回復量を表示する");
            Dictionary.Add("parse_ShowHealingCritPercentInfoHeader", "クリティカル回復率を表示する");
            Dictionary.Add("parse_ShowHealingCritLowInfoHeader", "最少クリティカル回復量を表示する");
            Dictionary.Add("parse_ShowHealingCritHighInfoHeader", "最大クリティカル回復量を表示する");
            Dictionary.Add("parse_ShowHealingCritAverageInfoHeader", "平均クリティカル回復量を表示する");
            Dictionary.Add("parse_ShowHealingCritModInfoHeader", "修正クリティカル回復量を表示する");
            Dictionary.Add("parse_ShowHealingCritModAverageInfoHeader", "平均修正クリティカル回復量を表示する");
            Dictionary.Add("parse_ShowTotalOverallHealingOverHealingInfoHeader", "Show Total Overall Healing OH Information");
            Dictionary.Add("parse_ShowRegularHealingOverHealingInfoHeader", "Show Regular Healing OH Information");
            Dictionary.Add("parse_ShowCriticalHealingOverHealingInfoHeader", "Show Critical Healing OH Information");
            Dictionary.Add("parse_ShowTotalHealingOverHealingActionsUsedInfoHeader", "Show Total Healing OH Actions Used Information");
            Dictionary.Add("parse_ShowHOHPSInfoHeader", "Show HOHPS Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegHitInfoHeader", "Show Healing OH Reg Hit Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegLowInfoHeader", "Show Healing OH Reg Low Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegHighInfoHeader", "Show Healing OH Reg High Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegAverageInfoHeader", "Show Healing OH Reg Average Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegModInfoHeader", "Show Healing OH Reg Mod Information");
            Dictionary.Add("parse_ShowHealingOverHealingRegModAverageInfoHeader", "Show Healing OH Reg Mod Average Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritHitInfoHeader", "Show Healing OH Crit Hit Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritPercentInfoHeader", "Show Healing OH Crit Percent Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritLowInfoHeader", "Show Healing OH Crit Low Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritHighInfoHeader", "Show Healing OH Crit High Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritAverageInfoHeader", "Show Healing OH Crit Average Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritModInfoHeader", "Show Healing OH Crit Mod Information");
            Dictionary.Add("parse_ShowHealingOverHealingCritModAverageInfoHeader", "Show Healing OH Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallHealingOverTimeInfoHeader", "Show Total Overall Healing OT Information");
            Dictionary.Add("parse_ShowRegularHealingOverTimeInfoHeader", "Show Regular Healing OT Information");
            Dictionary.Add("parse_ShowCriticalHealingOverTimeInfoHeader", "Show Critical Healing OT Information");
            Dictionary.Add("parse_ShowTotalHealingOverTimeActionsUsedInfoHeader", "Show Total Healing OT Actions Used Information");
            Dictionary.Add("parse_ShowHOTPSInfoHeader", "Show HOTPS Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegHitInfoHeader", "Show Healing OT Reg Hit Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegLowInfoHeader", "Show Healing OT Reg Low Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegHighInfoHeader", "Show Healing OT Reg High Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegAverageInfoHeader", "Show Healing OT Reg Average Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegModInfoHeader", "Show Healing OT Reg Mod Information");
            Dictionary.Add("parse_ShowHealingOverTimeRegModAverageInfoHeader", "Show Healing OT Reg Mod Average Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritHitInfoHeader", "Show Healing OT Crit Hit Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritPercentInfoHeader", "Show Healing OT Crit Percent Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritLowInfoHeader", "Show Healing OT Crit Low Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritHighInfoHeader", "Show Healing OT Crit High Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritAverageInfoHeader", "Show Healing OT Crit Average Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritModInfoHeader", "Show Healing OT Crit Mod Information");
            Dictionary.Add("parse_ShowHealingOverTimeCritModAverageInfoHeader", "Show Healing OT Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallHealingMitigatedInfoHeader", "Show Total Overall Healing Mitigated Information");
            Dictionary.Add("parse_ShowRegularHealingMitigatedInfoHeader", "Show Regular Healing Mitigated Information");
            Dictionary.Add("parse_ShowCriticalHealingMitigatedInfoHeader", "Show Critical Healing Mitigated Information");
            Dictionary.Add("parse_ShowTotalHealingMitigatedActionsUsedInfoHeader", "Show Total Healing Mitigated Actions Used Information");
            Dictionary.Add("parse_ShowHMPSInfoHeader", "Show HMPS Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegHitInfoHeader", "Show Healing Mitigated Reg Hit Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegLowInfoHeader", "Show Healing Mitigated Reg Low Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegHighInfoHeader", "Show Healing Mitigated Reg High Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegAverageInfoHeader", "Show Healing Mitigated Reg Average Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegModInfoHeader", "Show Healing Mitigated Reg Mod Information");
            Dictionary.Add("parse_ShowHealingMitigatedRegModAverageInfoHeader", "Show Healing Mitigated Reg Mod Average Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritHitInfoHeader", "Show Healing Mitigated Crit Hit Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritPercentInfoHeader", "Show Healing Mitigated Crit Percent Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritLowInfoHeader", "Show Healing Mitigated Crit Low Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritHighInfoHeader", "Show Healing Mitigated Crit High Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritAverageInfoHeader", "Show Healing Mitigated Crit Average Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritModInfoHeader", "Show Healing Mitigated Crit Mod Information");
            Dictionary.Add("parse_ShowHealingMitigatedCritModAverageInfoHeader", "Show Healing Mitigated Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalOverallDamageTakenInfoHeader", "合計被ダメージ量を表示する");
            Dictionary.Add("parse_ShowRegularDamageTakenInfoHeader", "通常被ダメージ量を表示する");
            Dictionary.Add("parse_ShowCriticalDamageTakenInfoHeader", "クリティカル被ダメージ量を表示する");
            Dictionary.Add("parse_ShowTotalDamageTakenActionsUsedInfoHeader", "被ダメージ行動を表示する");
            Dictionary.Add("parse_ShowDTPSInfoHeader", "DTPSを表示する");
            Dictionary.Add("parse_ShowDamageTakenRegHitInfoHeader", "通常被ダメージヒット数を表示する");
            Dictionary.Add("parse_ShowDamageTakenRegMissInfoHeader", "通常被ダメージミス数を表示する");
            Dictionary.Add("parse_ShowDamageTakenRegAccuracyInfoHeader", "通常被ダメージ命中率を表示する");
            Dictionary.Add("parse_ShowDamageTakenRegLowInfoHeader", "最少通常被ダメージ値を表示する");
            Dictionary.Add("parse_ShowDamageTakenRegHighInfoHeader", "最大通常被ダメージ値を表示する");
            Dictionary.Add("parse_ShowDamageTakenRegAverageInfoHeader", "平均通常被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenRegModInfoHeader", "修正通常被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenRegModAverageInfoHeader", "平均修正通常被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenCritHitInfoHeader", "クリティカル被ダメージヒット数を表示する");
            Dictionary.Add("parse_ShowDamageTakenCritPercentInfoHeader", "クリティカル被ダメージ率を表示する");
            Dictionary.Add("parse_ShowDamageTakenCritLowInfoHeader", "クリティカル被ダメージ最小値を表示する");
            Dictionary.Add("parse_ShowDamageTakenCritHighInfoHeader", "クリティカル被ダメージ最大値を表示する");
            Dictionary.Add("parse_ShowDamageTakenCritAverageInfoHeader", "平均クリティカル被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenCritModInfoHeader", "修正被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenCritModAverageInfoHeader", "平均修正被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenCounterInfoHeader", "カウンター被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenCounterPercentInfoHeader", "カウンター被ダメージ率を表示する");
            Dictionary.Add("parse_ShowDamageTakenCounterModInfoHeader", "修正カウンター被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenCounterModAverageInfoHeader", "平均修正カウンター被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenBlockInfoHeader", "被ダメージブロックを表示する");
            Dictionary.Add("parse_ShowDamageTakenBlockPercentInfoHeader", "被ダメージブロック率を表示する");
            Dictionary.Add("parse_ShowDamageTakenBlockModInfoHeader", "修正被ダメージブロックを表示する");
            Dictionary.Add("parse_ShowDamageTakenBlockModAverageInfoHeader", "平均修正被ダメージブロックを表示する");
            Dictionary.Add("parse_ShowDamageTakenParryInfoHeader", "受け流し被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenParryPercentInfoHeader", "受け流し被ダメージ率を表示する");
            Dictionary.Add("parse_ShowDamageTakenParryModInfoHeader", "修正受け流し被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenParryModAverageInfoHeader", "平均修正受け流し被ダメージを表示する");
            Dictionary.Add("parse_ShowDamageTakenResistInfoHeader", "被ダメージレジストを表示する");
            Dictionary.Add("parse_ShowDamageTakenResistPercentInfoHeader", "被ダメージレジスト率を表示する");
            Dictionary.Add("parse_ShowDamageTakenResistModInfoHeader", "被ダメージ修正レジストを表示する");
            Dictionary.Add("parse_ShowDamageTakenResistModAverageInfoHeader", "平均被ダメージ修正レジストを表示する");
            Dictionary.Add("parse_ShowDamageTakenEvadeInfoHeader", "被ダメージ回避を表示する");
            Dictionary.Add("parse_ShowDamageTakenEvadePercentInfoHeader", "被ダメージ回避率を表示する");
            Dictionary.Add("parse_ShowDamageTakenEvadeModInfoHeader", "修正被ダメージ回避を表示する");
            Dictionary.Add("parse_ShowDamageTakenEvadeModAverageInfoHeader", "平均修正被ダメージ回避を表示する");
            Dictionary.Add("parse_ShowTotalOverallDamageTakenOverTimeInfoHeader", "Show Total Overall DT OT Information");
            Dictionary.Add("parse_ShowRegularDamageTakenOverTimeInfoHeader", "Show Regular DT OT Information");
            Dictionary.Add("parse_ShowCriticalDamageTakenOverTimeInfoHeader", "Show Critical DT OT Information");
            Dictionary.Add("parse_ShowTotalDamageTakenOverTimeActionsUsedInfoHeader", "Show Total DT OT Actions Used Information");
            Dictionary.Add("parse_ShowDTOTPSInfoHeader", "Show DTOTPS Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegHitInfoHeader", "Show DT OT Reg Hit Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegMissInfoHeader", "Show DT OT Reg Miss Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegAccuracyInfoHeader", "Show DT OT Reg Accuracy Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegLowInfoHeader", "Show DT OT Reg Low Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegHighInfoHeader", "Show DT OT Reg High Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegAverageInfoHeader", "Show DT OT Reg Average Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegModInfoHeader", "Show DT OT Reg Mod Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeRegModAverageInfoHeader", "Show DT OT Reg Mod Average Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritHitInfoHeader", "Show DT OT Crit Hit Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritPercentInfoHeader", "Show DT OT Crit Percent Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritLowInfoHeader", "Show DT OT Crit Low Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritHighInfoHeader", "Show DT OT Crit High Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritAverageInfoHeader", "Show DT OT Crit Average Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritModInfoHeader", "Show DT OT Crit Mod Information");
            Dictionary.Add("parse_ShowDamageTakenOverTimeCritModAverageInfoHeader", "Show DT OT Crit Mod Average Information");
            Dictionary.Add("parse_ShowTotalBuffTimeInfoHeader", "Show Total Buff Time Info");
            Dictionary.Add("parse_ShowTotalBuffHoursInfoHeader", "Show Total Buff Hours Info");
            Dictionary.Add("parse_ShowTotalBuffMinutesInfoHeader", "Show Total Buff Minutes Info");
            Dictionary.Add("parse_ShowTotalBuffSecondsInfoHeader", "Show Total Buff Seconds Info");
            Dictionary.Add("parse_ShowCombinedTotalOverallDamageInfoHeader", "Show Combined Total Overall Damage Info:");
            Dictionary.Add("parse_ShowCombinedRegularDamageInfoHeader", "Show Combined Regular Damage Info:");
            Dictionary.Add("parse_ShowCombinedCriticalDamageInfoHeader", "Show Combined Critical Damage Info:");
            Dictionary.Add("parse_ShowCombinedTotalDamageActionsUsedInfoHeader", "Show Combined Total Damage Actions Used Info:");
            Dictionary.Add("parse_ShowCombinedDPSInfoHeader", "Show Combined DPS Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegHitInfoHeader", "Show Combined Damage Reg Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegMissInfoHeader", "Show Combined Damage Reg Miss Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegAccuracyInfoHeader", "Show Combined Damage Reg Accuracy Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegLowInfoHeader", "Show Combined Damage Reg Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegHighInfoHeader", "Show Combined Damage Reg High Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegAverageInfoHeader", "Show Combined Damage Reg Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegModInfoHeader", "Show Combined Damage Reg Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageRegModAverageInfoHeader", "Show Combined Damage Reg Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritHitInfoHeader", "Show Combined Damage Crit Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritPercentInfoHeader", "Show Combined Damage Crit Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritLowInfoHeader", "Show Combined Damage Crit Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritHighInfoHeader", "Show Combined Damage Crit High Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritAverageInfoHeader", "Show Combined Damage Crit Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritModInfoHeader", "Show Combined Damage Crit Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageCritModAverageInfoHeader", "Show Combined Damage Crit Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterInfoHeader", "Show Combined Damage Counter Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterPercentInfoHeader", "Show Combined Damage Counter Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterModInfoHeader", "Show Combined Damage Counter Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageCounterModAverageInfoHeader", "Show Combined Damage Counter Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockInfoHeader", "Show Combined Damage Block Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockPercentInfoHeader", "Show Combined Damage Block Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockModInfoHeader", "Show Combined Damage Block Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageBlockModAverageInfoHeader", "Show Combined Damage Block Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryInfoHeader", "Show Combined Damage Parry Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryPercentInfoHeader", "Show Combined Damage Parry Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryModInfoHeader", "Show Combined Damage Parry Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageParryModAverageInfoHeader", "Show Combined Damage Parry Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistInfoHeader", "Show Combined Damage Resist Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistPercentInfoHeader", "Show Combined Damage Resist Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistModInfoHeader", "Show Combined Damage Resist Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageResistModAverageInfoHeader", "Show Combined Damage Resist Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadeInfoHeader", "Show Combined Damage Evade Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadePercentInfoHeader", "Show Combined Damage Evade Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadeModInfoHeader", "Show Combined Damage Evade Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageEvadeModAverageInfoHeader", "Show Combined Damage Evade Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedTotalOverallHealingInfoHeader", "Show Combined Total Overall Healing Info:");
            Dictionary.Add("parse_ShowCombinedRegularHealingInfoHeader", "Show Combined Regular Healing Info:");
            Dictionary.Add("parse_ShowCombinedCriticalHealingInfoHeader", "Show Combined Critical Healing Info:");
            Dictionary.Add("parse_ShowCombinedTotalHealingActionsUsedInfoHeader", "Show Combined Total Healing Actions Used Info:");
            Dictionary.Add("parse_ShowCombinedHPSInfoHeader", "Show Combined HPS Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegHitInfoHeader", "Show Combined Healing Reg Hit Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegLowInfoHeader", "Show Combined Healing Reg Low Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegHighInfoHeader", "Show Combined Healing Reg High Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegAverageInfoHeader", "Show Combined Healing Reg Average Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegModInfoHeader", "Show Combined Healing Reg Mod Info:");
            Dictionary.Add("parse_ShowCombinedHealingRegModAverageInfoHeader", "Show Combined Healing Reg Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritHitInfoHeader", "Show Combined Healing Crit Hit Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritPercentInfoHeader", "Show Combined Healing Crit Percent Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritLowInfoHeader", "Show Combined Healing Crit Low Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritHighInfoHeader", "Show Combined Healing Crit High Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritAverageInfoHeader", "Show Combined Healing Crit Average Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritModInfoHeader", "Show Combined Healing Crit Mod Info:");
            Dictionary.Add("parse_ShowCombinedHealingCritModAverageInfoHeader", "Show Combined Healing Crit Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedTotalOverallDamageTakenInfoHeader", "Show Combined Total Overall Damage Taken Info:");
            Dictionary.Add("parse_ShowCombinedRegularDamageTakenInfoHeader", "Show Combined Regular Damage Taken Info:");
            Dictionary.Add("parse_ShowCombinedCriticalDamageTakenInfoHeader", "Show Combined Critical Damage Taken Info:");
            Dictionary.Add("parse_ShowCombinedTotalDamageTakenActionsUsedInfoHeader", "Show Combined Total DT Actions Used Info:");
            Dictionary.Add("parse_ShowCombinedDTPSInfoHeader", "Show Combined DTPS Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegHitInfoHeader", "Show Combined DT Reg Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegMissInfoHeader", "Show Combined DT Reg Miss Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegAccuracyInfoHeader", "Show Combined DT Reg Accuracy Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegLowInfoHeader", "Show Combined DT Reg Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegHighInfoHeader", "Show Combined DT Reg High Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegAverageInfoHeader", "Show Combined DT Reg Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegModInfoHeader", "Show Combined DT Reg Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenRegModAverageInfoHeader", "Show Combined DT Reg Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritHitInfoHeader", "Show Combined DT Crit Hit Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritPercentInfoHeader", "Show Combined DT Crit Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritLowInfoHeader", "Show Combined DT Crit Low Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritHighInfoHeader", "Show Combined DT Crit High Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritAverageInfoHeader", "Show Combined DT Crit Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritModInfoHeader", "Show Combined DT Crit Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCritModAverageInfoHeader", "Show Combined DT Crit Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterInfoHeader", "Show Combined DT Counter Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterPercentInfoHeader", "Show Combined DT Counter Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterModInfoHeader", "Show Combined DT Counter Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenCounterModAverageInfoHeader", "Show Combined DT Counter Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockInfoHeader", "Show Combined DT Block Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockPercentInfoHeader", "Show Combined DT Block Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockModInfoHeader", "Show Combined DT Block Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenBlockModAverageInfoHeader", "Show Combined DT Block Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryInfoHeader", "Show Combined DT Parry Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryPercentInfoHeader", "Show Combined DT Parry Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryModInfoHeader", "Show Combined DT Parry Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenParryModAverageInfoHeader", "Show Combined DT Parry Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistInfoHeader", "Show Combined DT Resist Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistPercentInfoHeader", "Show Combined DT Resist Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistModInfoHeader", "Show Combined DT Resist Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenResistModAverageInfoHeader", "Show Combined DT Resist Mod Average Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadeInfoHeader", "Show Combined DT Evade Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadePercentInfoHeader", "Show Combined DT Evade Percent Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadeModInfoHeader", "Show Combined DT Evade Mod Info:");
            Dictionary.Add("parse_ShowCombinedDamageTakenEvadeModAverageInfoHeader", "Show Combined DT Evade Mod Average Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageInfoHeader", "Show Percent Of Total Overall Damage Info:");
            Dictionary.Add("parse_ShowPercentOfRegularDamageInfoHeader", "Show Percent Of Regular Damage Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageInfoHeader", "Show Percent Of Critical Damage Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageOverTimeInfoHeader", "Show Percent Of Total Overall Damage OT Info:");
            Dictionary.Add("parse_ShowPercentOfRegularDamageOverTimeInfoHeader", "Show Percent Of Regular Damage OT Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageOverTimeInfoHeader", "Show Percent Of Critical Damage OT Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingInfoHeader", "Show Percent Of Total Overall Healing Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingInfoHeader", "Show Percent Of Regular Healing Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingInfoHeader", "Show Percent Of Critical Healing Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingOverHealingInfoHeader", "Show Percent Of Total Overall Healing OH Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingOverHealingInfoHeader", "Show Percent Of Regular Healing OH Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingOverHealingInfoHeader", "Show Percent Of Critical Healing OH Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingOverTimeInfoHeader", "Show Percent Of Total Overall Healing OT Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingOverTimeInfoHeader", "Show Percent Of Regular Healing OT Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingOverTimeInfoHeader", "Show Percent Of Critical Healing OT Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallHealingMitigatedInfoHeader", "Show Percent Of Total Overall Healing Mitigated Info:");
            Dictionary.Add("parse_ShowPercentOfRegularHealingMitigatedInfoHeader", "Show Percent Of Regular Healing Mitigated Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalHealingMitigatedInfoHeader", "Show Percent Of Critical Healing Mitigated Info:");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageTakenInfoHeader", "合計被ダメージ量を表示する");
            Dictionary.Add("parse_ShowPercentOfRegularDamageTakenInfoHeader", "通常被ダメージ量を表示する");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageTakenInfoHeader", "クリティカル被ダメージ量を表示する");
            Dictionary.Add("parse_ShowPercentOfTotalOverallDamageTakenOverTimeInfoHeader", "Show Percent Of Total Overall DT OT Info:");
            Dictionary.Add("parse_ShowPercentOfRegularDamageTakenOverTimeInfoHeader", "Show Percent Of Regular DT OT Info:");
            Dictionary.Add("parse_ShowPercentOfCriticalDamageTakenOverTimeInfoHeader", "Show Percent Of Critical DT OT Info:");
            Dictionary.Add("parse_LoadExistingLogFileButtonText", "保存済みログファイルを読み込む");
            Dictionary.Add("parse_BasicGlobalWarningLabel", "これは全ての戦闘をまとめて計測したものです。プレイヤーあるいは敵毎のより詳細な比較(DPS等)を知りたい場合には\"詳細表示\"をクリックして下さい。");
            Dictionary.Add("parse_HistoryToolTip", "履歴");
            Dictionary.Add("parse_StoreHistoryIntervalHeader", "履歴の保存間隔");
            Dictionary.Add("parse_EnableStoreHistoryResetHeader", "保存済み履歴の自動リセットを有効にする");
            Dictionary.Add("parse_StoreHistoryEventHeader", "履歴の保存トリガーとなるイベント");
            Dictionary.Add("parse_StoreHistoryEventHelperText", "*有効にすると履歴と解析結果は、選択したイベントが指定した間隔後に発生しなかった時に保存・リセットされます。");
            Dictionary.Add("parse_IgnoreLimitBreaksHeader", "リミットブレイクでのダメージを除外する");
            Dictionary.Add("parse_AutoLoadLastParseFromHistoryHeader", "履歴からリセット毎の最新解析結果を自動で読み込む");
            Dictionary.Add("parse_ResetDamageOnlyOption", "ダメージのみ");
            Dictionary.Add("parse_ResetAnyOption", "すべて");
            Dictionary.Add("parse_ScoreCardHeader", "スコアカード(パーティ)");
            Dictionary.Add("parse_TrackXPSFromParseStartEventHeader", "Track (D|DT|H)PS From Parse Start (ALL)");
            Dictionary.Add("parse_TrackXPSFromParseStartEventHelpText", "*With this enabled all PerSecond tracking will be done globablly from the start of the parse. This means if someone doesn't do anything for a minute their DPS on their second attack will be much lower than if it was tracking from Action StartTime");
            Dictionary.Add("parse_NameHeader", "名前");
            Dictionary.Add("parse_ColumnDisplaySettingsTabHeader", "表示カラム設定");
            Dictionary.Add("parse_BasicDisplaySettingsTabHeader", "簡易表示設定");
            Dictionary.Add("parse_ResetStatsMessage", "現在の表示をクリアしますか？");
            Dictionary.Add("parse_ResetStatsToolTip", "リセット");
            Dictionary.Add("parse_AdvancedCheckBoxText", "詳細表示");
            Dictionary.Add("parse_PartyComboBoxItemText", "Party");
            Dictionary.Add("parse_PartyAllComboBoxItemText", "Party (ALL)");
            Dictionary.Add("parse_MonsterComboBoxItemText", "Monster");
            Dictionary.Add("parse_MonsterAllComboBoxItemText", "Monster (ALL)");
            Dictionary.Add("parse_ScoreCardsComboBoxItemText", "スコアカード");
            Dictionary.Add("parse_PartyDamageActionsHeader", "Damage (Actions)");
            Dictionary.Add("parse_PartyDamageMonstersHeader", "Damage (Monsters)");
            Dictionary.Add("parse_PartyHealingActionsHeader", "Healing (Actions)");
            Dictionary.Add("parse_PartyHealingPlayersHeader", "Healing (Players)");
            Dictionary.Add("parse_PartyBuffsHeader", "Buffs");
            Dictionary.Add("parse_PartyDamageTakenActionsHeader", "Damage Taken (Actions)");
            Dictionary.Add("parse_PartyDamageTakenMonstersHeader", "Damage Taken (Monsters)");
            Dictionary.Add("parse_MonsterDamageActionsHeader", "Damage (Actions)");
            Dictionary.Add("parse_MonsterDamagePlayersHeader", "Damage (Players)");
            Dictionary.Add("parse_MonsterDamageTakenActionsHeader", "Damage Taken (Actions)");
            Dictionary.Add("parse_MonsterDamageTakenPlayersHeader", "Damage Taken (Players)");
            Dictionary.Add("parse_TotalsNormalHeader", "Totals (Normal)");
            Dictionary.Add("parse_TotalsActionsHeader", "Totals (Actions)");
            Dictionary.Add("parse_TotalsOverTimeHeader", "Totals (Over Time)");
            Dictionary.Add("parse_TotalsOverHealingHeader", "Totals (Over Healing)");
            Dictionary.Add("parse_TotalsMitigatedHeader", "Totals (Mitigated)");
            Dictionary.Add("parse_TotalsOverallHeader", "Totals (Overall)");
            Dictionary.Add("parse_TotalsPlayersHeader", "Totals (Players)");
            Dictionary.Add("parse_TotalsPlayersByActionHeader", "Totals (Players By Action)");
            Dictionary.Add("parse_RefreshSelectedButtonText", "Refresh Selected");
            Dictionary.Add("parse_ViewSourceLabel", "View Source:");
            Dictionary.Add("parse_ViewTypeLabel", "View Type:");
            Dictionary.Add("parse_ParseableTabHeader", "Parseable");
            Dictionary.Add("parse_YouHeader", "You");
            Dictionary.Add("parse_PartyHeader", "Party");
            Dictionary.Add("parse_AllianceHeader", "Alliance");
            Dictionary.Add("parse_OtherHeader", "Other");
            Dictionary.Add("parse_OverallTotalsDamageHeader", "Overall Totals (Damage)");
            Dictionary.Add("parse_OverallTotalsDamageOverTimeHeader", "Overall Totals (Damage Over Time)");
            Dictionary.Add("parse_OverallTotalsHealingHeader", "Overall Totals (Healing)");
            Dictionary.Add("parse_OverallTotalsHealingOverHealingHeader", "Overall Totals (Healing Over Healing)");
            Dictionary.Add("parse_OverallTotalsHealingOverTimeHeader", "Overall Totals (Healing Over Time)");
            Dictionary.Add("parse_OverallTotalsHealingMitigatedHeader", "Overall Totals (Healing Mitigated)");
            Dictionary.Add("parse_OverallTotalsDamageTakenHeader", "Overall Totals (Damage Taken)");
            Dictionary.Add("parse_OverallTotalsDamageTakenOverTimeHeader", "Overall Totals (Damage Taken Over Time)");
            Dictionary.Add("parse_OverallTotalsBuffsHeader", "Overall Totals (Buffs)");
        }
    }
}
